### ISSUE TITLE
Extract MiniMagick processing into a separate gem.

### ISSUE THREAD

**Issue by jnicklas** [refile/refile#106]
People have to add a dependency on MiniMagick in their Gemfile anyway.

Putting this out there as a point of discussion. Should we do this? Why, why not?

**Comment by kwando** [comment]
I think it makes sense to have it in separate gem.

**Comment by balexand** [comment]
I would like to see it broken out into a separate gem. That way, another processing service could be substituted. For example, a service like http://www.imgix.com/ could be used. Or a microservice written in another language could be used.

**Comment by jnicklas** [comment]
Done.
