### ISSUE TITLE
Extract S3 backend into a separate gem

### ISSUE THREAD

**Issue by jnicklas** [refile/refile#114]
It feels nice having S3 support baked right in, but at the same time there's just something strange about having this one blessed backend in the gem when everything else is split out. Additionally the tests for S3 don't run along with the regular test suite.

It'd also like to split out everything which requires additional gems, so we can set up proper dependencies for them.

``` ruby
gem "refile", require: "refile/backend/s3"
gem "aws-sdk"
```

vs.

``` ruby
gem "refile"
gem "refile-s3"
```

**Comment by andrewhavens** [comment]
:+1:
