### ISSUE TITLE
Doesn't work on nested resources

### ISSUE THREAD

**Issue by alexandremcosta** [refile/refile#142]
Does refile works on nested resources? I don't think so.
I'm able to update every single normal field, but not the refile images.

One detail is that if I debug, I can see that `@page.update_attributes(permitted_params)` does NOT update refile images, so `@page.studio.profile_image_id` is still nil after that. But `@page.studio.profile_image` actually returns a refile object during the debugging section. After the debugging, the object is not there anymore, neither profile_image_id is set.

And if I do something like `@page.studio.update_attributes(permitted_params[:studio_attributes])`, during the debugging section, it does persist the image and the profile_image_id!

Here is the code:

page.rb
```ruby
class Page < ActiveRecord::Base
  has_one :studio
  accepts_nested_attributes_for :studio
end
```

studio.rb
```ruby
class Studio < ActiveRecord::Base
  belongs_to :page

  attachment :profile_image
  attachment :background_image
end 
```

pages_controller.rb
```ruby
PagesController < ApplicationController
  prepend_before_filter :load_object, only: [:edit, :update]

  def edit
  end 

  def update
    if @page.update_attributes(permitted_params)
      redirect_to account_path
    else
      render 'edit'
    end 
  end 

  private
  def load_object
    @page = Page.find(params[:id])
    @page.build_studio if @page.studio.nil?
  end 
  def permitted_params
    params.require(:page).permit(
      :slug,
      studio_attributes: [:id, :name, :profile_image, :remove_profile_image, :background_image, :remove_background_image])   
  end 
end
```

views/pages/edit.html.erb
```erb
<%= form_for @page do |f| %>
  <%= f.fields_for :studio do |studio_form| %>
    <p class="form-group">
      <%= studio_form.label :name, t('studio.name') %>
      <%= studio_form.text_field :name, :class => 'form-control' %>
    </p>
    <div class="form-group">
      <%= studio_form.label :profile_image, t(:profile_image) %>
      <% if studio_form.object.profile_image_id? %>
        <div class="image">
          <%= attachment_image_tag(studio_form.object, :profile_image, :fill, 100, 100) %>
          <%= studio_form.check_box :remove_profile_image %>
          <%= studio_form.label :remove_profile_image %>
        </div>
      <% end %>
      <%= studio_form.attachment_field :profile_image, direct: true, presigned: true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= studio_form.label :background_image, t(:background_image) %>
      <% if studio_form.object.background_image_id? %>
        <div class="image">
          <%= attachment_image_tag(studio_form.object, :background_image, :fill, 100, 100) %>
        </div>
      <% end %>
      <%= studio_form.attachment_field :background_image, direct: true, presigned: true, :class => 'form-control' %>
    </div>
  <% end %>
  <p class="form-group">
    <%= f.label :slug, t('studio.slug') %>
    <%= f.text_field :slug, :class => 'form-control' %>
  </p>
  <div class="form-actions" data-hook="buttons">
    <%= f.submit t('update'), class: 'btn btn-primary' %>
    <span class="or"><%= t(:or) %></span>
    <%= link_to t('actions.cancel'), account_path, class: 'btn btn-default' %>
  </div>
<% end %>
```

Gemfile
```ruby
(...)
gem "mini_magick"
gem "refile", require: ["refile/rails", "refile/image_processing"]
gem "aws-sdk"
```

**Comment by jcutrell** [comment]
I had a similar issue; tried removing the javascript, and mine works fine. Wondering if there's something wonky happening with the cache_id getting translated over on save for nested resources?

**Comment by alexandremcosta** [comment]
I fixed with a before filter that saves only the nested resource first (argh! ugly!). And this messes up my validations.

**Comment by jnicklas** [comment]
Ugh I'm getting a case of déjà vu :( I have a feeling we ran into this exact problem with CarrierWave at some point. There's something weird and wonky going on with Callbacks and nested forms that I can't quite remember. I'm sure this is fixable somehow. I'd appreciate any help in tracking this down, I don't tend to use nested_forms that often myself.

**Comment by janko-m** [comment]
I'm not able to reproduce this problem. The following works for me on ActiveRecord 4.1.10.

```rb
require "active_record"
require "sqlite3"
require "refile"
require "refile/attachment/active_record"
require "tmpdir"

Refile.cache = Refile.store = Refile::Backend::FileSystem.new(Dir.tmpdir)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "nested.db")
ActiveRecord::Migration.verbose = false

ActiveRecord::Migration.class_eval do
  create_table :pages, force: true
  create_table :studios, force: true do |t|
    t.integer :page_id
    t.string :profile_image_id
    t.string :background_image_id
  end
end

class Page < ActiveRecord::Base
  has_one :studio
  accepts_nested_attributes_for :studio
end

class Studio < ActiveRecord::Base
  belongs_to :page

  include Refile::ActiveRecord::Attachment
  attachment :profile_image
  attachment :background_image
end

image = File.open(__FILE__)
page = Page.create
page.build_studio

page.update(studio_attributes: {profile_image: image, background_image: image})

puts page.studio.profile_image_id
puts page.studio.background_image_id

page.update(studio_attributes: {profile_image: image, background_image: image})

puts page.studio.profile_image_id    # different id
puts page.studio.background_image_id # different id
```

**Comment by alexandremcosta** [comment]
@janko-m I think it has something to do with the javascript layer, as @jcutrell said. That's why your script works. Try to reproduce via form completion, I wrote an edit.html.erb example on my previous post.

**Comment by janko-m** [comment]
After you attach the image, and it gets uploaded directly or presigned (btw, does it fail both with directly and presigned, or only one of those two?), what image attributes get sent in the params?

**Comment by alexandremcosta** [comment]
It fails anyway, directly, presigned, or without those options.
The attributes are perfect just as a normal accepts_nested_attributes_for, I've checked myself before posting the issue, so I know the problem isn't there. If you really need this exact information (ctrl-c ctrl-v), I will need more time. My project doesn't use nested images anymore since I wasn't able to get it to work.

**Comment by janko-m** [comment]
Ok, don't bother, I thought you still had the code, I will try to reproduce it myself.

**Comment by janko-m** [comment]
Still can't reproduce:

1. `rails new my_app`
1. added `gem "refile", require: ["refile/rails"]`
1. created both models and migrations
1. pasted in your PagesController
1. added `resources :pages`, `root to: ->(env) { [200, {}, []] }` to config/routes.rb
1. swapped out `account_path` with `root_path`
1. added `//=require refile` to app/assets/javascripts/application.js
1. both attachments successfully upload in the background, and after submission studio's `<attachment>_id` columns are filled in

**Comment by alexandremcosta** [comment]
weird...I will create a repository to reproduce it...in the meantime, you can close this issue

**Comment by stefanroex** [comment]
I'm experiencing a similar issue. I noticed the bug is caused by Active Record dirty tracking which isn't able to label the attachment-attribute as dirty. The result is that nested fields will work fine as long as other attributes are labeled as dirty (or if it's a new record).

@alexandremcosta To confirm this, perhaps you could try saving the the form with and without changing the studio-name attribute.

**Comment by kirillsalykin** [comment]
Hi all,

Looks like it is still broken.

I'm using this to workaround it:

```ruby

if theme_params[:quote_attributes].key?(:image) || theme_params[:quote_attributes].key?(:remove_image)
  @theme.quote.image_id_will_change!
end

 if theme_params[:fact_attributes].key?(:icon) || theme_params[:fact_attributes].key?(:remove_icon)
   @theme.fact.icon_id_will_change!
 end
```

i hope this will help to identify the problem.

I will try to create pull request with fix, but have not much time to do it now. :(

**Comment by kirillsalykin** [comment]
Also, 

it works if you do it from the console (like @janko-m) but doesnt work from rails itself. Very weird.

**Comment by janko-m** [comment]
I think this fix is still in master only, are you pulling from there?

**Comment by kirillsalykin** [comment]
@janko-m yes, i tried from master.

**Comment by balexand** [comment]
@janko-m @kirillsalykin I was just bitten by this bug. I can verify that it is fixed in `master`.

I've created [a branch that back-ports the fix to the `stable-0.5` brach](https://github.com/refile/refile/compare/stable-0.5...VELCROMAGNETS:active_record_dirty).  I'm going to reference this branch immediately in my production app. 

I'd be happy to submit a pull-request with the back-port so the fix could be released right away. Please let me know if this is something you'd be willing to merge. It's a bummer that this was fixed a month ago in #201 but isn't in a stable release yet.

**Comment by kirillsalykin** [comment]
@balexand @janko-m i confirm, upload works on master. But image removal doesnt :)
eg remove_icon: true - not triggered

Can you please check?

**Comment by jnicklas** [comment]
@balexand a month is not a long time in the context of an open-source project. I'd be okay with merging a backport if you submit a PR for it.

**Comment by yaroslav** [comment]
@jnicklas could you make a minor release with this? Surprised it's not in stable... To the point when I've actually invested a ton into my code after seeing this is obviously fixed :) Funny thing, my fault, but guess you get my point.
