### ISSUE TITLE
Cache URL breaks when model fails to save

### ISSUE THREAD

**Issue by lserman** [refile/refile#146]
Hey guys, looking for an elegant way around this problem.

My edit form shows a user's current avatar using `<%= image_tag attachment_url(@user, :avatar, :fill, 75, 75) %>`. I upload the image with the `direct: true` option, so it is on the cache before I submit the form.

If I submit the form and the user fails to save because of any unrelated validation errors, the URL given by `attachment_url` links to a broken image ("/attachments/cache/fill/75/75/.../image.png" for example).

If this were another field, a name for example, I normally would show `<%= @user.name_was %>` instead, so that the name will appear as it was before the attempted save. Using ActiveModel::Dirty in this case won't work though because of the structure of `attachment_url`.

What is the best way around this problem?

**Comment by jnicklas** [comment]
Why is that URL broken? I'm not sure what's going wrong here. Refile should "just work" for this exact use-case. Maybe I'm not understanding the issue correctly.

**Comment by lserman** [comment]
I'm not sure, that's what I'm trying to figure out here. I can look into it a bit more this weekend and try to give you some more information, but I am pretty much just using the standard configuration right out of the box with the built-in Sinatra app as the CDN on localhost.

**Comment by jnicklas** [comment]
@lserman if you can share the code you have, that might help. Or if you could write a failing test, that would be even more awesome.

**Comment by lserman** [comment]
Sorry I didn't get around to this on the weekend like I said. I'll get you some code ASA, hopefully tonight.

**Comment by lserman** [comment]
K, so:

In my model:

```
attachment :image
validates :name, presence: true
```

In controller, pretty standard stuff

```
def update
  @user.update permitted_params
  respond_with @user
end

def permitted_params
  params.require(:user).permit :name, :image
end
```

Gemfile:

```
gem 'refile', require: ['refile/rails', 'refile/image_processing']
```

I have a custom SimpleForm input that renders this partial, so here `object` is the User instance and `attribute` is `:image`:

```
<div>
  <%= attachment_image_tag object, attribute, :fill, width, height, class: 'img-circle', fallback: holderjs(width, height) %>
  <div class="uploader">
    <%= f.attachment_field attribute, direct: true %>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" style="width: 0%">
      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
```

I'm using the standard /attachments mounted app for development. Steps to reproduce:

- Upload an image, which works ("upload:complete" event fired etc).
- Delete the name from the textbox to break the name presence validation
- Submit the form, name presence error is shown and record is not saved
- Image URL generated by `attachment_image_tag` is now broken 

The image element looks like this:

```
<img class="attachment user image img-circle" src="/attachments/cache/fill/100/100/f132e31a3e13bb954be36be892d5d4f58208cc2f159ed3e521e9564006f4/rails.jpg" alt="Rails">
```

When submitting the form without errors, everything works fine.

**Comment by jnicklas** [comment]
Please provide an *executable* example.

**Comment by lserman** [comment]
I made a Heroku app to reproduce this issue: https://dry-mesa-3488.herokuapp.com/widgets

Try to create a new Widget. At first there is a LoremPixel thumbnail (`fallback:` option `attachment_image_tag`). Choose a file and submit without filling in name. The name presence validation will fail, and `attachment_image_tag` shows a broken image.

I just used the Heroku getting started repository. You can see my setup here, it basically just the Refile quick start: https://github.com/lserman/refile146/commit/fcfd9d9e8831f89089172e7104e4ecf47af5f89e

The repo is here https://github.com/lserman/refile146 , feel free to pull it yourself and give it a try of course. Let me know if I can do anything else.

**Comment by jnicklas** [comment]
`bundle update mini_magick` ;)

Here's how I figured it out: Make sure to look at the log output! The log output clearly shows that this is a problem with mini_magick, if you'd have posted the stack trace here, I'd have been able to help you much faster. If you have a problem with some kind of gem the first thing to try is always to make sure you're on the latest version, someone might have fixed it already.

**Comment by lserman** [comment]
Thanks, I could have sworn I checked the log and didn't see anything helpful when I originally reported this issue. All good now :+1:
