### ISSUE TITLE
if I have comma in file name I got error 403

### ISSUE THREAD

**Issue by eddiefisher** [refile/refile#149]
```Aprel.Starye_vetly.2003._Holst,maslo._35h50___7000rub.___1.jpg``` - original name

helper ```attachment_image_tag``` give me:
```
<img alt="Sostav.gerbera_7sht.%2csalal%2ckorkas%2cstrazy.tsena_830r._1" class="attachment delivery_item file" src="/attachments/a6960bb4e54cb65690cfbbda33281c28fc3eb91e/store/fit/160/120/92facb231bc5b02da9babaa2d0873b8d363c27a198a9c7b276a0073d6e91/Sostav.Gerbera_7sht.%2Csalal%2Ckorkas%2Cstrazy.Tsena_830r._1.jpg" style="max-width: 160px">
```

and now we have other file name: ```Sostav.Gerbera_7sht.%2Csalal%2Ckorkas%2Cstrazy.Tsena_830r._1.jpg```

comma was replaced on '%2C'

how I can fix it?

**Comment by eddiefisher** [comment]
on rails 3 I have this error, but on rails 4 working is fine

**Comment by jnicklas** [comment]
The filename is URI encoded to prevent any evil shenanigans. If you really want to work around this you'll need to manually generate a URI. But be careful, only do this if you're sure you can trust the input.
