### ISSUE TITLE
unable to upload .png files

### ISSUE THREAD

**Issue by acandael** [refile/refile#153]
Hi, great gem, but for some reason I cannot upload .png files.

greetings,

Anthony

**Comment by jnicklas** [comment]
Sorry, Refile does not support PNG files.

**Comment by jnicklas** [comment]
Just kidding ;) Seriously though, you're gonna have to give me a bit more than "I cannot". See https://github.com/elabs/refile/blob/master/CONTRIBUTING.md. Please include stack traces.

**Comment by acandael** [comment]
hi jnicklas,

sorry, I thought it was just a simple config setting, but when I look at the server stack trace there seems to be an error after uploading a .png image:

    Started GET     "/attachments/cache/fit/150/150/2553cdf41486520f1e53c80bb4a5c0de296748c287cdd7487e9ec7053d    e0/image" for ::1 at 2015-02-19 11:00:43 +0100
    Refile::App: Error -> `mogrify -resize 150x150    /var/folders/d1/v45l12z501jg5d505lwbmy080000gn/T/2553cdf41486520f1e53c80bb4a5c0de296748c2    87cdd7487e9ec7053de020150219-15214-vd1tq9` failed with error:
    mogrify: unable to load module `/usr/local/Cellar/imagemagick/6.8.6-3/lib/ImageMagick//modules-    Q16/coders/png.la': file not found @ error/module.c/OpenModule/1277.
    mogrify: no decode delegate for this image format     `/var/folders/d1/v45l12z501jg5d505lwbmy080000gn/T/2553cdf41486520f1e53c80bb4a5c0de296748c2    87cdd7487e9ec7053de020150219-15214-vd1tq9' @ error/constitute.c/ReadImage/552.

I'm using Rails version 4.2
in my Gemfile I added:
    gem "mini_magick"
    gem 'refile', '~> 0.5.3', require: ["refile/rails", "refile/image_processing"]

my repository can be found here:
https://github.com/acandael/adlit-rails

**Comment by jnicklas** [comment]
Sounds like there is a problem with your imagemagick install. "brew update"
and reinstall.

**Comment by acandael** [comment]
yeah, that fixed it. I ran:

brew outdated

to get a list of outdated packages

and then I ran

brew upgrade

now I can upload .png files

greetings,

Anthony
