### ISSUE TITLE
Are files downloaded via Refile.attachment_url cached?

### ISSUE THREAD

**Issue by davidcelis** [refile/refile#158]
Hi! I’ve been using Refile on a recent project of mine, and this involves using `Refile.attachment_url` to set the `src` attribute of HTML5 `<audio>` tags and then playing them. I’ve noticed that in some browsers, finally starting playback of the audio file will end up making multiple GET requests. Safari will make anywhere between 3 and 6, Firefox tends to make 2, and Chrome makes one. Normally I wouldn’t worry too much about this, but my files are being stored in S3 so bandwidth is a little bit of a concern for me.

I was wondering if those 6 GET requests to Refile’s Sinatra app actually result in 6 requests to S3 or if the Sinatra app does any sort of caching to prevent requesting files over and over.

**Comment by jnicklas** [comment]
From the README:

----

**Important:** Unlike other file upload solutions, Refile always streams your files through your
application. It cannot generate URLs to your files. This means that you should
**always** put a CDN or other HTTP cache in front of your application. Serving
files through your app takes a lot of resources and you want it to happen rarely.

Setting this up is actually quite simple, you can use the same CDN you would use
for your application's static assets. [This blog post](http://www.happybearsoftware.com/use-cloudfront-and-the-rails-asset-pipeline-to-speed-up-your-app.html)
explains how to set this up (bonus: faster static assets!). Once you've set this
up, simply configure Refile to use your CDN:

``` ruby
Refile.host = "//your-dist-url.cloudfront.net"
```

Using a [protocol-relative URL](http://www.paulirish.com/2010/the-protocol-relative-url/) for `Refile.host` is recommended.

**Comment by davidcelis** [comment]
Ah sorry, I didn't catch that first sentence in that README section. Thanks!
