### ISSUE TITLE
AWS S3 backend for production and file backend for development mode

### ISSUE THREAD

**Issue by acandael** [refile/refile#161]
I'm trying to configure the Refile gem so that files are uploaded to Amazon S3 in production mode, but in development mode files are uploaded to the file system.

my config/initializers/refile.rb file looks like this:

    require "refile/backend/s3"

    aws = {
      access_key_id: Rails.application.secrets.s3_key, 
      secret_access_key: Rails.application.secrets.s3_secret, 
      bucket: "adlit",
    }
    Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
    Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)
    end

but when I try to upload an image in development, I get this error message:

    Missing Credentials. Unable to find AWS credentials. You can configure your     AWS credentials a few different ways: * Call AWS.config with :access_key_id and     :secret_access_key * Export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to ENV *...

So I tried to fix this by adding the configuration in a conditional:

    if Rails.env.production
      ...
    end

But that didn't fix it, I still get the above error message in development mode.

Does anyone know how I can configure Refile to upload file to Amazon S3 in production and to the file system when in development mode?

thanks for your help,

Anthony

**Comment by jnicklas** [comment]
Just wrap it in:

``` ruby
if Rails.env.production?
  aws = {
    access_key_id: Rails.application.secrets.s3_key, 
    secret_access_key: Rails.application.secrets.s3_secret, 
    bucket: "adlit",
  } 
  Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
  Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)
end
```

As you wrote. That should do the trick.

**Comment by LuckyThirteen** [comment]
@acandael you can also try fakes3 in dev env, see [this](https://github.com/refile/refile/pull/43)

**Comment by acandael** [comment]
I recall, in a previous project where I used Carrierwave, I had denied access issues. I fixed that by adding the region parameter to my configuration.

I was hoping I could solve the problem with Refile the same way:

require "refile/backend/s3"

    if Rails.env.production?
    aws = {
      access_key_id: Rails.application.secrets.s3_key, 
      secret_access_key: Rails.application.secrets.s3_secret, 
      bucket: "adlit",
      region: "eu-west-1"
    }

    Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
    Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)
    end

but that didn't fix it.

**Comment by acandael** [comment]
@LuckyThirteen thanks!
But my issue with the development environment is fixed by wrapping the configuration in a

    if Rails.env.production?

condition.

The issue I have at hand for the moment is a connection issue with AWS in production.

**Comment by jnicklas** [comment]
@acandael If you have a separate issue, please create a separate issue for it. Though this sounds more like a problem with AWS than with Refile, so you might have more luck contacting Amazon.

**Comment by acandael** [comment]
it was indeed a problem with the environment variables. It's solved now.

**Comment by baothi** [comment]
thanks @jnicklas

**Comment by likelionSungGuk** [comment]
@acandael I got similar but opposite problem. In my application, it works well in development mode. My files and images uploaded well in aws s3 bucket, but now working in production mode. Could you tell me how to fix it?
