### ISSUE TITLE
Support actionform

### ISSUE THREAD

**Issue by TangRufus** [refile/refile#165]
Add support for [actionform](https://github.com/rails/actionform).

So far, `undefined method 'profile_image_attacher' for #<UserForm:0x007fa6a9f59b58>` shows up because the form object is not a active record.

Is it possible to include the helpers to the form objects?

Thanks!!

**Comment by TangRufus** [comment]
Note: treating the actionform objects as [pure ruby classes](https://github.com/refile/refile#pure-ruby-classes) is a quick fix for now

**Comment by TangRufus** [comment]
Adding the following gist allow you to declare refile `attachment` in ActionForm objects. However, it doesn't work on nested resources (maybe related to #142 )

```
#app_root/config/initializers/refile_action_form.rb

module Refile
  module ActionForm
    module Attachment
      include Refile::Attachment

      # @see Refile::Attachment#attachment
      def attachment(name, raise_errors: false, **options)
        super

        attacher = "#{name}_attacher"

        validate do
          if send(attacher).present?
            send(attacher).valid?
            errors = send(attacher).errors
            self.errors.add(name, *errors) unless errors.empty?
          end
        end

        after_save do
          send(attacher).delete!
        end
      end
    end
  end
end

::ActionForm::Base.extend(Refile::ActionForm::Attachment)
```

**Comment by jnicklas** [comment]
@TangRufus this kind of thing is perfect to release as a gem :)
