### ISSUE TITLE
Do we really care about meta that much?

### ISSUE THREAD

**Issue by div** [refile/refile#166]
Currently refile deals with filenames, sizes and content type. But i'm not really sure that it should be dealing with those things. It's more of the domain logic to handle flienames and sizes and their validations. There are no real validations in refile and i don't think that there should be any. I think all that meta handling looks really orthogonal to the core of gem. If we could delegate it somewhere it would greatly simplify the api. 

The attacher will only have to deal with Refile::File and not with json as it is now https://github.com/refile/refile/blob/master/lib/refile/attacher.rb#L79

1. Size - it's the easiest to deal with - because we should not. #100
2. Filename - I think it's really domain specific. I would say that 90% of usecases for refile are images, where you do not really care about filenames. But if you do, you probably want to handle them in some specific way - validate, replace non utf symbols or whatever. So you would want to do it yourself anyway. 
I think refile should not care about filenames at all.
3. Content-Type - is the tricky one, because we really need it. Firstly - we should not trust the user input, because it is easily spoofed. And if we do not trust, why would we want to throw it in the db? Secondly - if we have the file, the only thing we might've lost is the extension - which does not have anything to do with content type. So we should always be able to get content type out of the file itself. 

So what i propose is following:

1. Refile does no take user input with all that meta, only file. If some validations and/or filename handling are needed - it's super easy to implement, it might be something like this
```
class ImagesController < ApplicationController
  def create
    tempfile = params.fetch(:file)
    validator = ImageValidator.new(tempfile)
    if validator.valid?
      file = Refile.cache.upload(tempfile)
      url = Refile.attachment_url(file, :file)
      render json: {id: file.id, url: url}
    else
      render json: {errors: validator.errors }, status: :unprocessable_entity
    end
  end
end
```
(notice how Refile.attachment_url takes just Refile::File here and not the AR model, which is cool!)
There you can have all your meta validated, if you only cache! at this point, and not yet saving to db, you could just Rails.cache this meta with :id as a key, and grab it when the model is being saved.

2. Size and content type can be fetched by the backends, so you have an option to save it in a db or not.

3. All the AR methods are now dealing with only Refile::File or ids, no json blobs. And even more important with multiple file upload - https://github.com/refile/refile/issues/6#issuecomment-69889699
we could have images_files_ids setter here, which would be much easier to use then handling array of jsons.

So it all comes down to this - we could get rid of all the meta handling logic in refile, and explain how to do it in a controller instead if needed. What do you think?

**Comment by dpehrson** [comment]
I agree with you from an engineering perspective, but from an end-user perspective these meta attributes are pretty important quite often.

I switched from dragonfly to refile for a new project because it appears better maintained, but am seriously considering switching back because it provides no way (I can find) to easily get the dimensions of an uploaded image which is important to what I do.

**Comment by div** [comment]
@dpehrson Refile does not care about dimensions, MiniMagick does.
```
  image = MiniMagick::Image.open("input.jpg")
  image.path #=> "/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/magick20140921-75881-  1yho3zc.jpg"
  image.type        #=> "JPEG"
  image.mime_type   #=> "image/jpeg"
  image.width       #=> 250
  image.height      #=> 300
  image.dimensions  #=> [250, 300]
```

Straight form the docs https://github.com/minimagick/minimagick

**Comment by dpehrson** [comment]
@div I know, I am just looking for the more streamlined integration offered via the style of dragonfly. Just my two cents.

**Comment by jnicklas** [comment]
Metadata came pretty late in terms of features, in the beginning we had only storage of `id`. The reason we added metadata storage was because there was very intense demand for it. It was easily the most requested feature.

As for image dimensions, the reason I've been reluctant to add stuff like this is that it'd have to special cased in the JS code, there isn't really any way to add "plugins" to the JS code. Maybe it's worth revisiting though.

**Comment by dpehrson** [comment]
@jnicklas I appreciate you taking the time to respond, I use many of your open source libraries and am very appreciative for all the time you must put in.

Additionally, I completely understand the reasoning behind why this functionality doesn't exist.

For me, knowing the height/width of the image uploaded is important for a few reasons:

1. Outputting proper height/width attributes to prevent page jumps during rendering.
2. Knowing the aspect ratio of the image to determine applicability of images for certain jobs (eg. avatars must be 1:1, lifestyle images must be 16:9, etc.)
3. The ability to do proper calculations when resizing or copping images.

To be honest, I'd even be happy with a simple, but official wrapper for the code @div posted. Perhaps a method that people like myself could use in a `before_validate` model that would pull the source file, snag the dimensions, an populate the height/width attributes appropriately. This could even come with a big warning that says "Hey idiot, if you use this, it will add overhead."

It wouldn't be perfect, but it would give us the choice to accept that overhead.

Once again, thank you for everything!

**Comment by jnicklas** [comment]
@dpehrson Added a tracking issue for this, see #168. That doesn't mean we'll definitely do it, just that we should look into it more.

Closing this issue in the meantime. Metadata is here to stay.
