### ISSUE TITLE
Authorization with Pundit

### ISSUE THREAD

**Issue by jeromedoyle** [refile/refile#169]
Is there a way to do authorization on uploaded files with Pundit? I have uploaded files which should be restricted to the user that uploaded them, but anyone with the url that attachment_url generates can access the file. Since Refile uses the sinatra app, there's no controller for me to call Pundit's authorize method in.

**Comment by jnicklas** [comment]
Just don't give them the URL then ;)

Refile ids are practically impossible to guess. The next version will also have checksum based verification on URLs. As long as you don't hand out the URL, people won't be able to access the files.

**Comment by jeromedoyle** [comment]
I would love if it were that simple :)
Unfortunately, my users may know each other, so the possibility of them sharing the url is pretty high. I don't know a lot about Sinatra. Do you know of a way that Refile could call out to Pundit headless policy? As far as the checksum verification, how would that help me. Wouldn't that only allow me to verify that the file requested is what I received from the download, or are you talking about something different?

**Comment by jnicklas** [comment]
The other option you have is to simply serve the files from a Rails controller instead. It should be fairly simple to figure out how to do this. You lose some of the convenience of Refile, but it gives you a lot of flexibility.

**Comment by jeromedoyle** [comment]
I am now serving the files through my controller and it works great. I'm serving pdfs so I didn't lose any functionality. Thanks for the advice and the awesome gem!
