### ISSUE TITLE
Missing images on production after deploy

### ISSUE THREAD

**Issue by Wilkerson** [refile/refile#170]
I'm getting a "no find image error" after deploy, using Capistrano... Seems like the app can't find the image after assets precompile... should i set up a directory for shared_children, or something like that? Thanks.

**Comment by jnicklas** [comment]
If you deploy with Capistrano and you use the FileSystem backend in production then you definitely need to set something like that up. There are various guides on how to do this. Be aware that this essentially prevents you from scaling to more than one server though. S3 might be an easier option for production.
