### ISSUE TITLE
File size validation

### ISSUE THREAD

**Issue by 5t111111** [refile/refile#174]
While I'm sure it's controversial if file size in metadata is reliable like #100, I think file size validation is still   a good feature for convenience.

So I've roughly monkey-patched `valid?` of `Attacher` class.

```ruby
module Refile
  class Attacher
    def valid?
      @errors = []
      @errors << :invalid_extension if valid_extensions and not valid_extensions.include?(extension)
      @errors << :invalid_content_type if valid_content_types and not valid_content_types.include?(content_type)
      @errors << :exceeds_allowed_size if @metadata[:size] and @metadata[:size] > 1024 * 1024 # file size should be within 1MB
      @errors << :too_large if cache.max_size and size and size >= cache.max_size
      @errors.empty?
    end
  end
end
```

I'd like to know if there's better way to validate the size of the file to be uploaded or if you are planning to add file type validation feature.

**Comment by jnicklas** [comment]
We already have validation of size, simply set `max_size` in your backend. It's the line below the one you added ;)

**Comment by jnicklas** [comment]
It's actually documented in the README:

---

Backends also provide the option of restricting the size of files they accept. For example:

``` ruby
Refile.cache = Refile::Backend::S3.new(max_size: 10.megabytes, ...)
```

**Comment by 5t111111** [comment]
Ahh, yes true, it's exactly my bad. I should have read a bit more :sob: 
Anyway thanks for the information!
