### ISSUE TITLE
File size validation fails

### ISSUE THREAD

**Issue by 5t111111** [refile/refile#175]
I've set `max_size` to limit uploadable file size to the backend (I'm using `FileSystem` for the moment).

```ruby
# config/initializers/refile.rb
Refile.cache = Refile::Backend::FileSystem.new("tmp/uploads/cache", max_size: 1.megabytes)
Refile.store = Refile::Backend::FileSystem.new("tmp/uploads/store")
```

However, after adding the above lines, my application always fails with the below error, even when just displaying a form which has `f.attachment_field` in it.

```
comparison of String with 1048576 failed
```

For the workaround, I had to add `to_i` to `size` method's return value in `Attacher#valid?` to avoid type mismatch like this.

```ruby
@errors << :too_large if cache.max_size and size and size.to_i >= cache.max_size
```

I haven't confirmed that it occurs when you are using S3 as the backend.

**Comment by janko-m** [comment]
When does this happen? Before you even upload the image? I'm assuming you have the `image_size` column in your table, right?. It seems to me that this error can happen if you made the type of the `image_size` column `String` (varchar) instead of `Integer`.

**Comment by 5t111111** [comment]
As you guessed, I have accidentally set type of the one of the `image_size` columns. Sorry, I appreciate your help. I'm going to close this issue because it's just a wrong configuration issue.
