### ISSUE TITLE
Silence when "image_id" column is absent

### ISSUE THREAD

**Issue by janko-m** [refile/refile#176]
I was contributing to Refile a bit in its earlier stage, so I've gotten quite familiar with it. However, it still took me about an hour to figure out why my image ID wasn't saved. It turned out that instead of `avatar_id` column, I had an `avatar` column (silly me :)).

However, I wish that Refile had told me about it. It didn't because there are guards on `Refile::Attacher#read` and `Refile::Attacher#write` which don't do anything if the `avatar_id` accessor isn't defined. Why are those guards there? First I thought the reason is usage in POROs, but the readme says that you should define `attr_accessor :profile_image_id`.

**Comment by jnicklas** [comment]
I think it's somewhat accidental in that we're using the same code path for all columns we're reading and writing, and for all the other wants we want them to be silently ignored. Maybe it would be better to be stricter about the `id` column though.
