### ISSUE TITLE
Add a route helper, or allow the app to be mounted manually

### ISSUE THREAD

**Issue by jph** [refile/refile#179]
I work on an application where a devise/warden session is required for any routes to appear. I would like to extend this security to the /attachments mount point however it doesn't look like there's a method to do this.

I have experimented in mounting Refile.app, however the route being added within the gem is obviously still being mounted (which is a nice touch, that way I don't have to put this line into my routes at all):

```ruby
Rails.application.routes.draw do
  authenticated :user, ->(u) { u.admin? } do
    mount Refile.app => "/files"
  end
end
```
I lack the technical expertise to put together a pull request for something this deeply ingrained into your application, otherwise I would do so. I hope I've given you enough information for something I see as a great addition to the project!

**Comment by jnicklas** [comment]
You can set:

``` ruby
Refile.automount = false
```

And Refile won't add any routes.
