### ISSUE TITLE
Upload processed files to S3

### ISSUE THREAD

**Issue by lazaronixon** [refile/refile#180]
As mentioned on documentation of cloudfront:
>"**If an object in an edge location isn't frequently requested, CloudFront might evict the object—remove the object before its expiration date—**to make room for objects that are more popular."

Could be useful if after file processed refile upload it to S3, Then if it isn't cached don't reprocess again and get from S3. "The cache of cache".

More discussion here:
http://stackoverflow.com/questions/26632210/cloudfront-ttl-not-working

**Comment by jnicklas** [comment]
Is this an actual problem for you? I understand that sometime the cost of "long-tail" requests can be high, but if this is the case, maybe running your own HTTP cache is a better option? The handoff to S3 still won't be fast as CloudFront doesn't follow redirects.

**Comment by lazaronixon** [comment]
Yes.. three days without see the image and it hits the origin =/, so I have problems with memory and slow requests.

**Comment by jnicklas** [comment]
Hmm. Have you tried fiddling with Cache settings? This seems awfully short.

**Comment by Padchi** [comment]
I have the same problem, seems like my cached images are removed after just one  hour.

**Comment by jnicklas** [comment]
I think we won't do anything of the sort at the moment. There are plenty of ways of setting up HTTP caches which don't need any additional code in Refile. Effectively this just adds a cache, which is better done by something more general. Building a Rack-s3-cache middleware shouldn't be terribly hard for example.

I'm closing this issue.
