### ISSUE TITLE
CORS conflicts when being impatient

### ISSUE THREAD

**Issue by EtienneDepaulis** [refile/refile#181]
Hey guys,

I've just tried refile on a bucket I created for the occasion. I followed every steps, especially what is described in the CORS section.
However I encountered a nasty 'bug': S3 kept telling me I had not enabled CORS on my bucket.

I finally found the solution here: https://github.com/component/s3/issues/7#issuecomment-45581857 (TLDR; you have to wait for DNS propagation ...).
Maybe this is something worth mentioning on the README ? Would you like a PR for that or this issue is enough ?

Feel free to close this issue (as it is not an issue anymore)

**Comment by janko-m** [comment]
Thank you for letting us know about this, I added it to the readme.

**Comment by EtienneDepaulis** [comment]
Thx @janko-m !
Awesome work btw, it really did work in less than 5 min (if I don't count the DNS propagation) :)
