### ISSUE TITLE
How to add process view for uploading

### ISSUE THREAD

**Issue by misteral** [refile/refile#182]
How to add process view for uploading, like jquery file upload process, to form view?

**Comment by janko-m** [comment]
Refile provides a [JavaScript file](https://github.com/refile/refile/blob/master/app/assets/javascripts/refile.js) which you can include, and when the file is uploaded, the following JavaScript events get dispatched:

* `upload:start`
* `upload:progress`
* `upload:complete`
  * `upload:success`
  * `upload:failure`

You can read more about it in the [README](https://github.com/refile/refile#5-javascript-library).

**Comment by jnicklas** [comment]
I think @janko-m provided a good answer. Closing.
