### ISSUE TITLE
Error on Production / Rails

### ISSUE THREAD

**Issue by andrezimpel** [refile/refile#183]
In dev my rails app works just fine.

In production instead there is just no image, it's uploaded to the server but it just won't show up. I'm using the default backend.

When accessing the image url directly all I see is "error". :(

Hope somebody could give me a hint.

**Comment by jnicklas** [comment]
Try bumping the log level so you can see what's going on. A wild guess would be that imagemagick might not be installed or not working properly if you're using image processing?

**Comment by andrezimpel** [comment]
Got it!

Although imagemagick was installed, I was missing GraphicsMagick.

```
App 16260 stderr: Refile::App: Error -> ImageMagick/GraphicsMagick is not installed
```

**Comment by lualsiv** [comment]
On Mac, you can do brew install imagemagick, but that itself requires you to install Homebrew first
