### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by niels-s** [refile/refile#185]
Hey there,

I'm using Refile 0.5.3 in combination with Rails 3.2.20 and Devise 3.4.1. Now I'm having the strange behaviour on my app. I have everything deployed on a staging environment where they run in perfect harmony together. 
However when I deployed the code to production environment, things go wrong. 

Uploading attachments goes just fine with the refile.js library but from the moment I submit my form I get the following warning: `WARNING: Can't verify CSRF token authenticity`.
And as a result I'm redirected to login page again, as you may guess this behaviour is pretty annoying.
I'm hoping somebody could give me some pointers to look at since this is 100% related to refile I assume.

All help is really appreciated, thanks!

**Comment by jnicklas** [comment]
I don't think this is related to Refile. I don't think Refile would affect CSRF protection at all. Make sure you have the same setting in development for CSRF protection. Read up on CSRF protection in Rails (the security guide) if you don't know what this is all about.

**Comment by janko-m** [comment]
Does the same thing happen when you disable the refile.js library?

**Comment by niels-s** [comment]
When I try to submit the form without uploading a file, the form submits perfectly. But once I uploaded a file to the cache backend and I try to submit the form Rails can't verify CSRF Token. 
I've looked up some documentation on CSRF, so I'm going to look if form authenticity_token is changed by refile.js. Also will try @janko-m comment by disabling the refile.js lib.
Also will double check if there any differences between my staging and production environment.

**Comment by niels-s** [comment]
I've noticed my application cookie is changed after after I've uploaded a file but before I've submitted the form. So @jnicklas could it be this is related to refile(.js) after all?

**Comment by jnicklas** [comment]
Usually session cookie are HTTP only, so can't be affected by JS.

**Comment by niels-s** [comment]
@jnicklas, you're correct again. But in the mean while I've been looking around. I've noticed there is a difference between the behaviour on my staging and production environment. While on both environment the session is altered. On the staging environment it's only appended with what I assume is a hash of the filename or something like that. While on the production environment the session is decimated *and* appended with the same hash I mentioned before.
So I'm guessing the issue must come from here https://github.com/refile/refile/blob/master/lib/refile/app.rb#L59 some where. But I'm not able to pinpoint where issue directly comes from.

ps: I've checked my configurations for both staging and production. They are identical except for some different url's for email settings and CDN.

**Comment by jnicklas** [comment]
@niels-s this is super weird. We're not doing anything with sessions inside Refile. I really have no explanation for that. If it is something to do with Refile it'd be a really weird bug.

**Comment by niels-s** [comment]
@jnicklas I know, this is really strange. I've added the session I've gather to the comment here. I've looked into the code myself. The backend doesn't do anything session related but it happens.

I'm going to sleep maybe a fresh mind tomorrow could bring me some fresh ideas. Otherwise I fear I have to look for an alternative. Or dare I say it skip the verify authenticity token for this specific action.

Thanks for sharing your thoughts, let me know if you can think of something worth investigating. I'll see if I can take a look.

**staging before file upload**
BAh7CUkiD3Nlc3Npb25faWQGOgZFVEkiJTQ1MTJjNmEzOGQzZWM4OGEwYWVhYjMzNDJiYWQzZmY0BjsAVEkiE3VzZXJfcmV0dXJuX3RvBjsARiIGL0kiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsHWwZpBkkiIiQyYSQxMCRqN094WFo1c2Iub2NLNDV1OTQ1anh1BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMVpVTWQ3enh4bWVZUXFIMTBHL0c2eG1SZ3pCaCtPVCtacGR6TlRBZ1pmUkU9BjsARg

**staging after file upload**
BAh7CUkiD3Nlc3Npb25faWQGOgZFVEkiJTQ1MTJjNmEzOGQzZWM4OGEwYWVhYjMzNDJiYWQzZmY0BjsAVEkiE3VzZXJfcmV0dXJuX3RvBjsARiIGL0kiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsHWwZpBkkiIiQyYSQxMCRqN094WFo1c2Iub2NLNDV1OTQ1anh1BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMVpVTWQ3enh4bWVZUXFIMTBHL0c2eG1SZ3pCaCtPVCtacGR6TlRBZ1pmUkU9BjsARg%3D%3D--df35c23e52645eef8800ffdacf1897c762de364e

**production before file upload**
BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJTRkOTc2MzExYTk4YTU2NDAwMWExMTYwMDAzNzBlNmY5BjsAVEkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsHWwZpBkkiIiQyYSQxMCR3VVB6WTVZVGY1R3IzWDBCY0lqRmh1BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXE1M1hJeEVtdW40Y24rUGxOSlhoR1ArOGhVdUo0NW5kV2FCU1p4Q0VmTXM9BjsARg

**production after file upload**
BAh7BkkiD3Nlc3Npb25faWQGOgZFVEkiJTRkOTc2MzExYTk4YTU2NDAwMWExMTYwMDAzNzBlNmY5BjsAVA%3D%3D--0d88185d2e5d22d5f94c0579b060d13cc6b1da68

**Comment by janko-m** [comment]
One wild recommendation I could give you is to try to mount the Refile application directly in `config.ru`, to avoid any of Rails' middleware.

1. Set `Refile.automount = false` inside of `config/application.rb`, after gems are required (after `Bunder.require`). Maybe it can also go in an initializer, I'm not sure.
2. Transform your `config.ru` into this:

  ```rb
  require ::File.expand_path('../config/environment',  __FILE__)

  map "/" do
    run Kvizovi::Application
  end

  map "/#{Refile.mount_point}" do
    run Refile.app # or Refile::App
  end
  ```

I don't know which web server are you using in staging/production, but I think each one runs the application through `config.ru`.

**Comment by niels-s** [comment]
@janko-m, thanks for thinking along, I've tried your approach but than I can't use the rails [attachment_field](https://github.com/refile/refile/blob/6a25a2405964e6c8ad7eb1761a365ccdf7987961/lib/refile/rails/attachment_helper.rb#L73) helpers anymore. Because it fails to get the refile_app_path, even though I could get around this by manually adding everything myself that isn't a solution.

I also tried skipping the protect_from_forgery before_filter but because the cookie is changed the user isn't recognised anymore so then I get an unauthorised error. So I'm probably screwed if I don't find the origin of the problem.

**Comment by janko-m** [comment]
So you've tried `skip_before_filter :verify_authenticity_token`? Yeah, I think the culprit of this problem is the fact that your cookie gets changed. This is really weird, why would your browser be sending a different cookie to the server? In Chrome, try to go to "Networks" tab, and check "Preserve log", then see what's the value of the `Cookie` header on Refile's AJAX request (you're using direct uploads, right?) and then later your form submission. They should be the same (although I expect in your case they will be different).

How did commenting out `refile.js` go? I know this isn't the solution, but I just wanted to see if everything works normally.

**Comment by pankajp20** [comment]
I'm getting this error while updating a record on IE only. This do not happen application wide but occur for specific action of a controller. While submitting a form (action is used to update a record in DB), received error "Can't verify CSRF token authenticity". When checked form in IE, creates hidden field for "authenticity_token" but submitting the form redirect me to root URL of app (in application controller) and gives same error in console.

I tried to skip validating the CSRF token authenticity for this specific action but then form data is not submitted (write skip_before_action :verify_authenticity_token, only: [:] in my controller).

Any one have idea on this issue.

**Comment by janko-m** [comment]
Maybe it's Turbolinks?

**Comment by pankajp20** [comment]
Turbolink is disabled at present. This problem is coming after app migrated from Rails 3.2 to 4.2

**Comment by Darmody** [comment]
Did you guys use `remote=true`? I found this problem because I set `remote=true`.

**Comment by jnicklas** [comment]
AHHHHH!!! @Darmody thank you! That's the missing puzzle piece that explains this bug!

jquery-ujs does not support submitting forms with file fields via AJAX, so it won't actually do an AJAX request, it will instead do a regular form post. Unfortunately, when you use `remote: true`, Rails for some dumb reason does *not* add an authenticity token to the form. Instead it relies on jquery-ujs picking up the token from the `<meta>` tag it adds to `<head>`. But since we don't actually use AJAX, the form gets submitted without any authenticity token at all!

My suggestion would be to remove `remote: true`, since it doesn't do what you want anyway. If you want to submit the form via AJAX, do it manually with jQuery.

**Comment by pankajp20** [comment]
Thank you @Darmody and @jnicklas, but the actual problem was the "div"s. Structure of that page is based on "div" and one "div" (where the form lies) was placed inside table body mistakenly. And that "div" floats in the page causing this bug. Either no table should be used or the "div" should be inside a "td" tag.

**Comment by Darmody** [comment]
@jnicklas it works well with `remotipart`, if set remote true.

**Comment by jnicklas** [comment]
@pankajp20 with invalid markup, all bets are off ;)

@Darmody yeah that should work.

@niels-s can you check if any of these suggestions help your problem?

**Comment by fiedl** [comment]
I'm also experiencing **Can't verify CSRF token authenticity** after migrating from Rails 3.2 to Rails 4.1.

The issue does **only** occur in production **over HTTPS**. In development and staging, which are over HTTP, the issue does not occur.

With Rails 3.2. and **turbolinks** we had no issues.

----

refile 0.5.3
turbolinks 2.5.3
rails 4.1.10
jquery-rails 3.1.2

**Comment by janko-m** [comment]
Are you using `remote: true` in your forms? That is, are you using jQuery UJS?

**Comment by fiedl** [comment]
@janko-m : I don't think I'm using `remote: true`.

This is in my view:

```haml
- # app/views/users/_avatar.html.haml
= form_for @user do |form|
  = form.attachment_field :avatar, direct: true, class: auto_trigger_class
```

https://github.com/fiedl/your_platform/blob/master/app/views/users/_avatar.html.haml

And via javascript:

```coffee
# app/assets/javascripts/your_platform/user_avatars.js.coffee
$(document).on 'upload:complete', 'form.edit_user', ->
  $(this).submit()
```

https://github.com/fiedl/your_platform/blob/master/app/assets/javascripts/your_platform/user_avatars.js.coffee

**Comment by fiedl** [comment]
I've just confirmed that this is still an issue with Rails 4.2.

The view, which looks like this,

```haml
- # app/views/users/_avatar.html.haml
= form_for @user do |form|
  = form.attachment_field :avatar, direct: true, class: auto_trigger_class
```

generates this html form, which does include the authenticity_token.

```html
<form class="edit_user" id="edit_user_2" enctype="multipart/form-data" action="/users/2" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="zqvfFHPnkeP+PDZEK25KM47ydMBMRS5BKv2tL2czI8wfd64wOru9Td+QYoEDvgbVgSLYx4/0UTrN66qR0s1FNg==">
  <input value="null" type="hidden" name="user[avatar]">
  <input direct="true" class="auto_trigger" data-direct="true" data-as="file" data-url="https://example.org/refile/cache" accept="image/jpeg,image/gif,image/png" type="file" name="user[avatar]" id="user_avatar">
</form>

The form is submitted using javascript:

```coffee
# app/assets/javascripts/your_platform/user_avatars.js.coffee
$(document).on 'upload:complete', 'form.edit_user', ->
  $(this).submit()
```

The request headers include the authenticity token:

```
Content-Disposition: form-data; name="authenticity_token"

trERSz6Kwg5um0QLObezjmBquGR25pwm+ClJ9nXVHStnbWBvd9buoE83EM4RZ/9ob7oUY7VX410fP05IwCt70Q==
```

**Comment by jnicklas** [comment]
@fiedl can you track down *why* this is happening? I can't repro it at all, so I really can't help with solving it.

**Comment by janko-m** [comment]
@fiedl I assume you're still using Turbolinks. I have experienced `Can't verify CSRF token authenticity` errors a lot with Turbolinks. Can you try without it?

**Comment by fiedl** [comment]
@janko-m If it would help to track the problem down, I could temporarily deactivate turbolinks. But, in general, I would like to continue using turbolinks. Turbolinks did work for me fine with refile in Rails 3.2.

**Comment by jnicklas** [comment]
@fiedl since we can't repro this, we really need your help in tracking down the source of the issue.

If you want to get this issue resolved, you'll need to do one of two things:

1. Provide us with an executable reproduction of the problem. Start off with a fresh Rails app and figure out how to make this issue appear and upload it to github.
2. Track down what is causing this issue. It could be Refile, but it could also well be some other piece of the puzzle.

If you want to continue using Turbolinks that's fine, but @janko-m is trying to guide you in doing option (2), isolating the cause. If we could be certain that the problem was in the interaction between Turbolinks and Refile then that'd be useful, and a step in the right direction.

**Comment by hiasinho** [comment]
I just faced the same problem with a remote form. Got it fixed by adding `authenticity_token: true` to the form tag.

Found the solution here: https://github.com/rails/jquery-ujs/issues/331#issuecomment-20071744

**Comment by jnicklas** [comment]
I'm closing this issue, as I don't think that Refile is doing anything wrong. Rails should not be removing the authenticity token from forms if they might not be submitted via AJAX. IMO the inference algorithm for this in Rails is wrong, and I can't really understand why it'd be there in the first place, why not always add the authenticity token? Anyway, whatever the reason, there isn't anything in Refile we can do about this, aside from maybe documenting the problem somehow. @hiasinho's workaround is elegant enough.

For everyone who is having this problem and is *not* using `remote: true`: I have done all I can without a reproduction or an analysis of the cause, there is no sense in keeping this open if we have no idea why this bug happens, or if it's even Refile's fault.

**Comment by RealSilo** [comment]
@jnicklas @fiedl @Darmody Hey Guys! I know the issue is closed but I have a serious problem that is closely connected to this discussion. I've been trying to solve this problem for over 3 days, but I can't pull it off as I'm pretty new to rails. I guess it's not Refile's fault, but refile is involved as well. Could you take a look at it here: http://stackoverflow.com/questions/33652947/rails-file-uploading-via-ajax-with-refile-and-remotipart-private-pub-involved

**Comment by yoshihiko-ikenaga** [comment]
It seems that the route cause of this issue is the setting of sinatra base in Refile:App.
If I change the option of sinatra base, this error disappeared.

```
diff --git a/lib/refile/app.rb b/lib/refile/app.rb
index 87fd2b7..5fc5c65 100644
--- a/lib/refile/app.rb
+++ b/lib/refile/app.rb
@@ -18,7 +18,7 @@ module Refile
     configure do
       set :show_exceptions, false
       set :raise_errors, false
-      set :sessions, false
+      set :sessions, true
       set :logging, false
       set :dump_errors, false
       use CustomLogger, "Refile::App", proc { Refile.logger }
```
