### ISSUE TITLE
slow average response time

### ISSUE THREAD

**Issue by eddiefisher** [refile/refile#186]
I can't understand what is it:
```Sinatra: Refile::App/GET ([^/?#]+)/([^/?#]+)/([^/?#]+)/(.*?)/([^/?#]+)/((?:[^\./?#%]|(?:%[^2].|%[2][^Ee]))+)(?:\.|%2[Ee])((?:[^/?#%]|(?:%[^2].|%[2][^Ee]))+)```
http://cl.ly/image/3U1n1T1D403r

**Comment by jnicklas** [comment]
Processing images and streaming files is slow. I don't know if that's supposed to be surprising?

**Comment by eddiefisher** [comment]
can I cached files after processing?

**Comment by niels-s** [comment]
@eddiefisher you could taken advantage of a CDN. The request URL for your images stays the same, so they are cached. There some explanation in the project readme file. 
I also setup my app that way using AWS Cloudfront, it works pretty good.
