### ISSUE TITLE
huw I can get url without model?

### ISSUE THREAD

**Issue by eddiefisher** [refile/refile#188]
like:
```
file = File.open("#{Rails.root}/image.jpg", 'rb')
Refile.attachment_ur(file)
```

**Comment by jnicklas** [comment]
@eddiefisher I don't know at all what you want to do from that code. Do you want to upload a file without going through the model? You need to actually upload the file first in order to do that.

**Comment by eddiefisher** [comment]
yes, without model, but ```Refile.attachment_url``` need 2 params
```
file = File.open("#{Rails.root}/image.jpg", 'rb')
Refile.attachment_url Refile.cache.upload(file)
```

**Comment by janko-m** [comment]
I have to admit that it does make sense that this should be possible, from code design's perspective.

**Comment by jnicklas** [comment]
Me too :)
