### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by JoshuaNovak919** [refile/refile#189]
Is there a way to setup refile to support drag and drop now or will there be in the future?

**Comment by janko-m** [comment]
Aha, you mean like jQuery File Upload? Yeah, that would definitely be a nice feature. Although it seems to me that there should be a JS library which populates the file field on drag-n-drop, and then Refile would take over from there. Is there such a thing?

**Comment by JoshuaNovak919** [comment]
Yeah exactly. I've actually been looking for a JS library that does that, but haven't found one. Most of them do the uploading too. I'll see if I can find something or whip together some code to do it. I'm also looking into showing a preview for images before you upload them.

**Comment by janko-m** [comment]
Previews are easily done with JavaScript File API.

```js
$('input[type=file]').on("change", function() {
  if (this.files.length == 0) return;
  reader = new FileReader();
  reader.onload = function (e) { $("image").attr("src", e.target.result);  };
  reader.readAsDataURL(this.files[0]);
});
```

**Comment by JoshuaNovak919** [comment]
This looks promising: https://github.com/kartik-v/bootstrap-fileinput

**Comment by janko-m** [comment]
Great, I hope it works for you :)

**Comment by jcuenod** [comment]
Just for reference, I've had success with https://github.com/jaysalvat/ezdz

**Comment by chrise86** [comment]
Did anyone manage to implement [https://blueimp.github.io/jQuery-File-Upload/](jQuery-File-Upload)? Or the one @JoshuaNovak919 pointed out?
