### ISSUE TITLE
Get file in original format

### ISSUE THREAD

**Issue by JoshuaNovak919** [refile/refile#190]
I am using Refile to upload a PDF, but when I use attachment url it doesn't give me the .pdf extension:

`<%= link_to 'Download', attachment_url(@my_object, :brochure), target: '_blank' %>`

I don't want to specify the pdf format in `attachment_url`, because some users may upload other types of files. Is there a way to get the proper original format?

**Comment by janko-m** [comment]
Along with the file id, you can store [additional metadata](https://github.com/refile/refile#additional-metadata) about your files, including the filename (which contains the extension).

You just need to add the `:brochure_filename` string column, and it will be autofilled on upload. You could then add:

```rb
class MyModel < ActiveRecord::Base
  attachment :brochure

  def brochure_extension
    File.extname(brochure_filename) if brochure_filename
  end
end
```

**Comment by JoshuaNovak919** [comment]
Ok that works. I think it would make sense that if you add the `:brochure_filename` column that it would default to the extension in the original name.

**Comment by JoshuaNovak919** [comment]
Actually scratch that, it looks like it does. Yay!

**Comment by conwayanderson** [comment]
@janko-m I was able to use this solution locally but in production I'm using a CDN to deliver assets and this appears to not work in that scenario. Any thoughts on what is getting lost in translation?

**Comment by crhonox** [comment]
i have an issue with this, i'm uploading some pdf through an active job, 
`h = {
        remote_file_url: cert_url,
        contractor_id: contractor.id,
        file_filename: cert_url.split("/")[8],
        file_content_type: ".pdf"
      }
      Certification.create(h)`

i'm passing the file through a url and everything is fine, the problem is when i try to view the pdf, 
[https://imgur.com/jTpDIhx](url)
i'ts like the pdf is corrupted or something
