### ISSUE TITLE
Full attachment url

### ISSUE THREAD

**Issue by JoshuaNovak919** [refile/refile#191]
Is there a helper to get the full attachment url with the host etc?

IE: http://somedomain.com/attachments/store/soi3jjria3fkajwfaj983htg/somefile.pdf

**Comment by janko-m** [comment]
You can pass in `:host` to `attachment_url`:

```rb
attachment_url(@user, :avatar, host: request.url)
```

Since `request` doesn't have an method `#host_with_scheme`, you can pass a full URL, and internally Refile will replace the "path" part of the URL anyway. @jnicklas is it ok to rely on that behaviour?

**Comment by jnicklas** [comment]
Yes, that's an intentional feature. You're also encouraged to set `Refile.host`.

**Comment by jnicklas** [comment]
Oh, sorry, I read too fast. That's a neat way of solving this. I can't see us changing away from URI for this, so I doubt this will break, but there are no tests for it, so it's not an intended feature, sorry.

**Comment by thiagogsr** [comment]
@jnicklas I'm trying print my photos in pdf generated by prawn, but it requires a full address. `request` doesn't exist on this context. What is your suggestion for this case?

**Comment by thiagogsr** [comment]
Omg, it needs be the s3 url :/

**Comment by jnicklas** [comment]
@thiagogsr that doesn't really have anything to do with this issue. You can use `Refile.file_url` or `Refile.attachment_url` depending on which suits better. Check the docs.
