### ISSUE TITLE
Event for individual uploader

### ISSUE THREAD

**Issue by JoshuaNovak919** [refile/refile#195]
Is there a way to tap into the events for the attachment it's uploading? I have two attachments in the same form and the event is called for both. I want to have a progress bar etc for each attachment uploader.

**Comment by janko-m** [comment]
JavaScript events are always triggered on an HTML element. Refile triggers the uploading events on the file inputs, so you can do:

```js
$("input.attachment-one[type=file]").on("upload:complete", function() { ... })
$("input.attachment-two[type=file]").on("upload:complete", function() { ... })
```
