### ISSUE TITLE
ImageProcessor with s3

### ISSUE THREAD

**Issue by imgarylai** [refile/refile#196]
When I upload file to s3, the ImageProcessor API doesn't work.

I think that there are no file structure in s3 bucket?

http://jungllle.com/attachments/store/fill/600/600/e3d63c1a96be8a11832e6dc58a6a7b1035d7b3d8f2aed91d49d084b1655f/image.png

http://jungllle.com/attachments/store/e3d63c1a96be8a11832e6dc58a6a7b1035d7b3d8f2aed91d49d084b1655f/image.png

**Comment by nhattan** [comment]
Did you install ImageMagick on your sever?

**Comment by imgarylai** [comment]
Oops, I forgot to install this one. Thank for your helping.

**Comment by janko-m** [comment]
It would be great if we could somehow let `MiniMagick::Errors` propagate out of the `Refile::App`, so that in the main application it is raised as an error.
