### ISSUE TITLE
Remove hard dependency on Rails

### ISSUE THREAD

**Issue by joneslee85** [refile/refile#198]
Dear @jnicklas 

Firstly, thanks for this awesome gem, it makes life much easier for Rubyists out there.

Recently, I've looked into implementation of file upload with [lotusrb](https://github.com/lotus/lotus) and failed to get refile playing nicely because of the hard-dependency on Rails (i am thinking of extracting it into a seprate `refile-rails` gem). I would like to know if you are interested in a set of patches to remove this hard-dependency and adding support for Lotus.

Kind regards

**Comment by janko-m** [comment]
But Refile doesn't depend on Rails, we only depend on Sinatra and mime-types. But refile-lotus would be great :)

**Comment by joneslee85** [comment]
@janko-m as far as I concern, Gemfile has rails dependency as of https://github.com/refile/refile/blob/master/Gemfile#L15

**Comment by jnicklas** [comment]
@joneslee85 the Gemfile is not used when you install refile as a gem, it is used only for running Refile's own test suite. The file you're looking for is the gemspec file, which defines dependencies and other metadata. See: https://github.com/refile/refile/blob/master/refile.gemspec

I agree that lotus integration would be great, but it's something best left to an external gem. Though I'd be okay with adding it to the Refile organization if you want.
