### ISSUE TITLE
Clone images from one backend to another (e.g. using a production DB dump locally)

### ISSUE THREAD

**Issue by ayqazi** [refile/refile#199]
Hello,

I need to be able to use a dump of the production DB of my app locally. If I do this, all images break, because in production we use the S3 backend, and in development we use the file backend.

Is there an easy way I can loop through a bunch of models that have refile uploads, and copy them to the filesystem backend location that the development environment uses?

Thanks

**Comment by jnicklas** [comment]
Backends don't have a method which lists all files in them, but it should be fairly simple to do this using the AWS::S3 api. Just iterate through all objects in the bucket and upload them into your local backend.
