### ISSUE TITLE
Consider carrierwave-esque DSL for version naming

### ISSUE THREAD

**Issue by adamrubin** [refile/refile#204]
Currently, we can define (post-processed) image sizes process with:
```<%= image_tag attachment_url(@user, :profile_image, :fill, 300, 300, format: "jpg") %>```

I'm wary of littering my code with hard-coded image sizes like that, and prefer pre-defined named versions of each image. I can create a view helper to translate "small" into 50, 50 - but that won't work with my serializers and referencing those named versions on an iOS client.

Have you considered implementing something like carrerwave's Uploader module to handle defining named image sizes and processing instructions?

**Comment by jnicklas** [comment]
This is specifically something that Refile is *not* going to do. You can create a helper for this something like `thumbnail_image` for example, or whatever app-specific abstraction makes sense for you, but it is not something we will do inside the gem itself. You can also define a custom processor which makes `attachment_url` easier to invoke without having to provide all options.
