### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by JustMikey** [refile/refile#205]
I know it's not exactly the most appropriate place to ask this question but I wonder what security measures should be taken using this gem? Like if should I somehow check uploaded filenames and edit them if some evil symbols are used and things like that? Just a short list of things for consideration would do, even without explanations, I will google the rest. Thank you for your time.

**Comment by jnicklas** [comment]
@JustMikey one of the reasons refile does not let you modify the path and name of a stored file is to prevent someone from passing user input into it. Refile escapes the filename before generating URLs from it (https://github.com/refile/refile/blob/master/lib/refile.rb#L249), so you don't need to worry about the stored filenames.

We try to be secure by default, and you should not have to do anything special to build a secure system with Refile.
