### ISSUE TITLE
Migration to Refile

### ISSUE THREAD

**Issue by justguerra** [refile/refile#206]
I would like to create a task to migrate a model to Refile. 

So I  have a model, "User", that has a string attribute, "image_url" where we have the URL of a image of that user.

This model has also a refile attachment:
```ruby
class User < ActiveRecord::Base  extend Refile::Attachment
         attachment :profile_image
```
So I need a way to automatically upload and save this image without using forms.
I was thinking in something like that:

```ruby 
User.all.each do |user|
    File.open(user.image_url, "rb") do |file|
      user.profile_image = file
    end
    user.save
end
```

But for some reason File.open don't load "http://" requests. 
Any idea of how to solve this?

**Comment by walterdavis** [comment]
Require open-uri, then just call open in place of File.open. 

Walter

**Comment by janko-m** [comment]
You can do it as @walterdavis said, but Refile already supports assigning URLs:

```rb
User.find_each do |user|
    user.update!(remote_profile_image_url: user.image_url)
end
```
