### ISSUE TITLE
missing credentials error using AWS

### ISSUE THREAD

**Issue by kohl00** [refile/refile#215]
Missing Credentials.
2015-05-06T01:47:25.619025+00:00 app[web.1]: 
2015-05-06T01:47:25.619028+00:00 app[web.1]: AWS::Errors::MissingCredentialsError (
2015-05-06T01:47:25.619041+00:00 app[web.1]: 

In config/initializers/refile.rb

require "refile/backend/s3"
aws = {
  access_key_id: Rails.application.secrets.access_key_id,
  secret_access_key: Rails.application.secrets.secret_access_key,
  bucket: Rails.application.secrets.bucket
}
Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)

In secrets.yaml
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV["AWS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  bucket: <%= ENV["S3_BUCKET"] %>

**Comment by kohl00** [comment]
I set my production environment variables in heroku. The only thing I can think is that the secrets file is in .gitignore

**Comment by janko-m** [comment]
Yes, your credentials may be blank, you can `heroku run console` and check for `Rails.application.secrets.*` credentials if they're set. One other thing that may be causing the error is that you wrote `*aws` when passing the credentials instead of `**aws`.
