### ISSUE TITLE
Using Refile with hstore

### ISSUE THREAD

**Issue by ibnukamy** [refile/refile#216]
Hi there,

1. I'm trying to use `attachment_field` in a `hstore` field.
```ruby
<%= form_for @album, do |f| %>
  <%= f.text_field :title %>
  <%= f.fields_for :images, @album.images do |build| %>
    <%= build.attachment_field :img %>
......
```
`:images` is a hstore field inside the `:albums table`. How can I achieve this using refile? Because the `:img_attacher` depends on a model and not the field of the model? Any suggestion or advices are welcomed. Thank you in advance!

**Comment by jnicklas** [comment]
I think this will take some trickery to achieve, this use case is currently not supported at all by Refile. My best advice would be to introduce some kind of intermediate pure-ruby model, which represents an item in the HStore column. If you manage to make this work, please ping us back and let us know how! If you want something with more official support, take a look at #211.

**Comment by ibnukamy** [comment]
Thanks @jnicklas for your suggestion! I'll try to do the intermediary model approach. Thank you for the `refile gem` it's awsome :+1:

**Comment by jnicklas** [comment]
:) thank you!
