### ISSUE TITLE
Using CloudFront doesn't show in monitoring reports

### ISSUE THREAD

**Issue by IanJBriggs** [refile/refile#217]
I have set up Refile to use CloudFront using:

Refile.host = "//cdn.example.com"

Rails also uses this CDN URL to serve static assets successfully. I am able to see the assets start populating on the popular objects table in Amazons CloudFront service area.

However I dont see any objects from the Refile store. None. Upload is fine. I look at the URL in production on some images and it looks like:

/attachments/store/[GUID]/avatar

This is because its mounted to /attachments which I understand, but because its now using the CDN as a host should this not change? 

Why am I not seeing any images recored by CloudFront??

Ian

**Comment by jnicklas** [comment]
Seems like the URL is not fully qualified. My guess would be that `Refile.host` is not getting set for some reason. Double check that you're setting it to the right value.

**Comment by jnicklas** [comment]
Try opening a console in production and check `Refile.host`.

**Comment by IanJBriggs** [comment]
Thanks for your reply. 

Console in production:

irb(main):002:0> Refile.host
=> "//cdn.[URL].com"

**Comment by IanJBriggs** [comment]
So in knowing this. Should the GET request stil be:

`Started GET "/attachments/store/fill/120/120/[GUID]/avatar"`

Which then acts as a proxy to the CDN OR

`Started GET "//cdn.[URL].com/attachments/store/fill/120/120/[GUID]/avatar"`

Which Refile asks for the attachment directly from the CDN? Whats the intended behavior?

**Comment by jnicklas** [comment]
No, the CDN should be in front of the app, not the other way around. The URL generated by Refile should be a fully qualified URL to the CDN. If it's not, then something is going wrong, I have no idea what is, so you'll have to dig a bit.

**Comment by jnicklas** [comment]
I'm not sure how to further assist you on this issue. Did you get everything resolved? Can I close this?
