### ISSUE TITLE
progress for multiple files ?

### ISSUE THREAD

**Issue by grosser** [refile/refile#221]
atm I get a bunch of events back and don't know which file they belong to,
so a summery even would be great or adding some kind of meta information so I know if this is fine 1 or file 2

@jnicklas

**Comment by grosser** [comment]
currently using this evil code to keep the progress from flickering around

```
  var detail = e.originalEvent.detail;
  var percentage = Math.round((detail.loaded / detail.total) * 100);
  var current_total = $bar[0].total;
  if(current_total && current_total != detail.total) { return }; // wrong file
  $bar.text(percentage + "% of " + humanFileSize(detail.total));
  if(current_total == detail.position) { // 100% -> make room for the next
    $bar[0].total = null;
  } else {
    $bar[0].total = detail.total;
  }
```

**Comment by jnicklas** [comment]
I meant to fix this but I... forgot.

**Comment by jnicklas** [comment]
You should now have the file instance as well as the index of the file in the event detail.

**Comment by chrise86** [comment]
I'm still having to use something like @grosser, `e.detail.progress.loaded` is not working for me (with `multiple: true, direct: true`)
