### ISSUE TITLE
Error on newest master branch

### ISSUE THREAD

**Issue by rememberlenny** [refile/refile#222]
Error:
`SyntaxError: /Users/lkbgift/.rvm/gems/ruby-2.0.0-p247/bundler/gems/refile-3356053a5603/lib/refile/signature.rb:19: syntax error, unexpected ','
    def initialize(as:, id:, url:, fields:)`

**Comment by jnicklas** [comment]
Refile requires Ruby 2.2.

**Comment by rememberlenny** [comment]
@jnicklas Thanks again

**Comment by rememberlenny** [comment]
Everything is working now
