### ISSUE TITLE
Issues with remote files and local cache + s3 backend

### ISSUE THREAD

**Issue by mskog** [refile/refile#224]
Refile Versions
```
Using refile 0.5.4 from https://github.com/refile/refile (at v0.5.4)
Using refile-s3 0.0.1 from https://github.com/refile/refile-s3 (at master)
```

Using the Filesystem backend for cache/store works fine for all examples below.

Using the S3 based backend directly to upload a file works, so it does not appear to be an issue with the AWS credentials or anything.

When I use a FileSystem backend for the Cache and an S3 bucket for the Store I get the following error when uploading through a remote url 

```ruby 
pry(main)> MyModel.create remote_file_url: 'http://i.imgur.com/dlgbOCB.png'
ArgumentError: expected params[:body] to be a string or IO object
from /Users/mrcheese/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/param_validator.rb:24:in validate!
```

From file:

```ruby
[1] pry(main)> MyModel.create file: StringIO.new('sdfsdfdsf')
ArgumentError: expected params[:body] to be a string or IO object
from /Users/mrcheese/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/param_validator.rb:24:in `validate!'
```

When I instead use S3 for both cache and store the upload with a file/StringIO works but when using a remote url I get:

```ruby
[2] pry(main)> MyModel.create remote_file_url: 'http://i.imgur.com/dlgbOCB.png'
IOError: closed stream
from /Users/mrcheese/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/plugins/s3_md5s.rb:38:in `md5'
```

**Comment by jnicklas** [comment]
@mskog I was able to replicate the issue, and pushed a fix which seems to have fixed it for all cases I've tried. Can you give it a go now and see if it works better for you?

**Comment by mskog** [comment]
Works like a charm. Thank you!

**Comment by callmeed** [comment]
I'm getting the same `expected params[:body] to be a string or IO object` error with refile 0.5.5 and refile-s3 0.1.0.

**Comment by aaronmiler** [comment]
I am also experiencing this using `refile 0.5.5` and `refile-s3 0.1.0`

**Comment by jasdeepsingh** [comment]
Facing the same issue: `IOError: closed stream`
With: 

```
refile (0.5.5)
refile-s3 (0.1.0)
```

**Comment by jasdeepsingh** [comment]
I can verify, using the master branch on github fixes the issue. Thanks!
