### ISSUE TITLE
Placing the watermark on refile

### ISSUE THREAD

**Issue by asiniy** [refile/refile#231]
Is there any `before_process` or another hook where I can place a watermark on my image?

**Comment by jnicklas** [comment]
You will have to create your own processor in order to do this. It shouldn't be too hard. Take a look at the [MiniMagick processor](https://github.com/refile/refile-mini_magick/blob/master/lib/refile/mini_magick.rb) to see how it's done.

**Comment by asiniy** [comment]
ok, thx!

**Comment by zyphlar** [comment]
For posterity, this is how I did it:

https://gist.github.com/zyphlar/4b2a86aca41cb7d1280d

**Comment by samsoft00** [comment]
The title say it all, i want my website logo to be on every Refile Image, please how can that be achieve and also positioning? Thanks
