### ISSUE TITLE
metadataField not updated after validation error

### ISSUE THREAD

**Issue by trentclowater** [refile/refile#233]
When using background uploads (with direct: true), if you require an image using

    validates :image, presence: true

and try to create a new object without specifying a file, the file input will be wrapped with

    <div class="field_with_errors">
        <input direct="true"  data-direct="true" data-as="file" ... >
    </div>

This breaks the ability to add an image after the validation error has occurred, because this line:

    var metadataField = input.previousSibling;

can no longer find the hidden input that holds the file metadata. The hidden input is now a sibling of the parent field_with_errors div, not the file input itself.

**Comment by jnicklas** [comment]
That's pretty bad, can't believe no one has noticed this until now.

**Comment by trentclowater** [comment]
Not sure why nobody noticed it before either. Thanks for the quick fix.

Although I would suggest though that the data attribute be named something like `data-input-id`, `data-associated-input` or `data-associated-field` rather than `data-num`. When looking at the generated HTML, `data-num` wouldn't really give me a clue about what it is used for, while the others would immediately give me a reasonable idea what it is for without having to search through the source.

**Comment by jnicklas** [comment]
@trentclowater yeah, I didn't like the name either. I changed it to `data-reference` not sure if that's better.

**Comment by trentclowater** [comment]
@jnicklas  `data-reference` sounds okay to me. Much better than `data-num` at least. Should be fairly clear that it is a reference to the input that the metadata comes from.
