### ISSUE TITLE
After images are replaced, old URL's stop working

### ISSUE THREAD

**Issue by sindrenm** [refile/refile#235]
I've set up Refile, pointing towards CloudFront. If CloudFront can't find the file in their cache, they'll ask for it from our application, which will fetch it form S3 and process through Refile before it gives it back to CloudFront. Pretty much the basic setup with a CDN, I suppose. This works great for first-time image uploads.

However, since the images are given a (random?) hash generated by Refile when they're uploaded, if an image is replaced with another one, that ID hash is also regenerated and replaced, causing the old URLs to fail. On our setup with CloudFront and S3, this ends up raising an `AWS::S3::Errors::Forbidden` error in our application. Of course, this happens because the URL changes when images are replaced. And since the image is replaced, the old images are removed. Usually, this isn't a problem, but when the image's URL is cached somewhere (say it's been scraped and shared on Facebook or something), then it becomes problematic.

Sooo, is it any way to ensure that the URL doesn't change when files are replaced? Keeping the hash is fine if it remains the same on new files, but there might be a reason this isn't the case?

Thanks.

**Comment by sindrenm** [comment]
It probably isn't, but it might be related to #226, or rather; this might be what he is experiencing. But probably not.

**Comment by jnicklas** [comment]
If you need a canonical URL to files, you'd be best served with setting up your own controller action which streams files to the client (using `send_file` in Rails for example).

**Comment by sindrenm** [comment]
Good idea, @jnicklas, thanks for that. I'm a little bit sceptical about streaming the assets from Rails with `send_file`, but perhaps doing a **307 Temporary Redirect** and point to the path that Refile generates is a better approach. What do you think about that?

**Comment by jnicklas** [comment]
@sindrenm that only solves the problem partially. If someone hands someone else the link to the file, or shares it on Facebook, or whatever, it won't work. Why are you sceptical about streaming the file from Rails? That's essentially what Refile ends up doing anyway.
