### ISSUE TITLE
Paperclip and Image Processing style

### ISSUE THREAD

**Issue by fabiode** [refile/refile#237]
Hello, folks!

I'm familiar with Paperclip, but I'm thinking about to move all my projects to Refile, it appear to have such a solid behavior and the direct upload is a real problem solver.

I have two questions:

1) Anyone had this experience in migrating from Paperclip to Refile?

2) I'm missing in README, and even after reading the code, how to process images in different styles (like thumbnail, medium, big, etc.). Paperclip has the style option in hash. Is there any method to do this?

Thank all you guys for this amazing solution and keep the good work!

**Comment by kevinansfield** [comment]
Hi fabiode!

With Refile there is no need to specify your image sizes up-front as processed files are generated on the fly (make sure you set up a CDN!) based on the required dimensions etc.

Check out the section on [rails helpers](https://github.com/refile/refile#4-rails-helpers) for how you would request a particular image size.

**Comment by fabiode** [comment]
@kevinansfield I thought for one sec it could be something like this, but it was to futuristic for me! Hehe!

Thank you so much!

**Comment by alexbatista** [comment]
Hi, fabiode do you found the solution about the migration from paperclip to refile? I am found a solution for this.
