### ISSUE TITLE
mass upload replace photos

### ISSUE THREAD

**Issue by artempartos** [refile/refile#239]
I use refile mass upload, and when I update attributes, all old files replaces by new. But i want to have a possibility to append and remove images. If it possible to configure this behavior?

**Comment by artempartos** [comment]
Oh, I find append option in source. Is is really need update doc

**Comment by jnicklas** [comment]
It is documented. See https://github.com/refile/refile/blob/master/lib/refile/attachment/active_record.rb#L65
