### ISSUE TITLE
Image does not update for nested model

### ISSUE THREAD

**Issue by munshi** [refile/refile#241]
Hi, 
I am facing an error when updating an image in a nested model. Managed to repeat it for 2 use cases and still faced the same thing so I suspect it's a bug. 

I have:
User Model
- has_one :profile
- accepts nested attributes for Profile Model

Profile Model
- belongs_to :user
- attachment :profile_image

When I update the user information including the profile image, the profile image will only update if another field is changed as well. Meaning, if only the profile image field is changed, the image will not be updated. 

Tried again with Post that has one Image as nested attributes and faced the same issue. 

Rails 4.2.1, Ruby 2.2.2, Refile 0.5.4, Devise 3.4.1

**Comment by munshi** [comment]
Only change image field:

Started PATCH "/posts/4" for ::1 at 2015-05-25 19:04:08 +0800
Processing by PostsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"blah blah blah", "post"=>{"content_attributes"=>{"source"=>"Image", "image"=>#<ActionDispatch::Http::UploadedFile:0x007fb6c4a1a590 @tempfile=#<Tempfile:/var/folders/yz/q39n__m956q1_x98xk1_z0lh0000gn/T/RackMultipart20150525-34120-1xzwmmn.jpg>, @original_filename="1947899_850745788315967_6010265284945801616_n.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"post[content_attributes][image]\"; filename=\"1947899_850745788315967_6010265284945801616_n.jpg\"\r\nContent-Type: image/jpeg\r\n">, "id"=>"4"}, "category_id"=>"1", "description"=>"User 2 post", "tag_list"=>"tag", "tool_list"=>""}, "commit"=>"Update Post", "id"=>"4"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 3]]
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT 1  [["id", 4]]
   (0.1ms)  BEGIN
  Content Load (0.3ms)  SELECT  "contents".* FROM "contents" WHERE "contents"."post_id" = $1 LIMIT 1  [["post_id", 4]]
Redirected to http://localhost:3000/posts/4
Completed 302 Found in 22ms (ActiveRecord: 2.0ms)

**Comment by munshi** [comment]
When only profile_image attachment changed, upload fails:

Started PATCH "/users/3" for ::1 at 2015-05-25 19:13:07 +0800
Processing by UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"foo", "user"=>{"username"=>"seeduser_1", "profile_attributes"=>{"name"=>"Seed User", "bio"=>"", "profile_image"=>#<ActionDispatch::Http::UploadedFile:0x007fb6c722a0d0 @tempfile=#<Tempfile:/var/folders/yz/q39n__m956q1_x98xk1_z0lh0000gn/T/RackMultipart20150525-34120-17zqd9i.jpg>, @original_filename="10945023_850346015022611_224790108829327563_n.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_attributes][profile_image]\"; filename=\"10945023_850346015022611_224790108829327563_n.jpg\"\r\nContent-Type: image/jpeg\r\n">, "id"=>"7"}}, "commit"=>"Update User", "id"=>"3"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 3]]
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 3]]
   (0.2ms)  BEGIN
  Profile Load (0.2ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT 1  [["user_id", 3]]
  User Exists (0.4ms)  SELECT  1 AS one FROM "users" WHERE (LOWER("users"."username") = LOWER('seeduser_1') AND "users"."id" != 3) LIMIT 1
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE (LOWER("users"."email") = LOWER('user_1@seeds.com') AND "users"."id" != 3) LIMIT 1
   (0.1ms)  COMMIT
Redirected to http://localhost:3000/users/3/edit
Completed 302 Found in 13ms (ActiveRecord: 1.9ms)

**Comment by munshi** [comment]
When profile_image attachment and name field changed, update works:

Started PATCH "/users/3" for ::1 at 2015-05-25 19:15:23 +0800
Processing by UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"foo", "user"=>{"username"=>"seeduser_1", "profile_attributes"=>{"name"=>"Seed User (Changed)", "bio"=>"", "profile_image"=>#<ActionDispatch::Http::UploadedFile:0x007fb6c1963208 @tempfile=#<Tempfile:/var/folders/yz/q39n__m956q1_x98xk1_z0lh0000gn/T/RackMultipart20150525-34120-1op2614.jpg>, @original_filename="10712687_846810508709495_1052667840485239805_o.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_attributes][profile_image]\"; filename=\"10712687_846810508709495_1052667840485239805_o.jpg\"\r\nContent-Type: image/jpeg\r\n">, "id"=>"7"}}, "commit"=>"Update User", "id"=>"3"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 3]]
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 3]]
   (0.1ms)  BEGIN
  Profile Load (0.2ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT 1  [["user_id", 3]]
  User Exists (0.4ms)  SELECT  1 AS one FROM "users" WHERE (LOWER("users"."username") = LOWER('seeduser_1') AND "users"."id" != 3) LIMIT 1
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE (LOWER("users"."email") = LOWER('user_1@seeds.com') AND "users"."id" != 3) LIMIT 1
  SQL (0.3ms)  UPDATE "profiles" SET "name" = $1, "profile_image_id" = $2, "updated_at" = $3 WHERE "profiles"."id" = $4  [["name", "Seed User (Changed)"], ["profile_image_id", "a1f0301bc0de5b7aafa5e6f410e950343641c72a67612d71e7c66517da21"], ["updated_at", "2015-05-25 11:15:23.555835"], ["id", 7]]
   (5.1ms)  COMMIT
Redirected to http://localhost:3000/users/3/edit
Completed 302 Found in 39ms (ActiveRecord: 6.9ms)

**Comment by jnicklas** [comment]
This bug is fixed in master. See #142.

**Comment by munshi** [comment]
Sorry missed that. Thanks Jonas.
