### ISSUE TITLE
Filename bug

### ISSUE THREAD

**Issue by dhyegofernando** [refile/refile#243]
## Bug
Let's say that I'm trying to set a remote image url just like that:

```ruby
img_url = 'https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xaf1/v/t1.0-1/c0.0.500.500/23374_418505028243167_332794789_n.jpg?oh=6f0bfa642b1df49be2e10a94c9f8e42f&oe=55C6FEBD&__gda__=1438631152_d23b934d42f0f646f1b79b67b6868cb2'

u = User.last
u.remote_avatar_image_url = img_url

u.avatar_image_filename # 23374_418505028243167_332794789_n.jpg?oh=6f0bfa642b1df49be2e10a94c9f8e42f&oe=55C6FEBD&__gda__=1438631152_d23b934d42f0f646f1
```

(pay attention to the filename which has query parameters)

So than when I try to get ```User#avatar_image_url``` the following error is raised:

```ruby
# ...
u.avatar_image_url # URI::InvalidComponentError: bad component(expected relative path component): /attachments/1d3f569f1df57f133e7f5fd9b93c39557d34bdb1/store/476edde5e39bdb3992dcbe2d5ed91e377a03e6286d93589a2c0e8854a0c5/23374_418505028243167_332794789_n.jpg?oh=6f0bfa642b1df49be2e10a94c9f8e42f&oe=55C6FEBD&__gda__=1438631152_d23b934d42f0f646f1b79b67b6868cb2
```

## Solution
So after few tests I figured out that filenames can not have query parameters or special characters when use File.join in this [line](https://github.com/refile/refile/blob/56911b0d8d59a77a34d462880f0924a24a73377a/lib/refile.rb#L250).

If I set the filename in a simpler way I get a successful result:

```ruby
# ...
u.avatar_image_filename = 'abc.jpg'
u.avatar_image_url # /attachments/26a1ef21c3d6e7de93744acf2e8455948b37959b/store/aaaffe2fc3a2655e5cb14f4d609f38c88754031b435789912451297262a2/abc.jpg
```

That's a bug, isn't that?

**Comment by jnicklas** [comment]
Yes this is not expected. The filename *should* be escaped, which means it won't be super pretty, but ti should work. But even earlier than that we should strip off the query string from the URL.

**Comment by jnicklas** [comment]
Just pushed a fix for this, can you give it a try and see if it helps?

**Comment by dhyegofernando** [comment]
Yeah, totally working! Nice. Thanks.
