### ISSUE TITLE
Graceful uploading error handling

### ISSUE THREAD

**Issue by toothfairy** [refile/refile#244]
For now application [doesn't](https://github.com/refile/refile/blob/master/lib/refile/app.rb#L64) handle backend fail cases and just responds with 500 error code, which is not convenient. So maybe it would be nice to handle those exceptions in app and return 413 in case of size validation, or 400 when ArgumentError is thrown. It'd improve semantics and probably help handling errors on frontend.

**Comment by jnicklas** [comment]
Better error status codes would be nice, I agree. I'd love a PR for this.
