### ISSUE TITLE
how I can set token?

### ISSUE THREAD

**Issue by eddiefisher** [refile/refile#246]
GET /attachments/:token/:backend_name/:id/:filename

**Comment by jnicklas** [comment]
You'll need to generate it based on the rest of the URL. See https://github.com/refile/refile/blob/master/lib/refile.rb#L296-L316

**Comment by ibnukamy** [comment]
Hi @jnicklas, I'm serving my image url using json and how do I pass the token through json? I'm not using `attachment_url` or `attachment_image_tag`. Before the `:token` it was working fine just by using the id.

Another question is, is it possible for me to generate the token without using the view helper method? Thank you.

**Comment by ibnukamy** [comment]
I figured it out using `Refile.file_url`. Reading the source code at the above link was really helpful. Thanks.
