### ISSUE TITLE
Creating/Updating a resource fails to include :resource_image param

### ISSUE THREAD

**Issue by kohl00** [refile/refile#248]
I can't figure out why the controller isn't grabbing car_params from the params hash and updating the car_image attribute on the new object. Any help would be great.

  Processing by CarsController#create as 
   
     HTML Parameters: {
    "utf8"=>"✓",
    "authenticity_token"=>"vjY9yM9L3+fDF++NFHipHeHDU11j3VH20LCA5OHGhXuJF56NnKoBa0tdhX5vhGaTmsePco0mW+NNSWg1lrfhUg==",
     "car"=>{"price"=>"100000", "make"=>"Mercedes Benz", 
    "kind"=>"CL-Class", "year"=>"2014", "description"=>"New!",
    "car_image"=>#    <ActionDispatch::Http::UploadedFile:0x00000106d59650 @tempfile=#   <Tempfile:/var/folders/j_/mv_y6ggx7jq89p_0ywym78p40000gn/T/RackMultipart20150527-46234-nrxhki.jpeg>, @original_filename="mercedez-benz.jpeg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"car[car_image]\"; filename=\"mercedez-benz.jpeg\"\r\nContent-Type: image/jpeg\r\n">},
     "commit"=>"Create Car"}

      User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY     "users"."id" ASC LIMIT 1  [["id", 1]]
       (0.2ms)  begin transaction
      SQL (0.5ms)  INSERT INTO "cars" ("price", "make", "kind", "year", "description", "user_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["price", 100000], ["make", "Mercedes Benz"], ["kind", "CL-Class"], ["year", 2014], ["description", "New!"], ["user_id", 1], ["created_at", "2015-05-27 15:34:16.872110"], ["updated_at", "2015-05-27 15:34:16.872110"]]
       (19.3ms)  commit transaction

Car.rb

    class Car < ActiveRecord::Base
	  belongs_to :user
	  has_one :charge
	  attachment :car_image
 	  scope :sort_by_make, -> (make) { where('make = ?', make) }
 	  scope :sort_by_kind, -> (kind) { where('kind = ?', kind) }
 	  scope :sort_by_year, -> (year) { where('year = ?', year) }
 	  scope :availabe_for_purchase, -> { where('arrived IS NULL OR arrived = (?)', false) }
         validates :price,       presence: true, numericality: { only_integer: true}
         validates :make,        presence: true
         validates :kind,        presence: true
         validates :description, presence: true
         validates :year,        presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1950, less_than_or_equal_to: Time.now.year }
         validates :car_image,   presence: true
    end

Also added :car_image to car_params in the controller.

**Comment by jnicklas** [comment]
You really need to post your controller code.

**Comment by kohl00** [comment]
Thanks @jnicklas . Below the controller that handles the creating/updating the resource in question.

     class CarsController < ApplicationController
      before_action :set_car, only: [:show, :edit, :update, :destroy]

        def new
          @car = Car.new
        end

        def edit
        end

 
      def create
        @car = current_user.cars.new(car_params)

        respond_to do |format|
          if @car.save
            format.html { redirect_to @car, notice: 'Car was successfully created.' }
            format.json { render :show, status: :created, location: @car }
          else
            format.html { render :new }
            format.json { render json: @car.errors, status: :unprocessable_entity }
         end
       end
      end

  
      def update
        respond_to do |format|
          if @car.update(car_params)
            format.html { redirect_to @car, notice: 'Car was successfully updated.' }
            format.json { render :show, status: :ok, location: @car }
          else
            format.html { render :edit }
            format.json { render json: @car.errors, status: :unprocessable_entity }
         end
       end
     end

      private

        def set_car
          @car = Car.find(params[:id])
        end

        def car_params
           params.require(:car).permit(:price, :make, :user_id, :car_image, :arrived, :kind, :year, :description)
        end
    end

**Comment by jnicklas** [comment]
That looks good. Have you looked at what `car_params` is inside your controller?

**Comment by kohl00** [comment]
I'm not sure what you mean? car_params is inside of the controller?

**Comment by jnicklas** [comment]
Yes, I meant to check what it's actual value is inside the controller. Is `car_image` set properly?

**Comment by kohl00** [comment]
This is taken from my original post above, taken from the params hash:      

    "car_image"=>#    <ActionDispatch::Http::UploadedFile:0x00000106d59650 @tempfile=#   <Tempfile:/var/folders/j_/mv_y6ggx7jq89p_0ywym78p40000gn/T/RackMultipart20150527-46234-nrxhki.jpeg>, @original_filename="mercedez-benz.jpeg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"car[car_image]\"; filename=\"mercedez-benz.jpeg\"\r\nContent-Type: image/jpeg\r\n">}

This is a snippet from the form partial:

     <div class="field form-group">
        <%= f.label :car_image %><br>
        <%= f.attachment_field :car_image, class: "form-control" %>
      </div>

**Comment by jnicklas** [comment]
Yeah, I saw that. Check it anyway. Checking is superior to reasoning about what something is supposed to be. Once you've checked the controller and checked that every value is what it's supposed to be, dig deeper until you find where the value is not what you expect it to be.

**Comment by kohl00** [comment]
I think I might have figured it out. I had :car_image as the column name instead of :car_image_id . I'll let you know if that was the issue. Thanks for the help @jnicklas

**Comment by jnicklas** [comment]
@kohl00 we just pushed a change which makes that throw an error, since it's tripped a few people up already. Will be in the next version.

**Comment by kohl00** [comment]
That was the issue
