### ISSUE TITLE
Unable to remove uploaded file as nested attribute

### ISSUE THREAD

**Issue by dhyegofernando** [refile/refile#250]
## Context
Let's suppose that I have the following two models:

```ruby
class User < ActiveRecord::Base
  has_one :profile, as: :profileable

  # Remember: this macro auto apply the autosave option to true in this `profile` relation
  accepts_nested_attributes_for :profile
end

class Profile < ActiveRecord::Base
  belongs_to :profileable, polymorphic: true
  attachment :avatar_image, type: :image
end
```
So I can create or update my nested profile through a user just like that:

```ruby
attributes = {
  name: 'John Doe',
  avatar_attributes: {
    remote_avatar_image_url: 'http://...'
  }
}

u = User.new attributes
u.save # true

u.profile.avatar_image # #<Refile::File:0x007fe28bfa31b8...
```

That is what is expected to be.

## Problem
Thinking the same way as above we'd be able to remove the image too, right? Just like that:

```ruby
# ...
u.profile.remove_avatar_image = true
u.save # true

u.profile.avatar_image # #<Refile::File:0x007fe28bfa31b8...
```

and than it doesn't work. To get it work we have to save manually the relation:

```ruby
# ...
u.profile.save

u.profile.avatar_image # nil
```

----------------------------------------------------

Is it what we should expect to be? Thanks.

**Comment by jnicklas** [comment]
This is probably related to #142. My guess is that the fix is similar. The callback won't be called unless a change was made, so we'll have to call `will_change!`.

**Comment by dhyegofernando** [comment]
Absolutely that's the same issue. My bad for duplicate it. You can close this one and keep opened the original one.

**Comment by jnicklas** [comment]
I think it's not exactly the same, just similar. I just linked to #142 because I think we need to solve this the same way.

**Comment by dhyegofernando** [comment]
Calling ```send("#{name}_id_will_change!")``` after this [line](https://github.com/refile/refile/blob/master/lib/refile/attachment.rb#L75) should resolve it, shouldn't it?

**Comment by jnicklas** [comment]
@dhyegofernando almost. It should have been in the AR specific code. I've just pushed a fix, can you try it out and see if it works?

**Comment by dhyegofernando** [comment]
@jnicklas It worked nicely. Thanks.

**Comment by alexandremcosta** [comment]
Any estimate of when this will be stable?
