### ISSUE TITLE
The upload:complete event returns 1 for one or more uploads

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#255]
The following seems to always be logging `1` regardless of the number of uploads. This means we can't listen to the complete event to enable disabled buttons.

```javascript
$(document).on('upload:complete', 'form', function(e) {
  console.log( $(this).find('input.uploading').length );
});
```

I'm using the latest Chrome on OSX Yosemite, and the master branch of Refile.

**Comment by jnicklas** [comment]
Are you running from the master branch? I think this might be a regression which appeared when we added the multiple file upload.

**Comment by jnicklas** [comment]
Just pushed a fix for this, can you give it a look and see how it goes?

**Comment by abitdodgy** [comment]
I can confirm that this works. I actually made the same fix as you did and got it working. I should have made a pull request, I guess. Thanks!
