### ISSUE TITLE
Nginx + Pasenger url auto escape causes token validation error

### ISSUE THREAD

**Issue by tonilin** [refile/refile#256]
The file name is `test@3x.jpg`

It's worked when run on development: 

```
Refile::App: [2015-06-01 19:14:21 +0800] GET "/574866afc423ab5c49a5e92b448ffd2adab7aa0b/store/fill/320/160/0f4a162a236026c6c5cc2dc1d559067c8c94a3c4c530d7d6542d99987b5d/test%403x.jpg" 200 163.5ms
```

But on production, nginx + passenger auto decode the url, it causes validation error:

```
Refile::App: [2015-06-01 19:14:21 +0800] GET "/574866afc423ab5c49a5e92b448ffd2adab7aa0b/store/fill/320/160/0f4a162a236026c6c5cc2dc1d559067c8c94a3c4c530d7d6542d99987b5d/test@3x.jpg" 200 163.5ms
```

Is it a refile bug or a nginx+passenger bug?

**Comment by jnicklas** [comment]
Well that's pretty annoying. Why would they do that? Is this a configuration setting or default behaviour? If it's the default we might have to come up with some other way of escaping filenames other than URI escaping them.

**Comment by tonilin** [comment]
There's no addition settings on the nginx + passenger server. Just the basic settings.
I think it's the default behavior.

**Comment by wlads** [comment]
Found one answer from Igor Sysoev [here](https://www.ruby-forum.com/topic/177005) - although I have not tested

**Comment by jnicklas** [comment]
Seems like this is fixable by setting the right nginx config.
