### ISSUE TITLE
Is there a way to rename files that are being uploaded directly to S3?

### ISSUE THREAD

**Issue by chrisyeung1121** [refile/refile#257]
I searched through file upload solutions and have adopted a few. None really work well. So it's really great to see this effort. I wonder if I can find any options to rename files using refile helpers ? Or will it be in the roadmap?

**Comment by jnicklas** [comment]
The idea is that you should not care what your files are called on S3. We have no plans to add any way to rename the files on S3 is any way. Refile is built around the idea of making it unnecessary to do so. Please check out the README.
