### ISSUE TITLE
Problem uploading to S3

### ISSUE THREAD

**Issue by chrisyeung1121** [refile/refile#260]
I was following the tutorial and try to get my files uploaded to S3. It doesn't seem to work. It is all still uplaoded to Local file system.

I was following the tutorial in the README.md but doesn't seem to work. Do I just need to config the initializer for it to be uploaded to S3? 

Here is a link to my repo: https://github.com/chrisyeung1121/refile-example

**Comment by abitdodgy** [comment]
It's a bit hard without any code examples, but looking at your repo, just to rule this out: Are you sure you are setting the env variables correctly?

**Comment by chrisyeung1121** [comment]
Yes I have tested a few times. Env is correct.

**Comment by chrisyeung1121** [comment]
Do you have a working demo?

**Comment by jnicklas** [comment]
Try booting a console and looking at the return value of `Refile.store`, what class is it an instance of? Try uploading something to it and see if it works.

**Comment by chrisyeung1121** [comment]
I did a `puts` in the refile initializer and the output has my access_keys and secret correct.

The following is the output of `Refile.store.inspect`

```
#<Refile::S3:0x007fdf90345298 @access_key_id="A......Q", @secret_access_key="m2a.......HRSqr", @s3_options={:access_key_id=>"A.......Q", :secret_access_key=>"m2a......HRSqr", :region=>"ap-southeast-1"}, @s3=#<Aws::S3::Resource>, @bucket_name="c.....ent", @bucket=#<Aws::S3::Bucket name="c......ent">, @hasher=#<Refile::RandomHasher:0x007fdf903451a8>, @prefix="store", @max_size=nil>
```

And then when I upload the file.

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZR8zHFo69fJg8516CE3JuSjzUfDzXfFX3RyTg6aaIYUK9RZrmugFr+I4qFhsS524ESzEq1LEKU/UJfjrSiWGhA==", "user"=>{"profile_image"=>#<ActionDispatch::Http::UploadedFile:0x007fdf89e92828 @tempfile=#<Tempfile:/var/folders/kn/29d686ds16s31t8mp0957dt40000gn/T/RackMultipart20150604-78993-1ize0b0.jpg>, @original_filename="2012-06-01 20.10.04.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_image]\"; filename=\"2012-06-01 20.10.04.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Create User"}
```
It is still going to the Tempfile.

output as shown here

```
16:09:32 rails.1 | Processing by UsersController#create as HTML
16:09:32 rails.1 |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZR8zHFo69fJg8516CE3JuSjzUfDzXfFX3RyTg6aaIYUK9RZrmugFr+I4qFhsS524ESzEq1LEKU/UJfjrSiWGhA==", "user"=>{"profile_image"=>#<ActionDispatch::Http::UploadedFile:0x007fdf89e92828 @tempfile=#<Tempfile:/var/folders/kn/29d686ds16s31t8mp0957dt40000gn/T/RackMultipart20150604-78993-1ize0b0.jpg>, @original_filename="2012-06-01 20.10.04.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_image]\"; filename=\"2012-06-01 20.10.04.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Create User"}
16:09:34 rails.1 |    (0.1ms)  begin transaction
16:09:34 rails.1 |   SQL (1.0ms)  INSERT INTO "users" ("profile_image_id", "created_at", "updated_at") VALUES (?, ?, ?)  [["profile_image_id", "146ef274b5e652f592346abb8951502d30d45ff03e9ba7e942c96b129232"], ["created_at", "2015-06-04 08:09:34.450531"], ["updated_at", "2015-06-04 08:09:34.450531"]]
16:09:34 rails.1 |    (0.8ms)  commit transaction
16:09:34 rails.1 | Redirected to http://localhost:3000/users/10
16:09:34 rails.1 | Completed 302 Found in 2022ms (ActiveRecord: 1.8ms)
16:09:34 rails.1 | Started GET "/users/10" for 127.0.0.1 at 2015-06-04 16:09:34 +0800
```

**Comment by jnicklas** [comment]
Rails always creates a Tempfile for uploads, that has nothing to do with Refile. The question is what happens after that.

**Comment by chrisyeung1121** [comment]
Not sure what happens after all I know is it gets redirects to `get` photo from `/attachment` .. 
Anyway I can debug it? or is there any working demo I can reference from~?

**Comment by chrisyeung1121** [comment]
@jnicklas  do you have a simple working S3 Direct upload example :+1:

**Comment by chrisyeung1121** [comment]
has anyone got direct upload to S3 working?

**Comment by abitdodgy** [comment]
@chrisyeung1121 I'm sure if your issue were widespread something would have surfaced here. I have gotten uploads to S3 working several times already without any issues.

**Comment by jnicklas** [comment]
@chrisyeung1121 commented somewhere that he got it working eventually, so I'm closing this.
