### ISSUE TITLE
Multiple images upload:  images are being replaced with uploaded image when updating.

### ISSUE THREAD

**Issue by kirillsalykin** [refile/refile#261]
Article has_many article_images.

Scenario:
1. Create article with image 'A'
2. Edit article and upload image 'B'.

Actual: Image 'A' was removed and article has only image 'B'
Expected: Article has both 'A' and 'B' images.

Also, when nested_form '_destroy' checkbox added to form - exception is being thrown 'Couldn't find ArticleImage with ID=22 for Article with ID=13'. 
ArticleImage with id=22 still exists in db, but image file was deleted.

```ruby
class Article < ActiveRecord::Base
  has_many :images, class_name: 'ArticleImage', dependent: :destroy

  accepts_attachments_for :images, attachment: :file
  accepts_nested_attributes_for :images, allow_destroy: true
end
```

```slim
.form-group
  = f.label :images
  = f.fields_for :images do |image_form|
    .cf
      = image_tag attachment_url(image_form.object, :file, :fill, 150, 150, format: "jpg"), class: 'img-thumbnail'
      br
      = label_tag :remove_images do
        = image_form.check_box :_destroy
        = t('general.remove')
  .input-group
    span.input-group-btn
      span.btn.btn-primary.btn-file
        = t('general.browse')
        = f.attachment_field :images_files, multiple: true
    input type="text" class="form-control" readonly='readonly'
```
```ruby
def article_params
    permitted = params.require(:article).permit(images_files: [], images_attributes: [:id, :_destroy])
    permitted
  end
```

**Comment by jnicklas** [comment]
Please file separate issues separately.

The behaviour you're describing is the expected default behaviour. If you want the images not to be replaced then set `append: true` on `accepts_attachments_for`.

I'm a bit confused as to why you're using both `accepts_attachments_for` and `accepts_nested_attributes_for`? It seems that in your case you are using `accepts_nested_attributes_for` which is part of Rails, so I can't really see how the error you're getting has anything to do with Refile.

**Comment by kirillsalykin** [comment]
@jnicklas thanks! 
append: true makes exactly what i need. Also, exception is not fired because attachments not replaces anymore.

Can you please add append: true to readme?

**Comment by jnicklas** [comment]
I just added it. I do want to point out that we have rather extensive API documentation and that `append: true` is documented there.
