### ISSUE TITLE
File upload API support for iOS/Android

### ISSUE THREAD

**Issue by chrisyeung1121** [refile/refile#268]
I am using the rails application as an API for iOS and Android backend as well. I wonder if Refile plays along well with iOS/Android?

**Comment by jnicklas** [comment]
It depends on what you mean by play well. Refile works fine on Mobile Safari and Chrome. If you need to upload from a native app, you can do that via multipart form posts. I think Sinatra also supports binary post bodies, but I'm not 100% sure. Other than that there should be no issues using the mounted app from a native app.
