### ISSUE TITLE
Determine custom file path and reveal file extension in S3

### ISSUE THREAD

**Issue by chrisyeung1121** [refile/refile#269]
I got it working to upload files in S3. And I saw two folders, `cache` and `store` as mentioned in the documentation.

When I browse into it, it's a id hash like `50a755acd78e62a53d644eec4d103a59ac88dbc4047b8bdec568f32db956`. 

I wonder if it is possible to use file names and have custom directory structure?

**Comment by abitdodgy** [comment]
I don't believe this is possible at the moment because of the way Refile works. Besides, the filename and extension can be stored in your app. When downloading the file it will have the name and extension. Check issue number #240

**Comment by jnicklas** [comment]
This is not possible no. If you need control over the directory structure, Refile is not the right choice for you. That being said, the whole idea of Refile is that you should not care about the directory structure at all.

**Comment by iRonin** [comment]
> That being said, the whole idea of Refile is that you should not care about the directory structure at all.

Except that some of prefer or need an order on their few-hundred-million-object S3 buckets, don't they? :)
