### ISSUE TITLE
Clash with attachment_url method

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#270]
I'm justing putting this out there for discussion. We have an Attachment model, and some of its controller routes are clashing with `attachment_url` that Refile uses. We'll either add a namespace, or nest attachment routes under a parent model. Just food for thought, but I wonder how much of an impact this has on older applications have have `attachments_controller` and so forth. I our case we're early in the building stages of our app, so the cost of making this change is rather cheap.

**Comment by jnicklas** [comment]
We could provide an alias called something like `refile_attachment_url` or something, what do you think about that?

**Comment by abitdodgy** [comment]
@jnicklas IMO that would be great to have. Would you like a pull request? This might be a bit out of my depth, to be honest, but we all have to start somewhere, so I don't mind giving it a bash when I have some time. What do you think?

**Comment by jnicklas** [comment]
Yeah, give it a shot! :)

**Comment by monkbroc** [comment]
I ran into this as well. I made an `Attachment` model with a polymorphic association to a couple other models in my app. I ended up renaming it to `FileAttachment` just to work around the name collision with the `AttachmentHelper#attachment_url` helper.

So this is going to keep happening to others.

I'm not sure what could be done to fix this since renaming `attachment_url` would break existing applications.

**Comment by toothfairy** [comment]
I believe attachment_url is a very abstract and common method name to use. Perhaps ```refile_url``` might be replacement for it in some future. It directly references to it's nature and would help to avoid names collisions. @jnicklas what do you think about it?

**Comment by abitdodgy** [comment]
@toothfairy one of the suggestions that @jnicklas already made is `refile_attachment_url`, which I think is a better suggestion. I think `refile_url` is too ambiguous.

**Comment by toothfairy** [comment]
Not sure in what way it's ambiguous, @abitdodgy, but may be you're right. In my opinion ```__attachment__``` part in refile_attachment_url makes it way to explicit and long. In context of refile,  method named ```*_url``` can barely mean something else than attachment url. 

Also making alias won't solve the problem entirely (there still would be two methods with the save name in a different parts of application). My idea was to rename ```attachment_url``` to ```refile_url``` (or ```refile_attachment_url```)

**Comment by abitdodgy** [comment]
@toothfairy `refile_url` could be mistaken for where you mount your refile app, for example. But why would there be more than one `refile_attachment_url`?

**Comment by rilian** [comment]
I have "fixed" this issue in my project by explicitly calling `Refile.attachment_url` :)

Here is a small PR to include this advice in the documentation: https://github.com/refile/refile/pull/430/files#diff-04c6e90faac2675aa89e2176d2eec7d8R405

**Comment by sobrinho** [comment]
Closing since #430 got merged, use `Refile.attachment_url(...)` in case of collision.

Thanks!
