### ISSUE TITLE
NoMethodError when using accepts_attachments_for macro

### ISSUE THREAD

**Issue by mikeahmarani** [refile/refile#273]
Super straightforward but somehow I get an error when doing:

    class Post < ActiveRecord::Base
        has_many :photos, dependent: :destroy
        accepts_attachments_for :photos, attachment: :source, append: true
    end

**Comment by jnicklas** [comment]
It's not in the released gem yet. You can see the documentation for the current version here: http://www.rubydoc.info/gems/refile

**Comment by mikeahmarani** [comment]
Yeah I closed the issue because I realized that and just used the repo as the gem source. Thanks for the quick reply!

**Comment by jnicklas** [comment]
I figured :) just wanted to document it in case someone else stumbles upon
this.
