### ISSUE TITLE
How to display image at native aspect ratio?

### ISSUE THREAD

**Issue by abrambailey** [refile/refile#283]
I can see how to grab the image like so:
```
<%= image_tag attachment_url(@post, :image, :fill, 100, 100) %>
```
However, I'm wondering if there is some alternative, just just pull down based on one edge of the image. Something like:
```
<%= image_tag attachment_url(@post, :long_edge, 100) %>
```
This would be ideal as you could ensure the image gets pulled at an appropriate size, without cropping. Right now it seems like you have to pull down the full size version of the image if you want to ensure the entire image is shown. I'm sure I'm missing something?

**Comment by Titinux** [comment]
Try
``` ruby
<%= image_tag attachment_url(@post, :image, :fit, 100, 100) %>
```

fit : No cropping, ratio preserved and the longest edge is 100px

**Comment by abrambailey** [comment]
Oh cool! This might be worth throwing into the readme. I think this is more typical usage for image rendering in views.

**Comment by njcameron** [comment]
+1 for readme took me 30 mins to get here
