### ISSUE TITLE
Discussion (mailing list?)

### ISSUE THREAD

**Issue by walterdavis** [refile/refile#284]
I don't want to clutter issues with usage and migration discussion (unless that's appropriate). Is there a mailing list for this Gem?

Thanks,

Walter

**Comment by jnicklas** [comment]
Not currently. I used to have mailing lists for all my projects, but I'm a bit disillusioned with the format. You're welcome to ask questions here on the issue tracker, just be prepared that I'm probably going to close them pretty quickly with a short reply. Another option is StackOverflow, though honestly the quality of the answers usually isn't great.

**Comment by janko-m** [comment]
I think the discussion on the GitHub issue tracker worked pretty well so far, I always prefer it because you can write code more easily, mention people, reference issues and all other GitHub goodies.

**Comment by walterdavis** [comment]
Thanks, I do agree. But I have been in several other projects where the leaders would dismissively close all issues that were not specific to pull requests or actual error reports, so I wanted to ask before I got my fingers slammed in the door.

Walter

**Comment by janko-m** [comment]
Yes, I know what you mean, I first found out when using Sequel that projects besides the issue tracker can also have mailing lists, so always good to ask. @jnicklas are we continuing then with the issue tracker?

**Comment by jnicklas** [comment]
I think I'd like to continue like this for now. @walterdavis feel free to open questions as issues on this project.
