### ISSUE TITLE
Cannot get external processing to work?

### ISSUE THREAD

**Issue by lephyrius** [refile/refile#291]
I want to use a separate processing server for refile. 
So I created a small experimental processing server and started it with puma:
`puma -t 1:4 -p 9292`

But I only get this error when I try to get images from the server.
 ```
127.0.0.1 - - [06/Jul/2015:09:39:40 +0200] "GET /attachments/store/joken/320/320/true/true/e56f00d76ba50d6bf7cf0e95a8d209e867f34fea9a887f94fd5cfda4614c/cover_image.png HTTP/1.1" 404 9 0.0048
E, [2015-07-06T09:39:42.993539 #1837] ERROR -- : Refile::App: Could not find processor: store
I, [2015-07-06T09:39:42.993823 #1837]  INFO -- : Refile::App: [2015-07-06 09:39:42 +0200] GET "/attachments/store/joken/320/320/true/true/e56f00d76ba50d6bf7cf0e95a8d209e867f34fea9a887f94fd5cfda4614c/cover_image.png" 404 0.5ms
```
I have added:
```ruby
Refile.cache = Refile::S3.new(prefix: 'cache', **aws)
Refile.store = Refile::S3.new(prefix: 'store', **aws)
```
It really doesn't work!

So after that I tried with adding a secret key(it might be that's what is missing) but only get this error:
```ruby
Refile.secret_key = '123'
```
error:
```
! Unable to load application: NoMethodError: undefined method `secret_key=' for Refile:Module
```

Need some help! I dunno where to go from here? :watermelon:

**Comment by jnicklas** [comment]
It it possible you have a version mismatch between the server (running `master` probably) and the client (running 0.5.5)? That's what the error sounds like to me.

**Comment by lephyrius** [comment]
I made sure both was on 0.5.5 but it resulted in the same error.
So I switched to master and it resulted in almost identical error:
```
E, [2015-07-06T14:57:18.383036 #1486] ERROR -- : Refile::App: Could not find processor: store
I, [2015-07-06T14:57:18.383262 #1486]  INFO -- : Refile::App: [2015-07-06 14:57:18 +0200] GET "/attachments/b40590d7161ced19aa5521f983115b5a23784b22/store/joken/320/320/true/true/e56f00d76ba50d6bf7cf0e95a8d209e867f34fea9a887f94fd5cfda4614c/cover_image.png" 404 0.5ms

127.0.0.1 - - [06/Jul/2015:14:57:18 +0200] "GET /attachments/b40590d7161ced19aa5521f983115b5a23784b22/store/joken/320/320/true/true/e56f00d76ba50d6bf7cf0e95a8d209e867f34fea9a887f94fd5cfda4614c/cover_image.png HTTP/1.1" 404 9 0.0006
```

**Comment by janko-m** [comment]
The only way I think this could happen is if you mounted the Refile app on `/` instead of on `/attachments`. Then Refile thinks that `attachments` is the name of the backend, and proceeds further with the notion that `store` is a processor.

In Rails it could have happened if you set `Refile.automount = false`, and then accidentally mounted it on `"/"` instead of `Refile.mount_point`.

**Comment by jnicklas** [comment]
Closing this issue. @janko-m's explanation sounds plausible, and we haven't heard back from OP.
