### ISSUE TITLE
New tag request

### ISSUE THREAD

**Issue by jeremymarc** [refile/refile#294]
I would like to be able to use accepts_attachments_for using the last tag available. Right now its not possible (have to pull from master).

**Comment by matiasmasca** [comment]
+1

**Comment by jeremymarc** [comment]
nobody?

**Comment by fabn** [comment]
+1

**Comment by jnicklas** [comment]
Working on it. I was planning on doing a v1.0 release, but now scaling back to doing a v0.6 release first. That gives me the option of putting off some hard decisions which are needed to solve #229.

**Comment by jnicklas** [comment]
New version is released! Finally! :tada:
