### ISSUE TITLE
how to store extra information into image classes

### ISSUE THREAD

**Issue by mlchai** [refile/refile#296]
I'm using a multiple upload so I followed the guide for that in the README. I have an Image model but I need to store who uploaded the image. What would be the best way for me to do this?

**Comment by abitdodgy** [comment]
Why not add a column that stores the current user id? Presumably you have a login system where the current user is available. Just add a column to the image model that stores the id of  the current user.

**Comment by pickerflicker** [comment]
How do you go about setting the user_id?  Is there a callback after the model with the image is saved?

**Comment by mlchai** [comment]
I already added the column to do so. My problem is getting the actual user id. So far I don't see any way to do that with refile since the images are uploaded upon a model save action. I can't get the returned images that way, and I haven't seen a way to pass a block in to add/save additional attributes.

**Comment by abitdodgy** [comment]
Let's assume the parent model is called `Upload` and the child model is called `Image`. So an `upload` `has_many` `images`.

Can't you do something like this in the controller:

```ruby
def create
  @upload = Upload.new(upload_params)
  @upload.images.each { |image| image.owner = current_user }
  if @upload.save
  # ... etc
end
```

Or in the model... assuming upload has a user_id column.

```ruby
class Upload
  # ...
  before_save :set_owner

private

  def set_owner
    images.each { |image| image.owner = owner }
  end
end
```

**Comment by mlchai** [comment]
I can't do that. Let's say I have Image1 and Image2. User1 uploaded Image1, but when User2 uploads Image2 the code will set the uploader of Image1 to User2. In the second example, that's what I want to do but the problem comes in where are you getting the owner? The current user needs to be passed in somehow, and current_user is usually a controller method that isn't available in models.

**Comment by abitdodgy** [comment]
It's a hard for me to provide more help without some example code from you. But if you can't use controller example then there maybe something wrong with your setup. If you can show the relevant controller and model code, including your database columns, I might be able to help.

**Comment by jnicklas** [comment]
This question is not really related to Refile.

**Comment by holden** [comment]
@mlchai I'm having the same issue, did you ever find a solution?

**Comment by mlchai** [comment]
@holden I didn't find a clean solution I liked, but here's one:
http://stackoverflow.com/questions/2513383/access-current-user-in-model
