### ISSUE TITLE
Painfully slow image loading

### ISSUE THREAD

**Issue by famousky** [refile/refile#297]
Refile serve the assets from the cache instead of directly from S3 url and the loading times are really low for some reason. Trying to investigate why this is happening.

Question @jnicklas : **Why Refile doesn't link directly to assets on S3 and use cache instead?**

**Comment by jnicklas** [comment]
Because that's how it is designed. Please re-read the README.

**Comment by famousky** [comment]
@jnicklas why this issue is closed? 

I understand this is the way the refile works but there is still issue with slow image loading. I will add more info once I find why this is happening.
