### ISSUE TITLE
accepts_nested_attributes_for does not know when to create an image

### ISSUE THREAD

**Issue by yaroslav** [refile/refile#300]
Not sure if it's a feature request or just some sort of misconfiguration.

I have to use a `Entity has_one Image` schema in my project. Normally, that would be a multiple images upload — just as you have in the `README`, but I have to use `has_one`. 

So initially I had to pass `accepts_nested_attributes_for` something like this:

```ruby
accepts_nested_attributes_for :photo, allow_destroy: true,
  reject_if: lambda { |attributes| attributes['image'].empty? }
```

However, that does not really work. The way controller passes the params is something like this:

```
... "photo_attributes"=>{"image"=>"null", "remote_image_url"=>"", "_destroy"=>"0" ..
```

on updates, or just

```
... "photo_attributes"=>{"image"=>"null"} ..
```

On new records. Naturally, `image` is not `blank`, so ActiveRecord tries to create a Photo with an empty image.

`"null"` is there because of an input with `data-reference` which is generated by the refile helper, and it seems that it does not matter if I use direct uploads or not. Not sure if this is all by design, but I've ended up with doing this:

```ruby
  accepts_nested_attributes_for :photo, allow_destroy: true,
    reject_if: lambda { |attributes| Photo.empty_attributes?(attributes) }
```

```ruby
  def self.empty_attributes?(parameters)
    (parameters[:image].blank? || parameters[:image] == "null") &&
      parameters[:remote_image_url].blank?
  end
```

Am I wrong/misunderstanding the design somewhere or is there a room for improvement?

**Comment by yaroslav** [comment]
Oh, sorry, refile master (0dc2072a90), Rails 4.2.3

**Comment by abitdodgy** [comment]
@yaroslav I'm curious, how do you use accepts_nested_attributes_for with multiple uploads? I'm under the impression that you either use `accepted_attachments_for` or `accepts_nested_attributes_for`. Or am I misunderstanding you?

**Comment by yaroslav** [comment]
@abitdodgy I'm using `accepts_nested_attributes_for` for a `has_one` relationship and besides the issue described it all works just fine.

**Comment by abitdodgy** [comment]
@yaroslav Gotcha, I was hoping there was a way to do multiple uploads with additional attributes without some JS hackery!

**Comment by jcuenod** [comment]
@abitdodgy I'm hoping for the same thing.

**Comment by jnicklas** [comment]
The value in that field should be blank and not "null".

**Comment by jnicklas** [comment]
Fixed.

**Comment by yaroslav** [comment]
Thanks!!

On Thursday, September 10, 2015, Jonas Nicklas <notifications@github.com>
wrote:

> Fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/refile/refile/issues/300#issuecomment-139242087>.
>


-- 
Yaroslav
