### ISSUE TITLE
Presign URL is being hit over CDN

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#301]
I'm getting a CORs error while uploading after I added a CDN.

```
XMLHttpRequest cannot load http://redacted.cloudfront.net/attachments/cache/presign?t=1437108378113.0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

Refile is sending a GET request to presign the upload straight to the CDN. Is this normal? The CloudFront response is a 307 temporary redirect to my bucket. I'm a bit stumped because everything works wonderfully well until I set the host to my CDN distro.

1. I created a bucket with  `cache` and `store` folders.
2. I added a CORS config

    ````xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
        <AllowedHeader>Content-Type</AllowedHeader>
        <AllowedHeader>Origin</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
    ````
3. I created an AWS user and added a bucket policy for this user:

    ````json
{
	"Version": "2012-10-17",
	"Id": "",
	"Statement": [
		{
			"Sid": "",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::id:user/username"
			},
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::bucket",
				"arn:aws:s3:::bucket/*"
			]
		}
	]
}
    ````
4. I've configured the refile initializer.
    ````ruby
require "refile/s3"

aws = {
  access_key_id: Rails.application.secrets.AWS_KEY_ID,
  secret_access_key: Rails.application.secrets.AWS_SECRET_ACCESS_KEY,
  region: Rails.application.secrets.AWS_REGION,
  bucket: Rails.application.secrets.AWS_BUCKET,
}

Refile.cache = Refile::S3.new(prefix: "cache", **aws)
Refile.store = Refile::S3.new(prefix: "store", **aws)
    ````

At this point everything is working well. I created a CloudFront distribution for my bucket with essentially the defaults. Once I added the distribution to refile, I started getting the error.

````ruby
Refile.host = Rails.application.secrets.CLOUDFRONT_DISTRUBUTION
````

I have a feeling I'm not setting up my CDN correctly, but I am not tampering with the defaults. Any ideas?

**Comment by abitdodgy** [comment]
I've managed to get one step further by editing the CloudFront CDN to forward headers onto origin. But now I'm getting a 403 forbidden. I've amended the bucket policy to ensure CloudFront has access to the bucket.

```json
		{
			"Sid": "2",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity [redacted]"
			},
			"Action": "s3:*",
			"Resource": "arn:aws:s3:::nimbusws-dev/*"
		}
```

If anyone has anyone successfully setup Refile with CloudFront, would you be kind enough to share your CDN config, or some details on the process?

**Comment by abitdodgy** [comment]
Sorry, I don't mean to spam, but I amended the policy again, and this time, when trying to upload files I'm getting a `GET http://[dist].cloudfront.net/attachments/cache/presign 404 (Not Found)` error. I'm not sure why. I'm also not sure where `attachments` is coming from in the URL. If I do `Refile.host` in the terminal I get `"http://[dist].cloudfront.net/`, which is how I set it up. 

I came across issue #217 but it's not proving helpful.

**Comment by jnicklas** [comment]
I'm pretty sure this is a bug. The presign URL is not supposed to be hit over the CDN. I've checked the code and it looks wrongs to me, so this is probably just simply broken. At the same time it feels a bit wrong to simply ignore `Refile.host` in this case. What if someone has mounted the app somewhere else, and the current app doesn't even have the Refile app mounted? That would break totally, with no way of fixing it.

I'm not sure how to best go about fixing this. Let me think it over a bit.

**Comment by abitdodgy** [comment]
@jnicklas Weirdly enough, despite the 404, the images still upload. When trying to request the files I get this URL that produces a 404 (I've cut off some of the characters to shorted it):

```
//[dist].cloudfront.net/attachments/ec9f427de977492..../store/fill/100/100/74f17f4947c27bdb.../profile_image
```

Where `profile_image` is the name of the attachment field. I imaged this would be:

```
//[dist].cloudfront.net/store/fill/100/100/74f17f4947c27bdb.../profile_image
```

This maybe a similar issue to #217. Also, PR #292 may or maybe be related here.

Is there a quick/dirty way to get working? I'm also a bit worried about existing uploads, and if transitioning to a CDN now will impact those.

**Comment by thomasklemm** [comment]
I'm not sure this is an issue. I'm also seeing the Presign-URL being hit via Cloudfront, but the request is passed through to the app and no cached response returned.

```
GET request to https://d1eavxxee7beiy.cloudfront.net/attachments/cache/presign
Response headers:
Cache-Control:max-age=0, private, must-revalidate
X-Cache:Miss from cloudfront
```
`Object caching` in the Cloudfront distribution is set to **`Use Origin Cache Headers`**, so the app decides on which headers to add, and Cloudfront respects theses headers and passes them on.

@abitdodgy Any chance your distributon is configured to customize the response headers (see 'Default Cache Behavior Settings' > 'Object caching')?

**Comment by abitdodgy** [comment]
I doubt it but I will take a look as soon as I get to the office. But why
not got directly to S3 when presigning? What does going through the CDN
achieve? In my case, the URLs are being malformed despite the upload going
through, which is a similar issue to the one I referenced here from some
months ago. It seems that there is something off with the CDN given several
people are reporting issues.

**Comment by ivobenedito** [comment]
I'm also getting some issues with the presign URL passing on the CDN for multiple file uploads.

If I upload 5 files, the first one is a miss from CloudFront, but the other 4 are all Hit from CloudFront. In some cases it returns exactly the same file id and in other cases it doesn't. 

This means the multiple file upload fails randomly when the CDN Host is active on Refile. 
If I point the data-url to the Refile Endpoint, it just works.

**Comment by abitdodgy** [comment]
@thomasklemm and @ivobenedito can you please show me an example of what the CDN URLs look like in your app?

@thomasklemm I can confirm that `Object Caching` is set to `Use Origin Cache Headers`. I've solved this issue thanks to @ivobenedito by passing in `host: request.base_url` to `attachment_field` and now presign requests go straight to S3. But after the upload is done I'm getting 404 on all files. @ivobenedito I still can't figure out for the life of my what I'm doing wrong. My urls look like this:

`http://[dist].cloudfront.net/attachments/:id/store/fill/100/100/:key/profile_image`

Where `:id` is the refile id and `:key` is the file key. Going to `http://[dist].cloudfront.net/store/key` works. But I don't know how that URL makes sense.

**Comment by ivobenedito** [comment]
@abitdodgy You're saying that you're uploading with success but after when the files are moved from cache to store you get 404? Is S3 bucket well configured as an origin of the CDN? How about turning off CDN and serving directly with S3? Does it work? You can test it locally on localhost.

**Comment by abitdodgy** [comment]
@ivobenedito yes! I believe my bucket is configured correctly. I created a test application since it's easier to see than explain. It shows the behaviour I'm talking about.

## Example app
1. App address: [refile-test.herokuapp.com][1]
2. CDN is CloudFront, everything left at its defaults.
3. S3 bucket: [refile-example][2] accessible to world, CORs setup correctly.
4. Repo for example app: [https://github.com/Aerogami/refile-test][3]

The bucket has all the right CORs config (taken from here) and a policy that allows it to be read from public.

We have an `Upload` model that `has_many :documents`. Everything works fine. Except for when using the CDN to retrieve the files. In the document partial I have two rows for each document. One resets the host, to show that the file really is there, and the first one is the default, or using the CDN, which shows a 404.

[1]: refile-test.herokuapp.com/
[2]: http://refile-example.s3.amazonaws.com/
[3]: https://github.com/Aerogami/refile-test

**Comment by abitdodgy** [comment]
Sorry, I don't mean to be a pest, but before I bash my head against the wall again, I'd like to know if this is a bug, or if I'm doing something wrong. I've setup [a test app][1] that shows that uploaded files are not being served from the CDN. I'm curious if anyone is able to use a CDN with Heroku successfully, and how they've achieved that. 

@jnicklas should we split this into two issues? Two things are going on here:

1. Presign requests are going through the CDN.
2. Assets are not being served from the CDN.

What do you think?

  [1]: http://refile-example.herokuapp.com

**Comment by goodviber** [comment]
I have a similar issue, my correct s3 url  via Cloudfront is 
      ```"//my-dist-url/store/7868768768687689768768976876876876868768768768998"```
but using the attachment_image_tag in my view it is rendering as
     ``` "//my-dist-url/attachments/store/7867687687687687687687687687687687687686/image.jpg"```
which does not show the image.
I can upload to s3 without any issue, yet the "attachments" and "image.jpg" are throwing me a curve.

**Comment by jnicklas** [comment]
The CDN is supposed to be in front of your app, not in front of S3.

**Comment by abitdodgy** [comment]
@jnicklas Do you mean that the CDN **Origin Domain Name** should be pointing back to the app instead of the S3 bucket?

**Comment by jnicklas** [comment]
Yes. Exactly.

**Comment by goodviber** [comment]
So the Origin Domain Name would be www.my_app.com?
What would the Origin Path be, or should it just be left blank?

**Comment by abitdodgy** [comment]
@goodviber yes, it should be your apps URL. As for the Origin Path, leave it blank. I just tested this and it works.

**Comment by goodviber** [comment]
**@abitdodgy** is your repo above now fully functional and also what set up do you have for Cloudfront?
re: **Alternate Domain names (cnames)**
**Origin Domain Name** and anything else that varies from standard setup.
I have tried everything with no luck. I can get the images to to display only by stripping the url string of "attachments"  and "image.jpeg". This works ok, but feels like a horrible hack...

**Comment by abitdodgy** [comment]
@goodviber yes, it's fully functional. I only made sure that **Origin Domain Name** was pointing to `refile-example.herokuapp.com`. That's all I did, and it worked. The CDN setup is the default one. **Origin Domain Name** is the only thing I changed. It was pointing to my S3 bucket, which prevented it from working. The rest are defaults.

**Comment by goodviber** [comment]
Thanks @abitdodgy , I finally got the whole thing working...

**Comment by jnicklas** [comment]
So I finally got around to tackling this issue properly. We now have two separate host settings, `Refile.app_host` which affects *all* URLs generated by Refile, and `Refile.cdn_host`, which only affects `file_url` and `attachment_url`.

Needless to say, if you have a CDN set up, you should only set `Refile.cdn_host`.

The regular `Refile.host` is now deprecated, to prevent confusion.

**Comment by ivobenedito** [comment]
Awesome @jnicklas :)! Great addition. Thx!!

**Comment by acandael** [comment]
I changed the Origin Name to my app domain name, and set the refile host setting in the initializer file to to the Cloudfront distribution name, and it worked!!

But I wasn't able anymore to upload image to S3 storage : (

Does anyone have an idea how to fix this?

Im using Refile version 0.5.4

thanks for your help,

Anthony

**Comment by ivobenedito** [comment]
@acandael Upgrade to Refile latest version 0.6.2 and replace `Refile.host` by `Refile.cdn_host`.

**Comment by acandael** [comment]
thanks, I upgraded Refile to 0.6.2, everything is working. The only thing that's broken is the preview image in my upload form. Don't know what's causing this.

greetings,

Anthony

**Comment by ivobenedito** [comment]
Preview image? Probably that's not related to Refile :)

**Comment by acandael** [comment]
@ivobenedito with 'preview image' I mean the image that's get shown in the form, before it get's uploaded.

The form code looks like this:

    <% if @member.image_id? %>
      <%= image_tag attachment_url(@member, :image, :fill, 150, 150) %>
      <div class="check_box">
        <%= f.check_box :remove_image %>
        <%= f.label :remove_image %>
      </div>
    <% end %>

    <%= f.attachment_field :image, direct: true, data: { remote_id: :member_image_cache_id } %>

The Coffeescript that handles the preview looks like this:

    $ ->
  "use strict"

  if !document.addEventListener
    return

  document.addEventListener "change", (changeEvent)->
    input = changeEvent.target
    if input.tagName == "INPUT" && input.type == "file" && input.getAttribute("data-direct")
      if !input.files
        return

      file = input.files[0]
      metadataField = input.previousSibling

      dispatchEvent = (name, detail)->
        ev = document.createEvent('CustomEvent')
        ev.initCustomEvent(name, true, false, detail)
        input.dispatchEvent(ev)

      if file
        url = input.getAttribute("data-url")
        fields = JSON.parse(input.getAttribute("data-fields") || "null")

        data = new FormData()

        if fields
          Object.keys(fields).forEach (key)->
            data.append(key, fields[key])

        data.append(input.getAttribute("data-as"), file)

        xhr = new XMLHttpRequest()
        xhr.addEventListener "load", ()->
          input.classList.remove("uploading")
          dispatchEvent("upload:complete", xhr.responseText)
          if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304)
            id = input.getAttribute("data-id") || JSON.parse(xhr.responseText).id
            if metadataField
              metadataField.value = JSON.stringify({ id: id, filename: file.name, content_type: file.type, size: file.size })
              input_id = input.getAttribute("data-remote-id")
              metadataField.setAttribute("id", input_id)
            input.removeAttribute("name")
            dispatchEvent("upload:success", xhr.responseText)
          else
            dispatchEvent("upload:failure", xhr.responseText)

        xhr.upload.addEventListener "progress", (progressEvent) ->
          if progressEvent.lengthComputable
            dispatchEvent("upload:progress", progressEvent)

        xhr.open("POST", url, true)
        xhr.send(data)

        input.classList.add("uploading")
        dispatchEvent("upload:start", xhr)
