### ISSUE TITLE
Document CloudFront options when using direct uploads?

### ISSUE THREAD

**Issue by yaroslav** [refile/refile#302]
Hello, just noticed that on production when using S3 + CloudFront, the uploader hits CDN with an `OPTIONS` request, which is filtered out by default when creating a new CF distribution.

When used with a sample JavaScript code to enable/disable the submit button, that of course resulted in submit button to stay disabled.

**Comment by abitdodgy** [comment]
@yaroslav Aparently presigned URLs should not go through the CDN. See #301 which I just opened. I'm curious at how you were able to get this to work. Which gem and Ruby versions are you using? Can you share your Refile initializer?

I was not able to get this to work. My URLs are becoming malformed. See #301 for more details.

**Comment by yaroslav** [comment]
>  I'm curious at how you were able to get this to work

I guess I did not! I was playing around to resolve #300, enabling and disabling the JS library as well as direct uploads. Since everything was working locally, I just pushed direct uploads to production once and ran into mentioned issues.

**Comment by thomasklemm** [comment]
When using presigned uploads, I am seeing the following requests in this order:

1. A `GET` request to the presign endpoint through the CDN.
2. An `OPTIONS` request to the **S3 bucket** (not to Cloudfront).
3. A `POST` requet to the S3 bucket.

@yaroslav Can you verify that the `OPTIONS` request is made to the S3 Bucket, not the CDN? If so, this issue can be closed.

**Comment by yaroslav** [comment]
In my case, `OPTIONS` went to CloudFront.
