### ISSUE TITLE
How to not crop and keep image ratio, setting a maximum height, 100% width

### ISSUE THREAD

**Issue by andiruleu** [refile/refile#303]
Been trying to look everywhere for a solution but no luck... How do I NOT crop my image and keep the image ratio with having a max height and doing a 100% width? 

My current image tag:

    <%= attachment_image_tag(image, :file, :fill, 100, 430) %>

want to keep 430 as the height, and change 100 to 100%? and what do I change :fill to?

**Comment by abitdodgy** [comment]
See issue #283. I think you are looking for this:

```erb
<%= attachment_image_tag(:image, :fit, 100, 430) %>
```

To quote:

> No cropping, ratio preserved and the longest edge is 100px

**Comment by andiruleu** [comment]
Can I get 100% on the width side? How would I get a percentage?

On Monday, July 20, 2015, Mohamad El-Husseini <notifications@github.com>
wrote:

> See issue #283 <https://github.com/refile/refile/issues/283>. I think you
> are looking for this:
>
> <%= attachment_image_tag(:image, :fit, 100, 430) %>
>
> To quote:
>
> No cropping, ratio preserved and the longest edge is 100px
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/refile/refile/issues/303#issuecomment-123139084>.
>


-- 
Andrew Liu


"I'm convinced that the only thing that kept me going was that I loved what
I did." - Steve Jobs

"Intelligence plus character - that is the goal of true education." - Dr.
Martin Luther King, J

**Comment by janko-m** [comment]
The following should work:

```erb
attachment_image_tag(:image, :fit, nil, 430)
```
