### ISSUE TITLE
undefined method `files_attachment_definition'

### ISSUE THREAD

**Issue by DerAlSem** [refile/refile#304]
Hi,

Trying to switch from Paperclip to Refile.

`gemfile` (just in case)

``` ruby
gem "refile", require: "refile/rails", git: 'https://github.com/refile/refile.git', branch: 'master'
gem "refile-mini_magick"
```

I have features:

`feature.rb`

``` ruby
class Feature < ActiveRecord::Base
    has_many :assets, dependent: :destroy
    accepts_attachments_for :assets, append: true  

    def post_params
      params.require(:feature).permit(files: [])
    end
end
```

Each features has assets. 

`asset.rb`

``` ruby
class Asset < ActiveRecord::Base
    belongs_to :feature
    attachment :file

    enum category: { 'А/В' => 1, 'Для прессы' => 2, 'Документы' => 3,  'Другое' => 4 }
    categories
    [['A/V', 1], ['Для прессы', 2], ['Документы', 3]]

    def asset_params
        params.require(:asset).permit(:file)
    end

end
```

Basically an asset - is a file, which can be downloaded. Before downloading it should be uploaded. Hi, captain. So, form is:

`views/assets/form.html.erb`

``` ruby
<%= form_for @asset, :url => {:action => :create, :method => :post}, :html => {:multipart => true} do |f| %>
 <p>
    <strong>Choose file for upload</strong>
    <%= f.attachment_field :files, multiple: true %>
  </p>
end
```

NoMethodError in Assets#new 

undefined method `files_attachment_definition' for #Asset:0xb41c35a4

for line
`<%= f.attachment_field :files, multiple: true %>`

I've run through docs once more. Noticed, that controller should be updated too.

``` ruby
def feature_params
params.require(:feature).permit(assets_files: [], :title_en)
end 
```

This gives me another error: 

SyntaxError in FeaturesController#edit 
/home/deralsem/devel/upi-rus/app/controllers/features_controller.rb:72: syntax error, unexpected ',', expecting => ...it(assets_files: [], :title_en, :title_ru, :release_date, :g... ... ^

Any advise much appreciated.

Update:

``` ruby
def feature_params
params.require(:feature).permit(:assets_files [], :title_en)
end 
```

moved colon before asset_files, error is gone, but undefined_method is still there. ;-(

**Comment by abitdodgy** [comment]
You assert model:

```ruby
categories
[['A/V', 1], ['Для прессы', 2], ['Документы', 3]]
```

It looks wrong. What's this supposed to be?

**Comment by DerAlSem** [comment]
Hi,

it is enum categories. http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

It is totally OK and worked like a charm with Paperclip, i really doubt, that they are the reason.

Thanks.

**Comment by abitdodgy** [comment]
I'm confused. The issue title says you're getting a different error than the stack trace, which is a syntax error. Which is it?

**Comment by DerAlSem** [comment]
Hope this make sense: 
![image](https://cloud.githubusercontent.com/assets/10348327/8870585/de383d0a-31f7-11e5-9ec4-907af45fe30a.png)

**Comment by ahmgeek** [comment]
+1

**Comment by jnicklas** [comment]
Sorry for the very late reply, seems to me the only problem is that you have:

``` erb
<%= f.attachment_field :files, multiple: true %>
```

Which should be:

``` erb
<%= f.attachment_field :assets_files, multiple: true %>
```

**Comment by jnicklas** [comment]
This should probably generate a better error message.

**Comment by DerAlSem** [comment]
Thanks, i will give it one more try. ;-)

**Comment by sobrinho** [comment]
@juarezlustosa will chime on this.
