### ISSUE TITLE
How would you remove files from multiple images?

### ISSUE THREAD

**Issue by andiruleu** [refile/refile#305]
The documentation shows how to remove files in a simple form, but what if I have images displayed in a loop?

    <%= simple_form_for @project, html: { multipart: true } do |f| %>

      <% @project.project_images.each do |img| %>
        <%= attachment_image_tag(img, :file, :fit, 1000, 430) %>
      <% end %>

      <%= f.attachment_field :trip_images_files, multiple: true %>
      <%= f.button :submit %>
    <% end %>

Where would we add the remove checkbox? I have asked this in stackoverflow but no help. http://stackoverflow.com/questions/31556113/attaching-checkboxes-to-an-array-of-images-inside-form-in-ruby-on-rails-using-r?noredirect=1#comment51069522_31556113

**Comment by anti-destin** [comment]
I do this:

```
<%= f.simple_fields_for :avatars do |a| %>                                                                                                                         
  <div class='inline-box'>
    <%= attachment_image_tag(a.object, :file, :fill, 75, 75) %>

    <%= a.input :_destroy, as: :boolean, label: 'Remove' %>
  </div>
<% end %>
```

**Comment by jnicklas** [comment]
You'd need to use something like Rails nested attributes or something. Or roll it yourself. There's no built in way to do this.
