### ISSUE TITLE
Problem with multiple files with a space in more then one of the files in filename. 

### ISSUE THREAD

**Issue by tcast** [refile/refile#307]
When uploading multiple files to S3 I started to get this error. 
Aws::S3::Errors::NoSuchKey 

 The specified key does not exist.

In debugging, i found that it only occurs when i have more then one file selected, and one of the files has a space in the file name. 

For example:  photo.jpg, doc.pdf, test.mp3  all upload fine together. 

But - ‘my photo.jpg’, ‘my doc.pdf’, test.mp3 will throw the key error. 

However, i can upload multiple files where only ONE of the files has a space - if there are more than 1 with a space in the filename, the error occurs. 

In my database, i am storing the filename and extension, and I believe this problem started around the time I added those columns. 

I am using master on both refile and refile-s3

**Comment by abitdodgy** [comment]
I'm almost sure this related to #292. I suggest we close this and move the discussion there.

**Comment by jnicklas** [comment]
Was able to replicate it, and it seems that #292 indeed fixed it.
