### ISSUE TITLE
Handling soft deletes

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#309]
We're using a soft deletes module that overrides ActiveRecord's `destroy` method. Instead of deleting the record, a `deleted_at` column is updated with a timestamp. Refile still calls `delete!` internally leaving the soft deleted file without an attachment. This can be a nasty surprise for those unaware of this behaviour.

See [line 44 in `lib/refile/attachment/active_record.rb`][1].

It's easy to solve this with a custom method, but it's worth leaving this issue out here for others. Maybe this should be configurable?

[1]: https://github.com/refile/refile/blob/20ecdb3d760b8eed2d5f4bddf6dd8c673063bf2c/lib/refile/attachment/active_record.rb#L44

**Comment by janko-m** [comment]
I was thinking of the exact same feature recently, I need it when saving serialized copies of a record (snapshot), that in case the original gets deleted, the deserialized snapshot still shows the image.

I think the best place for this configuration is the [attachment definition](https://github.com/refile/refile/blob/master/lib/refile/attachment_definition.rb), just to add one more keyword argument.

**Comment by jnicklas** [comment]
I was totally sure we had an option to switch off deletion of files, but it seems there isn't one. Weird.

**Comment by shanemcd** [comment]
Does anyone have any recommendations for a workaround until this is resolved? I have tried `skip_callback :destroy, :after` with no luck.

**Comment by shanemcd** [comment]
Update. I was able to hack around this by doing:

```ruby
attachment :file
define_callbacks :destroy
```

**Comment by abitdodgy** [comment]
I have a pull request for this. https://github.com/refile/refile/pull/333

I don't expect it to be merged since it might be low quality, but I would welcome feedback from those involved in this issue.

**Comment by abitdodgy** [comment]
Closing in favour of #362

**Comment by tyleramos** [comment]
Looks like this issue was closed over a year ago, but this has not made it into a release yet.  The latest gem version 0.6.2 does not include this fix.  Any plans to release a new version of the gem?

**Comment by abitdodgy** [comment]
@tyleramos my pull request was merged here: https://github.com/refile/refile/pull/362

**Comment by tyleramos** [comment]
@abitdodgy Thanks for the quick response!  I noticed that it was merged into master but this has not been released as a ruby gem yet.  https://rubygems.org/gems/refile shows the latest version 0.6.2 was created in October but this was merged in November.  Any plans to release a new version of the ruby gem?

**Comment by abitdodgy** [comment]
@tyleramos that's for @jnicklas to decide, but this repo has been quiet for months. I'm sure @jnicklas is very busy, but it would be great to hear from him on what he has in mind going forward.
