### ISSUE TITLE
Process file before save

### ISSUE THREAD

**Issue by 1dot44mb** [refile/refile#311]
Hi,

I am using refile successfully, thanks for the great gem.

Users upload recorded audios from their mobile phones, which comes as _amr_ filetype. I would like to implement a functionality to the server side, which checks the uploaded file, if it is _amr_ it will run the ffmpeg command to convert it to mp3 and store the mp3 (not the uploaded amr file). So that i can play it to the users later.

I know the conversion, etc should be made in another gem, i can do that. What i want to learn is; how to hook to "after_upload" of refile so i can run my own code just before it saves and give it the converted file rather than the uploaded file.

Is the model's "before_save" suitable for this?

Thanks.

**Comment by 1dot44mb** [comment]
Please keep in mind that i can not make this like image conversion. Because it converts upon request. And converting video or audio files upon each request will not be suitable in comparison to converting them just once and serving the converted file later.

**Comment by jnicklas** [comment]
Yes, the before_save hook is what you want. If you're using ActiveRecord you can check whether the file has changed so you don't reprocess unnecessarily using `previous_changes`.

**Comment by 1dot44mb** [comment]
Thanks for the answer.

I wonder when does Refile move the file from "Cache" to "Store"? Is it after successful save of model? (after_save?). I also wonder if there is a possibility to override or monkey path the exact place that refile moves the file from cache to permanent store?

Regards.

**Comment by masonmark** [comment]
Using Refile's `attachment` method to extend your model causes Refile to also add a `before_save`  callback to trigger its own behavior for storing attachments. Therefore, the order in which you add your own behavior using `before_save` is important.

My app manages mechanical drawings, and the canonical originals are PDF documents, but the web UI needs JPEG preview images for those too. So, somewhat similar to what @1dot44mb wants to do above, I wanted to generate and store those additional JPEG representations (as Refile attachments) at save time. (So unlike @1dot44mb, I am not **replacing** the attachment, but I am **adding** additional attachments.)

This first code below doesn't work, because Refile is adding its own before_save callbacks **before** I add mine. So they get executed first, triggering the actual storage of the Refile attachments... so then adding additional attachments in my before_save callback has no effect, because those don't get stored by Refile. 

```ruby
class Drawing < ActiveRecord::Base
  has_one :drawing_number
  belongs_to :drawing_set

  attachment :canonical_pdf_representation
  attachment :small_jpg_representation

  before_save {PDFThumbnailer.update_jpg_previews self}

  # ... THIS DOES NOT WORK
```

Changing the order like this fixes it:

```ruby
class Drawing < ActiveRecord::Base
  has_one :drawing_number
  belongs_to :drawing_set

  before_save {PDFThumbnailer.update_jpg_previews self} 
  # ... This works, because it means the above before_save 
  # callback will execute before Refile's before_save callbacks
  # that get added by invoking the attachment method below:

  attachment :canonical_pdf_representation
  attachment :small_jpg_representation

  # ...
```

Per the [Rails documentation about how callbacks are ordered](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html), the ordering is slightly convoluted, but there are also options like :prepend which might be an alternative to actually ordering the code differently. 

For me, it was easier to just add my own before_save callbacks that affect Refile attachments before having Refile add its own.

**Comment by 1dot44mb** [comment]
@masonmark Thank you for the great feedback.

So, in "before_save" the attachment is uploaded to the cache but is not persisted to store right? So i can just do file operations and move my file to store?

**Comment by masonmark** [comment]
In Refile's [own before_save callback](https://github.com/refile/refile/blob/20ecdb3d760b8eed2d5f4bddf6dd8c673063bf2c/lib/refile/attachment/active_record.rb#L40), which it sets up when you use the `attachment` macro-style method in your model, Refile calls [Attacher#store!](https://github.com/refile/refile/blob/20ecdb3d760b8eed2d5f4bddf6dd8c673063bf2c/lib/refile/attacher.rb#L121).

I didn't actually step through it in byebug, but it looks like that is where Refile actually does the "persist the attached file to permanent storage" work. So I think that `before_save` callback is, in fact, where the attachment gets persisted.

But, if you make sure your own `before_save` callback executes before Refile's  (e.g., by registering your own callback first, as in my previous comment), then I think you can do anything you want to the file attachment at that point, and Refile can still handle all the actual persisting-it-to-permanent-storage work for you. E.g., something like:

```ruby
class MyCoolModelObject

  before_save {
    path_to_mp3 = MyCoolAudioConverter.make_mp3_from_amr_file_somehow()
    
      File.open(path_to_mp3, "rb") do |file|
        self.audio_recording = file
      end
  }

  attachment :audio_recording

  # ...
```

That way you are replacing the attached .amr with the .mp3 version you created, but still leaving all the rest of the work up to Refile. I think that way it should still work whether using the filesystem, S3, or other Refile backend.

**Comment by 1dot44mb** [comment]
@masonmark and @jnicklas Thank you very much for your help. I have achieved what i want. Here is my code in case anyone needs it in the future.

What i do is simply; hook `before_save` of my model (which has the attachment attribute) and check if the file in the cache (that is just about to be saved) is ".amr or .3gp" type. If it is; i run the external ffmpeg command to convert it to mp3 and if the conversion is successfull; i replace the previous file with the newly converted file by simply just setting "attachment" attribute of the model (in my case, it is `file`). 

As @masonmark pointed out; the `before_save` hook must be called before `attachment`.

Thanks again @masonmark .


    before_save :audio_to_mp3
    
    attachment :file

    def audio_to_mp3
		_file = self.file_filename
		_extension = File.extname(_file)
		_name = File.basename(_file, _extension)
		_path_to_mp3 = "/tmp/#{_name}.mp3"

		if [".3gp", ".amr"].include? _extension
			# Convert to MP3
			conversion_result = system("ffmpeg -i '#{Refile::cache.directory}/#{self.file.id}' -f mp3 -y '#{_path_to_mp3}' 2>&1")

			# If command finished successfully and output file exists; assign it to this model's file attribute
			if $?.success? && File.exists?(_path_to_mp3)
				File.open(_path_to_mp3, "rb") do |file|
					self.file = file
				end
			end

		end

**Comment by mmplisskin** [comment]
Thank you @masonmark and @jnicklas this is very helpful. I am trying to do something similar with this great gem. Users upload multiple files, if they are zip then they are extracted and the .wav sounds are converted to mp3 for preview, all formats need to be saved. I am a little bit confused as to how to add multiple attachments to the model. 

@masonmark Do you mind showing some of your code for this action? 
{PDFThumbnailer.update_jpg_previews self} 

Thanks.

**Comment by mmplisskin** [comment]
Got it thanks to a little bit of pair coding and trial and error. 
```
.....
if $?.success? && File.exists?(_path_to_mp3)
           File.open(_path_to_mp3, "rb") do |file|
            self.tablename.new(file: file)
           end
        end
...
```
