### ISSUE TITLE
Display direct uploaded image before saving the associated model

### ISSUE THREAD

**Issue by samflores** [refile/refile#312]
I'm using the direct upload approach and trying to display the uploaded image by creating and inserting an image element on the `upload:success` event. It seems there's no way to create the URL on the client because of the token part.

`/attachments/:token/cache/:id/:filename`

The `id` is available in the event object and the `filename` really don't matter.

Am I missing something or is this really impossible?

**Comment by samflores** [comment]
Forgot to mention I'm using `refile master (0.5.5 0dc2072)` and `Rails 4.2.3`.

**Comment by Menghongli** [comment]
@samflores There is a method called `file_url(Refile.store.get(id))` might be useful for this case
https://github.com/refile/refile/blob/0dc2072a90020c940102b099387c34297f89b321/lib/refile.rb#L248

**Comment by samflores** [comment]
I know the method, but it would require a trip to the server. After reading `refile.js` and the `Refile` class ( specially the `file_url` and `token` methods) I assume there's no client-only way to create the url, given I wouldn't let the client know the `secret_key`.

**Comment by jnicklas** [comment]
There is no way to generate an image URL client-side, if you're running on master. If you're doing a direct upload you can use the HTML5 file api to extract a data URL from the file and display that as an image source. It's fairly easy to do. That saves you the round-trip.
