### ISSUE TITLE
How to resize Image ?

### ISSUE THREAD

**Issue by kenshero** [refile/refile#313]
I am newbie Rails . I use Refile upload image to S3 . Very cool to upload but I don't know resize image. I search and see ImageProcessor to resize . But I don't know how to use ImageProcessor . Can you help me ?  

Sorry .I'm bad english.

**Comment by abitdodgy** [comment]
It's in the API documentation and the Readme.

https://github.com/refile/refile#4-rails-helpers

For example, 

```erb
<%= attachment_image_tag(@user, :profile_image, :fill, 300, 300) %>
```

**Comment by kenshero** [comment]
@abitdodgy  
No. Now I use <%= attachment_image_tag(@user, :profile_image, :fill, 300, 300) %> already.

I mean resize while upload image . because if not resize when show image that image cannot show full image.   Image cut some part

**Comment by kenshero** [comment]
@abitdodgy  
OK  Thank . I change  "fill" to "fit" and work .

**Comment by chrishough** [comment]
Thoughts on adding https://github.com/refile/refile/pull/452 @abitdodgy

**Comment by abitdodgy** [comment]
@chrishough I'm afraid it's not up to me (we should probably be glad :laugh:). @jnicklas is the maintainer of Refile.

**Comment by chrishough** [comment]
ahh nice.  @jnicklas you may want to check out that PR it is great for the project.
