### ISSUE TITLE
How to define Max_Size refile ?

### ISSUE THREAD

**Issue by kenshero** [refile/refile#314]
I want to Upload image to S3 . And I need to define Max_Size image 800kb . 
I see Code " Refile.cache = Refile::S3.new(max_size: 10.megabytes, ...) ". But I don't know how to use.
I add in refile.rb . but still can upload .   Can you help me please ?

**Comment by abitdodgy** [comment]
Yes, add it to `refile.rb`.

```ruby
Refile.cache = Refile::S3.new(prefix: "cache", max_size: 10.megabytes, **aws)
```
Note that this will only apply to the cache, but that may not matter since Refile works by copy from `cache` to `store`, so files go to cache first. Alternatively, add it to the aws options hash defined earlier.

```ruby
aws = {
  access_key_id: "xyz",
  secret_access_key: "abc",
  region: "sa-east-1",
  bucket: "my-bucket",
  max_size: 10.megabytes
}
Refile.cache = Refile::S3.new(prefix: "cache", **aws)
Refile.cache = Refile::S3.new(prefix: "store", **aws)
```
