### ISSUE TITLE
Convert process doesn't work

### ISSUE THREAD

**Issue by musaffa** [refile/refile#316]
```ruby
attachment_image_tag(resource, :image, :convert, 'jpg')
attachment_url(resource, :image, :convert, 'jpg')
```
Convert process cannot change the internal type of the image files. Other processes like `:fill`, `:limit` work just fine. If I use `format: 'jpg'` with `:fill`, for example, it just changes the image extension without changing the image type itself. But the [code](https://github.com/refile/refile-mini_magick/blob/master/lib/refile/mini_magick.rb#L134) is intended to change the image type when the format is set. In a nutshell, `img.format (.....)` in `refile-mini_magick` doesn't work with `refile`.

I'm using the master branches of `refile` and `refile-mini_magick`.

**Comment by janko-m** [comment]
From what I can see, the code simply calls `MiniMagick::Image#format`, which is supposed to do the conversion. Can try to see if the problem is in MiniMagick?

**Comment by musaffa** [comment]
MiniMagick is fine:
![screenshot from 2015-08-02 00 25 56](https://cloud.githubusercontent.com/assets/294616/9023032/315ae7ec-38ad-11e5-9fd5-15756edefced.png)

**Comment by musaffa** [comment]
@janko-m @jnicklas I think I've found the problem. We can instantiate image with either `MiniMagick::Image.new` or `MiniMagick::Image.open`. But the `new` method works differently than `open`. If the file name provided in the parameter doesn't have any extension, the image instantiated with `new` method cannot convert the image type. In case of `open`, it works whether file name have any extension or not.

So in the [refile-mini_magick](https://github.com/refile/refile-mini_magick) gem, if I change the [new](https://github.com/refile/refile-mini_magick/blob/master/lib/refile/mini_magick.rb#L133) method with `open`, `convert` process starts working as expected.

I've also tested this in the [spec file](https://github.com/refile/refile-mini_magick/blob/master/spec/refile/mini_magick_spec.rb#L8). If I change from:
```ruby
let(:portrait) { Tempfile.new(["portrait", ".jpg"]) }
```
to:
```ruby
let(:portrait) { Tempfile.new("portrait") }
```
It fails with `new` but works perfectly with `open`.

**Comment by janko-m** [comment]
@musaffa Great work! Would you be kind enough to submit a PR to refile-mini_magick?
