### ISSUE TITLE
undefined method `accepts_attachments_for' for #<Class:0x007fdd28d01c88>

### ISSUE THREAD

**Issue by saferamirez** [refile/refile#318]
I have a error in line where I add accepts_attachments_for. 

```ruby
class Room < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  has_many :facilities
  has_many :Preferences

  accepts_attachments_for :photos, allow_destroy: true

  validates :location, presence:true
  validates :country, presence:true
  validates :city, presence:true
  validates :description, length: { minimum: 10}
  validates :price, presence:true
end

class Photo < ActiveRecord::Base
  belongs_to :room
  attachment :image

end
```

**Comment by jcuenod** [comment]
I can confirm. Running master branch. The error is

    undefined method `accepts_attachments_for'

**Comment by fjeansilva** [comment]
When it 'll be available function? I get the same error.

**Comment by abitdodgy** [comment]
@fjeansilva it's already available on the master branch.

**Comment by MrBrownser** [comment]
Hi, I'm using refile-mongoid gem, and it depends on refile 0.5 version, as we can see in the gemspec file:
    gem.add_dependency "refile", "~> 0.5"
How can I change this dependency to match the master branch where 'accepts_attachments_for' is available please? Does it makes sense?

**Comment by jnicklas** [comment]
@MrBrownser master branch is still on `0.5.5`, you don't have to change anything.

I'm working through issues now after a long absence, hopefully I'll be able to release a new version soon.
