### ISSUE TITLE
Portrait Photos Auto Rotating to Landscape

### ISSUE THREAD

**Issue by CPHollister** [refile/refile#323]
When a new photo is uploaded it auto rotates to landscape. Has anyone else experienced this? 
As seen below:
![screen shot 2015-08-11 at 7 50 54 pm](https://cloud.githubusercontent.com/assets/3248568/9215653/5ad602ac-4062-11e5-8a78-d3e415883509.jpg)

Gemfile
gem "refile-s3"
gem 'refile', require: "refile/rails", git: 'https://github.com/refile/refile.git', branch: 'master'
gem "refile-mini_magick"

Show.html.erb
<%= attachment_image_tag(image, :file, :fill, 600, 600, class: 'img-responsive') %>

**Comment by dummied** [comment]
Mind posting the image in question? I have a suspicion ... 

(Spoiler: some cameras use `exif::orientation` to "set" the orientation. ImageMagick can auto-orient, but I don't think mini_magick uses it by default)

**Comment by jnicklas** [comment]
I think the problem is rather that the image is *not* autorotating. That is the image actually is in landscape, but has EXIF metadata which rotates it into portrait, and Refile is not reading that metadata. See: https://github.com/refile/refile-mini_magick/issues/1
