### ISSUE TITLE
storing images to s3 - what am i missing please?

### ISSUE THREAD

**Issue by aceroks** [refile/refile#327]
I'm using this code in config/initializers/refile.rb

require 'refile/s3'

aws = {
  access_key_id: ENV['access_key_from_s3'],
 secret_access_key: ENV['secret_key_from_s3'],
 region: "us-west-2",
 bucket: ENV['my-bucket'],
}
Refile.cache = Refile::S3.new(prefix: "cache", **aws)
Refile.store = Refile::S3.new(prefix: "store", **aws)

I have also tried other suggestions using:
require 'refile/backends/s3' on top and the following on bottom:
Refile.cache = Refile::Backends::S3.new(prefix: "cache", **aws)
Refile.store = Refile::Refile.store = Refile::Backends::S3.new(prefix: "store", **aws)

I even dragged and dropped my images, they only show in productions on my development/production laptop. Heroku sweeps out the Dynos so I need to store images on s3 and can't for the life of me connect the dots to get it to work. Can you help, gratede it's a trivial blog app I am learning Rails with but I decided to use Refile for image upload capability and it works great on my laptop, nowhere else. Help, if you got some time to kill.
Steve

**Comment by jnicklas** [comment]
This may be a stupid question, but have you:

1) Created an amazon account and generated credentials for it
2) Created a bucket in the appropriate region
3) Set this configuration as environment variables (`heroku config:set` I think on Heroku)
4) Logged into the production console of your app to verify that this configuration is indeed set.

**Comment by jnicklas** [comment]
Have not heard back from OP. Closing.

**Comment by aceroks** [comment]
I apologize for not responding. I missed  your response and had basically given up on the issue. I had done 1 & 2 of your list but not 3 & 4. I will try that. Thanks very much.
