### ISSUE TITLE
Assigning from a data URI?

### ISSUE THREAD

**Issue by erikdahlstrand** [refile/refile#328]
Hi,

Is it possible to assign from data uris?

Something like this? It would be really useful.

```
user.profile_image_url = "data:image/png;base64,iVBORw0KGgoA..."
```

**Comment by jnicklas** [comment]
No, there is no way to do this out of the box, but it should be fairly simple to add some kind of method to do this. I don't think it's generally useful enough to warrant inclusion in the gem itself though.
