### ISSUE TITLE
Question: commits missing from 0.5 releases

### ISSUE THREAD

**Issue by carlost** [refile/refile#329]
In the past few months a lot of MRs have been accepted into master and have not been included in a refile release (0.5.5, 0.5.4 etc).  For example:  https://github.com/refile/refile/pull/126

Is the expectation that those commits won't be included in a release until 0.6.x?

Carlos

**Comment by jnicklas** [comment]
My intention was to finish a 1.0 release, but I don't think I am comfortable with calling the current state of the gem 1.0, so I'll see if we can push a new version in the meantime, but there are a couple of issues with multiple file uploads which need to be fixed first.

**Comment by jnicklas** [comment]
And no, none of these changes will be backported to 0.5, there'll be a 0.6 release with those new features.

**Comment by carlost** [comment]
-> there'll be a 0.6 release with those new features.

Thanks for the update ... and the gem :smile:
