### ISSUE TITLE
Using refile with Globalize gem

### ISSUE THREAD

**Issue by partydrone** [refile/refile#330]
I have a Rails 4.2 project using the Globalize 5.0 gem with a `Download` object:

```ruby
class Download < ActiveRecord::Base
  belongs_to :download_type
  has_and_belongs_to_many :products

  attachment :file

  translates :title, :part_number, :file_id, :file_filename, :file_size, :file_content_type

  validates :title, presence: true
  validates :file, presence: true

  def to_param
    "#{id}-#{title.parameterize}"
  end
end
```

Everything seems to work fine. Translated fields are saved in the `download_translations` table created by Globalize—including the `file_id`—and the file is uploaded.

The problem is when I upload a file for a new locale, the new information is saved in `download_translations`—along with the new `file_id`—but the _previous_ file is deleted from the store.

So at any given time, I can have data in the database for multiple versions of a file based on locale, but out of all those, only _one_ file exists in the file store—the last file uploaded.

It would be great if files are only deleted from the file store when a translation is deleted.

**Comment by jnicklas** [comment]
Globalize still exists? I used that like eight years ago. Funny.

As I recall it does some pretty evil monkey patching of all sorts of things. You're going to have to dig a bit to figure out what's going on.

**Comment by jnicklas** [comment]
I don't really think I can help with this question, so I'm closing it. Try asking on StackOverflow.
