### ISSUE TITLE
Can’t get image to display once uploaded to S3

### ISSUE THREAD

**Issue by hydrozen** [refile/refile#331]
I successfully uploaded a file to my S3 bucket (I checked and its there) but when I use the rails helper to display the image:

```<%= attachment_image_tag(image, :file, :fill, 300, 300) %>```

it only ouputs the id of the file without an image tag or anything. Am I missing something? Also, what’s the name of the backend when using refile-s3? I wanted to access the sinatra endpoint directly to see if I could see the image but I don’t know what to put as the backend. I tried refile-s3 and s3 and both times I get this in the console:

Refile::App: Could not find backend: refile-s3
Refile::App: Could not find backend: s3

**Comment by jnicklas** [comment]
You should probably put either `store` or `cache` as the backend names. I don't know why you're not seeing the image, your code looks correct. Maybe something else is interfering with the `attachment_image_tag` method?

**Comment by hydrozen** [comment]
It’s a vanilla rails app that I created just to test that. But good news, this morning it works and I didn’t change anything O_o. I really don’t understand what was going on last night... maybe the s3 bucket was taking some time to get setup properly or something?

**Comment by jnicklas** [comment]
Sometimes CORS takes a while to start working, that's the only thing I can think off, other than that it should work. Anyway, seems like you're good now, so I'll close this.
