### ISSUE TITLE
Filesystem backend moving files from cache to store come up empty

### ISSUE THREAD

**Issue by jph** [refile/refile#339]
When I upload via Refile, using default Filesystem backends, in Rails 4.2, the file appears in the cache (tmp/uploads/cache), then when the model instance is saved (persisted to active record) the resulting object in the store/ directory has a filesize of 0 bytes.

I've searched around heaps for any info, can't find anything. Any point in the right direction would be appreciated.

I did some quick testing, and Refile itself can most definitely see the empty file, and it is presented through the browser no problem... But just empty.

Deliberately invalid ID:
```
17:22:20 web.1         | Refile::App: Could not find attachment by id: 8c75d4a122365fd3db7dd2d346294ef970ec45778540a109a9e65e9245d1
17:22:20 web.1         | Refile::App: [2015-09-01 17:22:20 +1000] GET "/store/8c75d4a122365fd3db7dd2d346294ef970ec45778540a109a9e65e9245d1/m.png" 404 1.0ms
```

Valid ID that was just uploaded:
```
17:22:28 web.1         | Refile::App: [2015-09-01 17:22:28 +1000] GET "/store/8c75d4a122365fd3db7dd2d346294ef970ec45778540a109a9e65e9245d0/m.png" 200 1.9ms
```

Ruby 2.1.1p76
Rails 4.2.1

Relevant lines from Gemfile.lock
```
    refile (0.5.3)
      mime-types
      sinatra (~> 1.4.5)
    refile-mini_magick (0.1.0)
      mini_magick (~> 4.0)
      refile (~> 0.5)
```

**Comment by jnicklas** [comment]
This is very strange. I haven't seen this kind of bug before. I imagine you can't find a way to reproduce this? I have no idea where to even begin looking for a solution to this, so your best bet is digging through  what happens inside Refile and where it loses the data.

**Comment by jph** [comment]
Absolutely. It may be my environment, I'm running on a pretty hacked Debian box. I will do some debugging and report back with anything I find in case it ever comes up in other places.

**Comment by jph** [comment]
Hi there @jnicklas, I've done some further testing on this and I'm only seeing this bug in one part of my app. There are a couple of other places where I'm uploading files that this isn't happening, so I'm going to assume it's my implementation rather than anything within refile.

Thanks for the comments. You can close this issue now.

**Comment by To1ne** [comment]
I am having the same problem. This is the table I've got:

```ruby
  create_table "documents", force: :cascade do |t|
    t.integer  "attachment_id"
    t.string   "attachment_filename"
    t.integer  "attachment_size"
    t.string   "attachment_content_type"
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end
```

And this is the model:
```ruby
class Document < ActiveRecord::Base
  attachment :attachment
end
```

I am calling:
```ruby
attachment_url(Document.first, :attachment)
```

Which generates something like: `/attachments/3032fe9feddddd4d341eeb26d35ab40a6466c4e6/store/2554/ArtieZiff.gif`

But when I visit it, I get the error:
>Refile::App: Could not find attachment by id: 2554

The strange thing I am seeing, in the `public/upload` I find a file with a totally different name than the hashed path of the url (I am not sure if it should be the same?).

**Comment by To1ne** [comment]
Ah (annoyed grunt), `attachment_id` should be a `string` not an `integer`.

Carry on...
