### ISSUE TITLE
Text file busy @ unlink_internal

### ISSUE THREAD

**Issue by Vaporizd** [refile/refile#340]
Hi,

I'm having an issue with refile and vagrant using synced folders. The issue is that whenever i try to save a file the following error occurs: 

Errno::ETXTBSY (Text file busy @ unlink_internal - /vagrant/vidya/tmp/uploads/ca
che/2dcd0c3fd391985ffe88ea30d826890c817fe64756f5fb6c92408368caa0):

Here's the full stack trace http://pastebin.com/TaUn9eJW 

This however works in the vagrant guest if it isnt within the synced folders. I used carrierwave to test if it would fail as well, it however didn't and carrierwave works fine with synced folders.

Is there anything that refile does that keeps that file busy?

**Comment by jnicklas** [comment]
We try to be diligent about cleaning up file descriptors which is the only thing I can think of. I don't know enough about virtualization to help out with this one, I'm afraid.

**Comment by tquill** [comment]
I'm having the same issue using VirtualBox with Windows 7 as the host, and Ubuntu 14.04 LTS as the guest.

From a bit of googling, it seems the issue may be caused when Windows is the host.  Still looking for a work around while still using a shared folder

**Comment by douglaslise** [comment]
On StackOverflow there is a solution setting the store to another folder instead of the project's root `tmp`, so the files aren't synced with the host:
http://stackoverflow.com/a/32400433/298004

**Comment by sobrinho** [comment]
Closing, I also don't know enough about virtualization to debug this further.

Feel free to open a PR if you find the solution.
