### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by crunchycarrot** [refile/refile#341]
After upgrading to latest version 4.3, It works really well! But only one things, the attachment image is no longer displayed, I got "error" message
![screen shot 2015-09-03 at 3 10 57 pm](https://cloud.githubusercontent.com/assets/14013234/9653527/21c1497e-524e-11e5-9410-8ff1ddb6c2a1.png)

Can you help?

**Comment by jnicklas** [comment]
Have you checked the log?

**Comment by jnicklas** [comment]
Closing. Please check the log for the error message.

**Comment by crunchycarrot** [comment]
Yes, solved, thank you
