### ISSUE TITLE
How to remove attached files when there are more than one?

### ISSUE THREAD

**Issue by whereismushfiq** [refile/refile#344]
<%= form_for @post do |form| %>
  <%= form.label :images_files %>
  <%= form.attachment_field :images_files, multiple: true %>
<% end %>

How do i remove images for this case?  I'm using  append :true .
class Image < ActiveRecord::Base
  belongs_to :post
  attachment :file
 end

class Post < ActiveRecord::Base
  has_many :images, dependent: :destroy
  accepts_attachments_for :images, attachment: :file, append: true
 end

Controller:

def post_params
  params.require(:post).permit(images_files: [])
end

**Comment by jnicklas** [comment]
This is out of the scope of the Refile gem. There are plenty of ways to remove records, the easies being a link to a controller action which call destroy on it, but what you go with depends on what you need.

**Comment by Axxiss** [comment]
@jnicklas could it be possible to handle multiple deletion on refile? 

Perhaps something like this:
- define an `attr_acessor` for attachers (Post in this case)
- add `after_update` callback to delete selected attachments (Images)

User still have to handle how to the attachment list and gather which ones to delete.

If you think its doable I can send a PR with an initial draft.

**Comment by erikdahlstrand** [comment]
@whereismushfiq I guess you want to remove images by editing the parent Post?
I thought accepts_attachments_for was a wrapper around accepts_nested_attributes_for and it would accept the parameter ```allow_destroy: true```. But it doesn't seem to be the case.

I solved it by adding accepts_nested_attributes_for

```
accepts_attachments_for :images
accepts_nested_attributes_for :images, allow_destroy: true
```

```
= simple_form_for @post do |f|
  = f.simple_fields_for :images do |c|
    = c.input :_destroy, as: :boolean
  = f.button :submit
```

```
params.require(:post).permit(
  :name,
  :_destroy,
  images_files: [],
  images_attributes: [:id, :_destroy]
)
```

**Comment by mmplisskin** [comment]
I have been trying to do this with rails forms in an edit action and managed to get it to sort of work with a nested route but unfortunately it destroys all images. Any help would be appreciated. 

```<% @event.images.each do |image| %>
      <%= image_tag attachment_url(image, :file, :fill, 450, 200, format: "jpg") %>
      <%= link_to "Image", attachment_url(image, :file) %>
      <%= link_to "Remove", event_image_path(@event, image.id), :method  => :delete, :confirm => "Are you sure?" %>
    <% end %>
```

**Comment by whereismushfiq** [comment]
Thanks guys. I actually did the same thing as max. Used nested route and
added a remove button.

Sincerely,
MUSHFIQ

**Comment by mmplisskin** [comment]
@whereismushfiq 
Cool. Were you able to get it to only delete the files individually or did it delete all of them?

**Comment by whereismushfiq** [comment]
I did that a month ago. As far as I remember i could delete one by one.
Could you do the same? I can check my code if you need that.

On Saturday, October 31, 2015, Max Plisskin <notifications@github.com>
wrote:

> @whereismushfiq <https://github.com/whereismushfiq>
> Cool. Were you able to get it to only delete the files individually or did
> it delete all of them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/refile/refile/issues/344#issuecomment-152693769>.
>


-- 
Sincerely,
MUSHFIQ
