### ISSUE TITLE
Testing direct file uploads?

### ISSUE THREAD

**Issue by dvrylc** [refile/refile#347]
Hi there, it's my first time using the Refile gem and I'm trying to write controller tests for my direct file uploads. Haven't had much luck thus far, anyone has tips? 

To be exact, I'm trying to test a POST action on the controller with an attached file handled by Refile. 

Thanks in advance! :smile:

**Comment by jnicklas** [comment]
Which part are you having trouble with?

**Comment by abitdodgy** [comment]
I had to wager, I would say how to stub a file upload in the controller. @dvrylc can you elaborate a bit more, please?

**Comment by Tensho** [comment]
+1

**Comment by Tensho** [comment]
@jnicklas Please refer me to the place where I can read about testing refile stuff.

**Comment by abitdodgy** [comment]
See issue #367 - but I've been doing something like this.

```
file = StringIO.new('hello')
file = Refile::Backend::FileSystem.new("tmp/uploads/cache").upload(file)
file_attributes = {
  id: file.id,
  size: file.size,
  filename: 'hello.txt',
  file_content_type: 'text'
}.to_json

post :foo, {
  file: file_attributes
}
```
