### ISSUE TITLE
Error when not using `multiple: true` in attachment_field

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#348]
In my application I have an automatic versioning feature where a `Document` object has many `Version` objects. From the `documents#show` I want to enable the user to upload a new version of the document. 

``` ruby
class Document < ActiveRecord::Base
  accepts_attachments_for :versions, append: true
end
```

Here's the form.

``` slim
  = form_for [@project, @document] do |f|
    = f.attachment_field :versions_files, presigned: true, host: request.base_url
    = f.submit
```

In this case I want the user to upload one file at a time, so I decided to omit the `multiple: true` option. However, the object was not being updated. After looking at the logs, I found that `strong_parameters` was filtering the `versions_files` param.

```
Unpermitted parameter: versions_files
```

But the parameter is whitelisted, so I figured its type validation is failing.

``` ruby
# documents_controller.rb
@document.update! permitted_attributes(@document)
```

``` ruby
class DocumentPolicy < ApplicationPolicy
  def permitted_attributes
      [:status, :phase, :file, versions_files: []]
  end
end
```

I changed the `permitted_attributes` method to return `versions_files` as a symbol.

```
  def permitted_attributes
      [:status, :phase, :file, :versions_files]
```

Then I got this error:

```
ArgumentError in DocumentsController#update
```

From the stack trace, it looks like it's happening in `accepts_attachments_for`... I've omitted much of the stack trace because I don't think it's useful. I'll add it if it's needed.

```
/Users/Mohamad/.rvm/gems/ruby-2.2.0/bundler/gems/refile-973d4ad5617a/lib/refile/attachment/active_record.rb:99:in `partition'
/Users/Mohamad/.rvm/gems/ruby-2.2.0/bundler/gems/refile-973d4ad5617a/lib/refile/attachment/active_record.rb:99:in `block (2 levels) in accepts_attachments_for'
activerecord (4.2.3) lib/active_record/attribute_assignment.rb:54:in `public_send'
activerecord (4.2.3) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
```

I'm using master.

**Comment by jnicklas** [comment]
I think that Refile assumes that `versions_file` is an array, whereas from what I understand in your case it wouldn't be. IMO this case should be made to work. A PR would be fantastic!

**Comment by sobrinho** [comment]
I'm not sure about this one...

`versions_files` expects an array and accepting a File object is strange to me, although I see the use case.

@abitdodgy want to open a PR for that one?

**Comment by abitdodgy** [comment]
@sobrinho if we can put this on the back burner for a while longer, I would appreciate it. I need to go back and look at what I ended up doing to get around the issue.

**Comment by sobrinho** [comment]
@abitdodgy sure, I will keep this open for a while.

**Comment by sobrinho** [comment]
Closing in favor of #584.
