### ISSUE TITLE
Resize fallback image

### ISSUE THREAD

**Issue by anti-destin** [refile/refile#351]
Suppose that we specify a fallback image:

```
<%= attachment_image_tag(@user, :profile_image, :fill, 300, 300, fallback: "default.png") %>
```

Is there a simple way to resize the fallback image to the specified dimensions?

**Comment by jnicklas** [comment]
No, not really. Just create a fallback image in the dimensions you want.

**Comment by alexandremcosta** [comment]
Isn't this an issue? Would you accept a PR that fix this behavior, resizing the fallback image to the desired attachment size?
