### ISSUE TITLE
[question] Some downloaded file names appear with + signs instead of spaces

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#354]
I've not able to consistently reproduce this, but in some instances files are downloaded where spaces in their names are being replaced with `+` signs. This could be OS or browser dependent, or the way the file name is being encoded.

Has anyone come across such an issue? Does anyone have a more concrete idea as to what might cause this to happen?

**Comment by walterdavis** [comment]
If you want to be precise, a URL is not allowed to contain any spaces, so you need to start with your filenames -- make sure they are "legal" before you store the file. Rails parameterize helper will do this for you very intelligently, you just have to pop off the extension, run parameterize on the base name, and then put it back together.

Walter

**Comment by jnicklas** [comment]
We escape the filename to make sure it doesn't contain any characters which could be used for malicious purposes (like `../`), that's what you're seeing.

See: https://github.com/refile/refile/blob/master/lib/refile.rb#L315
