### ISSUE TITLE
Missing assets from gem package

### ISSUE THREAD

**Issue by garytaylor** [refile/refile#357]
Hi,
  I have just upgraded from 0.5.5 to 0.6 and included the refile-s3 gem and refile-mini-magick gems, however, the app/assets/javascripts/refile.js file is missing and my app is complaining as we use that for S3 direct file uploads.

I can see it in the repository though

Thanks

Gary

**Comment by monkbroc** [comment]
You can use the gem directly from GitHub until this is fixed.

`gem "refile", require: "refile/rails", github: "refile/refile"`

**Comment by fabn** [comment]
Found the same thing, caused  by https://github.com/refile/refile/commit/f457be8e5306971148145e07e6eec228a3569579

**Comment by jnicklas** [comment]
Damnit! Pushed 0.6.1 which fixes this.
