### ISSUE TITLE
Error when using mulitple:true, direct:true, (and/or) presigned:true in attachment field

### ISSUE THREAD

**Issue by andrewnick** [refile/refile#361]
I am getting a 'no implicit conversion of Fixnum into String' error when rendering a multiple image upload form and I am not sure why.

Here is the error

```
ActionView::Template::Error (no implicit conversion of Fixnum into String):
    144:   <div class="form-group">
    145:       <%= f.label :listing_attachments_files %>
    146:       <%= f.attachment_field :listing_attachments_files, multiple: true, direct: true %>
    147:   </div>
    148:   
    149:   <div class="form-group">
```

I am able to upload multiple images to and from amazon without the direct and/or presigned option. I also have a single image upload form in another section of the site that has direct and presigned set that is working well.

The listing_attachment model is 

```
class ListingAttachment < ActiveRecord::Base
	belongs_to :listing
	attachment :file
end
```

The relevant Listing model code is 

```
class Listing < ActiveRecord::Base

	has_many :listing_attachments, dependent: :destroy
  	accepts_attachments_for :listing_attachments

end

```

Thanks

**Comment by abitdodgy** [comment]
@andrewnick which version of the gem are you using?

**Comment by andrewnick** [comment]
refile (0.5.5 6c35ef8)
refile-mini_magick (0.1.0)
refile-s3 (0.1.0)

These are the refile related gems in my Gemfile

```
gem 'refile', require: "refile/rails", git: 'https://github.com/refile/refile.git', branch: 'master'
gem "refile-mini_magick"
gem "refile-s3"
```

**Comment by andrewnick** [comment]
Updated the gem to the latest version (refile 0.6.1) and problem solved!

Thanks for the hint. :+1:
