### ISSUE TITLE
NoMethodError: undefined method `cdn_host=' for Refile:Module

### ISSUE THREAD

**Issue by babaleo** [refile/refile#364]
I am getting the following error when deploying my application. It occurs during assets precompile.

`NoMethodError: undefined method 'cdn_host=' for Refile:Module`

I have set `Refile.cdn_host = "abc.cloudfront.net"` under config/initializers/refile.rb

Please help.

**Comment by sorentwo** [comment]
Which version are you using? From the history it looks like this was called `host` before 0.6.0.

**Comment by jnicklas** [comment]
Yes, `cdn_host` is the new name as of 0.6.0. See #301 for details.

**Comment by babaleo** [comment]
Yes I am on version 0.5.5. I will upgrade to 0.6.0. Thanks, much appreciated!

**Comment by acandael** [comment]
I tried to upgrade from refile 0.5.3 to 0.6.2 but when I restarted my Rails server I got this error:

/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/refile-0.6.2/lib/refile/backend/s3.rb:1:in `<top (required)>': [Refile]
        from /Users/acandael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'│the S3 backend has been extracted into a separate gem, see https://github.com/refile/refile-s3 (RuntimeError)

**Comment by jnicklas** [comment]
@acandael follow the instructions in the README, you'll need to add `gem "refile-s3"` as a dependency.

**Comment by acandael** [comment]
Hi jnicklas, I upgraded from refile 0.5.4 to 0.6.2
In my refile initializer I had to change the require statement from

require "refile/backend/s3"

to

require "refile/s3"

On my local machine everything works, but when I try to deploy the upgrade on the production server, I get the error:

    rake stderr: rake aborted!                                                                                                              │02          09:10:25 +0100
   NameError: uninitialized constant Refile::Backend::S3                                                                                     │
   /opt/www/adlit/releases/20151202081343/config/initializers/refile.rb:10


my initializers/reflle.rb looks like this now

    require "refile/s3"

    if Rails.env.production?
      aws = {
        access_key_id: ENV["AWS_ACCESS_KEY_ID"], 
        secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"], 
        bucket: "adlit"
      }

      Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
      Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)
     Refile.cdn_host = "//d1e4k3tmal57z3.cloudfront.net"
  end

do you know what could be the problem?

greetings,

Anthony

**Comment by acandael** [comment]
problems are fixed now, I had to make some changes in the refile.rb initializer file and upgrade from rails 4.2.2 to 4.2.3

my initializers/refile.rb looks like this now

    require "refile/s3"
    if Rails.env.production?
      aws = {
        access_key_id: ENV["AWS_ACCESS_KEY_ID"], 
        secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"], 
        region: "eu-west-1",
        bucket: "adlit"
      }
      Refile.cache = Refile::S3.new(prefix: "cache", **aws)
      Refile.store = Refile::S3.new(prefix: "store", **aws)
      Refile.cdn_host = "//d1e4k3tmal57z3.cloudfront.net"
    end

I tested things and everything works, the images are accessed from Cloudfront and I can upload image to the S3 store.

One small caveat I'm still facing is that the preview image is broken in the upload form.

Not sure at the moment what's causing this.

greetings,

Anthony
