### ISSUE TITLE
Remove must_revalidate in Cache-Control header

### ISSUE THREAD

**Issue by fabn** [refile/refile#365]
It is completely useless because refile cannot revalidate files against `If-None-Match` headers (or `If-Modified-Since`) without reprocessing the whole file.

Even if refile could validate conditional requests I think that it's against the main purpose of this gem, i.e. to have autoexpiring urls. If the file change (because of different processor parameters) its url will be different and if one needs to expire all of them can do that by changing `Refile.secret_key` to invalidate all cached urls.

You can implement what has been suggested in [this comment](https://github.com/refile/refile/issues/209#issuecomment-97127401) or (better) completely remove it.

The right set of headers for refile app in my opinion would be 

```
Cache-Control: public, max-age=31536000
Expires: Sat, 17 Sep 2016 17:10:49 GMT # dynamically generated with 1.year.from_now
```

In this way all browsers and intermediate caches can safely cache anything that is returned by refile.

**Comment by jnicklas** [comment]
Good suggestion, I have no idea why it was there in the first place. I've removed it and released a new version.
