### ISSUE TITLE
Suggestion to add a project wiki

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#368]
A lot of tickets are being opened for very similar issues, most commonly:

1. Issues stemming from not running the latest version of the gem. #364, #361, #318, and more.
2. Issues related to manipulating images, like resizing and cropping. #351, #323, #313, and more.
3. Issues related to documentation and features, like `strong_params`, S3, `accepts_attachments_for`, removing attached files, etc... #344, #334, and more.
4. Caching, Heroku, etc...

@jnicklas I know how you feel about wikis, but I would be happy to take responsibility for a Refile wiki and keep it updated. What do you think? We could, instead, improve the documentation in the README, but it would be hard to include this much information and keep the README nice and compact.

**Comment by jnicklas** [comment]
Sorry for the late reply once again @abitdodgy. I'm finding myself with less time to devote to this than I'd like.

I'd honestly rather have more documentation. GitHub makes it pretty sane to split out documentation into separate files, so we could have separate files for these things. I've yet to see a wiki which isn't full of outdated or downright incorrect information, and I don't have the time or energy to garden a wiki.

With documentation within the repository there's a higher impetus to keep it up-to-date, and a chance to review the information before it gets added to keep out anything that's obviously wrong.

**Comment by abitdodgy** [comment]
I understand what you mean. If I understand you correctly, we can just add some markdown files with documentation or answers to FAQ. Sounds good to me. I'll close this.
