### ISSUE TITLE
Add documentation for features most frequently asked about

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#369]
Now that I've closed #368, I've updated this issue to suggest a list of things that would be useful to document.

It would be nice to document the following things since they're features most often asked about. This list is neither definitive nor in ranked in order of importance; these are my own suggestions based on what I've observed on the issue tracker.
- [ ] Running refile on a separate server, especially useful for those running their app on Heroku and suffer from performance issues.
- [ ] Showing image previews in JavaScript
- [ ] Manipulating images, like cropping and resizing.
- [ ] Setting up a CDN
- [ ] Removing attached files.
- [ ] Testing uploads

**Comment by andrewhavens** [comment]
@abitdodgy This is a good idea. I'm sure other people are trying to find a solution like me...what is the best practice for using Refile on Heroku? I have already set up Fastly as a CDN. Unfortunately, the performance is still really bad. I am already trying to "pre-cache" the images in the CDN by requesting the images in a background job. Unfortunately, this doesn't seem to help. What would you recommend to solve this issue?

**Comment by abitdodgy** [comment]
@andrewhavens I'm in the same boat as you are. There's a discussion on this topic in #229. I get the same errors frequently, and a high response time warning on every request that goes through Refile. I think the best way to deal with this is to have the CDN retrieve the files from S3 isntead of through the Refile app, but I don't know if this is possible.

Perhaps storing the S3 url in the database, and hitting that instead of Refile might work... but again, I'm not familiar with the internals of Refile to know if this works. I'd be interested to hear about any progress you make on this issue.

I've had other things on my plate, and since we've been able to trudge along even with those limitations, I've not looked into solving this issue.

**Comment by abitdodgy** [comment]
@andrewhavens another possiblity is to run Refile on a separate box with a bit more juice than a Heroku dyno... but I don't know how much extra plumbing we'd need for that to work.

**Comment by choonkeat** [comment]
Running an image server off a digitalocean box is good and cheap (and easy, if prepackaged as docker image). My own experience, albeit not refile, is that it can be a boot-up-and-forget thing.

However, refile rack app is currently too simplistic and will drown a small box when >1 request poke through the cdn/varnish/nginx layer

**Comment by abitdodgy** [comment]
@choonkeat I think a simpler solution might be to somehow store the S3 url and have the CDN bypass Refile. I don't know if that's possible.

**Comment by choonkeat** [comment]
@abitdodgy that works if the file stored in s3 is all you need, but it also defeats one of the advantage of refile (and [shrinerb](https://github.com/janko-m/shrine), [attache](https://github.com/choonkeat/attache)) which is the ability to use dynamically resized images in your app.

**Comment by abitdodgy** [comment]
@choonkeat that's true, although in our case we are using it for document and file storage, and we don't care about resizing (in most cases we don't, but we do in one case: user avatars).

**Comment by sobrinho** [comment]
Wiki is enabled now, feel free to create a page for the FAQ.

Thanks!
