### ISSUE TITLE
How to decrease image quality?

### ISSUE THREAD

**Issue by richardvenneman** [refile/refile#371]
Hi there,

We just converted an app from Paperclip attachments and it has worked wonderfully so far. One thing is that we have very large page headers for some objects. These can easily reach 2MB without compression.

Is there any recommended approach on decreasing the image quality of images? Paperclip allows for specifying `convert_options: { header: '-quality 70' }`. With Refile, must I write a custom processor which in turn calls the `:fill` processor?

Has anyone by chance compressed images with Refile before? Would love some help with this :)

**Comment by sebabouche** [comment]
:+1:

**Comment by molfar** [comment]
so how?

**Comment by aglushkov** [comment]
Take [this file](https://github.com/refile/refile-mini_magick/blob/master/lib/refile/mini_magick.rb) and create your processors with some improvements.

Or, you can make some monkey-patching :-)
This works for me with refile-mini_magick 0.2
``` ruby
module MyNamespace
  class ChangeQualityProcessors < Refile::MiniMagick
    def call(file, *args, **hash_args, &block)
      block = ->(cmd) do
        yield cmd if block_given?
        cmd.quality 10
      end

      super file, *args, **hash_args, &block
    end
  end
end
[:fill, :fit, :limit, :pad, :convert].each do |name|
  Refile.processor(name, MyNamespace::ChangeQualityProcessors.new(name))
end
```

**Comment by sidms** [comment]
Refile.processor :quality do |file|
  MiniMagick::Tool::Convert.new do |convert|
    convert << file.path
    convert.quality(60)
    convert << file.path
  end.call  
end

**Comment by karlclement** [comment]
@aglushkov Can you elaborate on where to place that file and when to call it?
