### ISSUE TITLE
Multiple files upload

### ISSUE THREAD

**Issue by optticall** [refile/refile#372]
Hi,

I'm doing multiple files upload and it seems to working fine, until the moment it should
appears in the browser... I don't know if I'm missing something.

what appears is:
File File File File File [#<Image id: 1, post_id: 2, file_id: "ff4321b8d6269b2b5dc7762027c815f60a136d3bb722b35869...", created_at: "2015-09-25 18:23:11", updated_at: "2015-09-25 18:23:11">, #<Image id: 2, post_id: 2, file_id: "2d6ebd5c21c33fd727265d08a75c90d62eeb75f6817ee60aee...", created_at: "2015-09-25 18:23:11", updated_at: "2015-09-25 18:23:11">, #<Image id: 3, post_id: 2, file_id: "c1296b0768ff3034c16847c96f41321b7a079e3b8ee1151d65...", created_at: "2015-09-25 18:23:11", updated_at: "2015-09-25 18:23:11">, #<Image id: 4, post_id: 2, file_id: "fa8855773b7fa3d95483186d596c12c747e5f466e09be8993a...", created_at: "2015-09-25 18:38:28", updated_at: "2015-09-25 18:38:28">, #<Image id: 5, post_id: 2, file_id: "b653eace2ab2d8ab4575ce62e73acc3a05813e40ad3dded0b6...", created_at: "2015-09-25 18:38:28", updated_at: "2015-09-25 18:38:28">] 

Here is my view code:

post.html.erb
<%= @post.images.each do |img| %>
	<%= image_tag attachment_url(img, :file, :fill, 150, 150) %>
<% end %>

Models:
Image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  attachment :file
end

class Post < ActiveRecord::Base
	validates :title, :content, :presence => true
	has_many :images, dependent: :destroy
	accepts_attachments_for :images, attachment: :file, append: true
end

Post Controller
def post_params
   params.require(:post).permit(:title, :content, :slug, images_files: [])
end

**Comment by richardvenneman** [comment]
Looks good to me, but in any case you should remove the `=` from the each loop directive:

```ruby
<% @post.images.each do |img| %>
```

Are you getting errors in the resources panel of your web inspector?

**Comment by optticall** [comment]
I did another try and its ok now. I don't know why it didn't work at first time =\
