### ISSUE TITLE
Refile.js progress reporting issues using S3 presigned backend

### ISSUE THREAD

**Issue by doxxon** [refile/refile#374]
I'm using refile.js v0.6.1 together with S3 backend in presigned configuration.

Uploading works fine, but for larger files >3MB the progress reporting seems to be off. After the progress hits approx 52%, the upload snaps to 100%.

Works "as expected" for smaller <200 kb files

Anyone able to reproduce?

**Comment by jnicklas** [comment]
We just proxy on the progress as reported by the browser, I don't think there's much we can do about this kind of problem.

**Comment by doxxon** [comment]
ok thanks
