### ISSUE TITLE
Easier way to access main url

### ISSUE THREAD

**Issue by JoshuaNovak919** [refile/refile#376]
There should be an easier way to access the main url for an image/file. For example I should be able to call `@user.profile_image.url` in the controller instead of having to use `Refile.attachment_url(@user, :profile_image)`. It would be especially helpful for when you are using files like pdfs etc and don't ever need to change the size etc.

**Comment by abitdodgy** [comment]
Why not just build a wrapper method in your class?

```ruby
def profile_image_url
  Refile.attachment_url(self, :profile_image)
end
```

**Comment by JoshuaNovak919** [comment]
I could, but that seems a bit redundant to have to do that for each model that has an attachment i'd say.

**Comment by abitdodgy** [comment]
It's easy enough to write a module and include it in any classes that define attachments.

**Comment by jnicklas** [comment]
It already exists ;) https://github.com/refile/refile/blob/master/lib/refile/attachment.rb#L87-L89
