### ISSUE TITLE
Validate OCG PDF files

### ISSUE THREAD

**Issue by pawel2105** [refile/refile#377]
Hey

Is there any way to check whether a PDF file has OCG [1] and add validation to prevent those files from being uploaded?

[1] http://www.planetpdf.com/developer/article.asp?ContentID=focus_on_pdf_layers_ocg_

The only way I've found to differentiate between a PDF without additional OCG layers, and one with layers is to check for a node labelled `stRef:originalDocumentID`:

    > cat pdf_with_layers.pdf | grep stRef:originalDocumentID
    >> <stRef:originalDocumentID>uuid:65E6390686CF11DBA6E2D887CEACB407</stRef:originalDocumentID>

    > cat pdf_without_layers.pdf | grep stRef:originalDocumentID
    >>

**Comment by walterdavis** [comment]
Are you trying to do this on the browser, before the file is actually uploaded? Or on the server, after it has been uploaded but before it has been permanently stored?

Walter

**Comment by pawel2105** [comment]
@walterdavis Preferably in the server. I could probably use JS to validate it client-side.

**Comment by jnicklas** [comment]
I think you'd need to do this server side. There isn't anything build in per-se which allows you to do this, but implementing it yourself shouldn't be hard. Just add a validation which checks for the tag in the file.
