### ISSUE TITLE
Show image exactly after uploading

### ISSUE THREAD

**Issue by asiniy** [refile/refile#378]
Hi there!

Refile allows me to upload images to the site asynchronously.

```
<%= form.attachment_field :profile_image, direct: true %>
```

Is there any ready boilerplate code which show how to show images to user exactly after uploading (With no waiting to submit a form),

**Comment by sebabouche** [comment]
Actually there is… but I can't manage to make it work :(

As referenced here https://github.com/refile/refile/issues/312, the idea is to use ReadAsDataURL.

My form field (using simple_form) is: 
    = f.input :image, as: :attachment, direct: true
And my jquery script (using coffee script) is:
  $(document).on("upload:start", "form", (e) ->
    $(this).find("input[type=submit]").attr("disabled", true))

  $(document).on("upload:complete", "form", (e) ->
    if(!$(this).find("input.uploading").length)
      $(this).find("input[type=submit]").removeAttr("disabled")

      preview = $('.img-card')
      file = $('#card_image').files[0]
      reader = new FileReader
    
      reader.onloadend = ->
        preview.src = reader.result
    
      if file
        reader.readAsDataURL file
      else
        alert "Arrrrrrrrgh. Empty…"
        preview.src = ''  )

**Comment by asiniy** [comment]
@sebabouche 

This one works for me

``` ruby
$ ->
  $(document).on 'upload:start', 'form', (e) ->
    renderImage e.target

  renderImage = (fileField) ->
    # generate a new FileReader object
    reader = new FileReader
    # inject an image with the src url

    reader.onload = (event) ->
      theUrl = event.target.result
      $(fileField).closest('.sortable').find('.rightpane img').attr('src', theUrl)

    # when the file is read it triggers the onload event above.
    reader.readAsDataURL fileField.files[0]
```

**Comment by jnicklas** [comment]
It would be somewhat nice to have some kind of widget in Refile which does this out of the box, but I suspect that it's going to require a lot more JavaScript code than I'd be comfortable adding. Especially since we do not want to depend on jQuery, and event delegation without a library is still somewhat painful.

I've done pretty much exactly what @asiniy did in an application and it works very nicely, so it's not particularly hard to implement on your own.
