### ISSUE TITLE
Sometimes the image json posted is "{}"

### ISSUE THREAD

**Issue by lephyrius** [refile/refile#380]
I want to make the user upload multiple files. So I'm using cocoon. 
https://github.com/nathanvda/cocoon

The problem is that sometimes then JSON that should look like this:
`{"id":"7c0f42f667737c5b49694fb1ff220c3209b70ba968c08bc7105001aedfa","filename":"5.png","content_type":"image/png","size":4101555}`
Becomes:
`{}`
I have verified that the file is correctly uploaded by showing a preview of the image. Is there a way to "trigger" the transfer from the JS? I know this is a bug but as a temporary solution. I will now search for a solution of my own and post it here if I find it. :smile_cat:

**Comment by lephyrius** [comment]
The root of the problem is definitely that in cocoon the JS doesn't generate a new "data-reference" attribute. So when it refers to the hidden field then it's refering just to the last element:
https://github.com/refile/refile/blob/master/app/assets/javascripts/refile.js#L29-L30
Because every element is the same. 
I don't know how to "solve" this. But I probably do some editing when adding a new nested attribute in Cocoon. 
Maybe change it to search for siblings or search in parent of the file input field would solve this? Hmmmm...
Do you really need the data-reference? Couldn't you just refer to previous hidden input sibling?
Lot's of idea and I don't know what is the ideal.

**Comment by lephyrius** [comment]
This seems to work. If you replace:
https://github.com/refile/refile/blob/master/app/assets/javascripts/refile.js#L29-L30
With:
`var metadataField = input.previousElementSibling;`
I really don't know if that's the "correct" solution because it seems a bit more brittle if you want to customize it a bit. The data-reference seems like a much more robust solution but it's a complicated one.

**Comment by jnicklas** [comment]
No, that doesn't work. When Rails encounters a form error it will wrap the field in an error div, getting the previous sibling is not a reliable way to get the hidden field, unfortunately. Neither is the name, since the same form could occur multiple times on the same page.

**Comment by jnicklas** [comment]
The `data-reference` thing is a pretty bizarre hack I'll admit, but I can't think of any other way to implement this that isn't completely unreliable. For strictly valid markup, the `id` field would work, but I suspect that it's going to cause lots of problems, because people are not diligent about keeping their markup valid, and it's very easy to generate duplicated ids.

I suspect that running Refile inside Cocoon is a somewhat edge use case, so I'd rather prefer to keep the better behaviour for the majority case.

Do you have any other ideas how this could be fixed?

**Comment by choonkeat** [comment]
if we pretend we only need to solve this for cocoon... then adding our own `data-reference` can be done during

``` javascript
$(document).on('cocoon:after-insert', function(e, insertedItem) {
  // do things
});
```

**Comment by jnicklas** [comment]
Closing this. I don't think we can solve this in a better way than we currently do.
