### ISSUE TITLE
delete files

### ISSUE THREAD

**Issue by chamini2** [refile/refile#382]
I've set up the uploading just fine, but I want to give the option to users to remove the uploaded file and when they use that option, I want to really remove it from disc.

How should I do this?

**Comment by abitdodgy** [comment]
In ActiveRecord, Refile will automatically delete the file from disc once the object has been destroyed. For that to happen callbacks need to be run, so you must use `object.destroy` and not `object.delete`. There's an open patch #362  to customise this behaviour, but it has not been merged yet.

**Comment by chamini2** [comment]
I wanted to delete only the file, not the model containing it. But your link helped me find the solution, I user `user.picture.delete`, where `user` has an *attachment* `picutre_id`, I also had to set the `user.picture_id` to `nil`.

**Comment by mmplisskin** [comment]
I think this would be a great option for those of us doing backups so we can just store file_id and backup images in s3.
