### ISSUE TITLE
It can save an image on a specific folder in a bucket ?

### ISSUE THREAD

**Issue by felipewmartins** [refile/refile#385]

**Comment by abitdodgy** [comment]
I don't think so. Refile is flat by default. You can choose a bucket, and a folder within that bucket, but your uploads will always go to that location.

**Comment by abitdodgy** [comment]
See this issue. https://github.com/refile/refile/issues/139

**Comment by taylorbrooks** [comment]
@abitdodgy @jnicklas Rather than opening a new issue, I figured I would comment here.

Instead of saving to a specific folder, is it possible to save different uploads to different S3 buckets? Or is Refile expecting to use one bucket per application?

**Comment by abitdodgy** [comment]
I'll defer to @jnicklas on this, but since you set the bucket in the intializer I imagine it's a single bucket per app. Perhaps you could change buckets at run time, but I don't know enough about the internal workings so say more.

**Comment by taylorbrooks** [comment]
I think this #390 is related. I'm going to move this convo over there.
