### ISSUE TITLE
Files lose reference on deploy with Capistrano

### ISSUE THREAD

**Issue by chamini2** [refile/refile#386]
When I do `cap production deploy` all the profile pictures of my users lose the hash reference and show broken image icons.

What can I do to fix this?

**Comment by chamini2** [comment]
I am using the `FileSystem` backend, I don't know if that may be the problem

**Comment by sorentwo** [comment]
@chamini2 Using the `FileSystem` backend would certainly be the underlying cause of the problem. You need to make sure that the directory you are writing to is shared between capistrano deploys. If you aren't writing to one of the shared/linked directories then you'll loose all of the uploads between each deployment.

I'd highly recommend hosting your images off of the file system if at all possible. For hobby or light usage S3 won't cost you anything.

**Comment by chamini2** [comment]
Ok, that is the problem, I tried to solve this by using the [`refile-postgres`](https://github.com/krists/refile-postgres) backend, but that didn't work either.

After making the change to postgres, I got the following error:

    I, [2015-10-28T23:27:25.945292 #2928]  INFO -- : Started GET "/attachments/store/fill/300/300/17404/picture" for 190.72.228.163 at 2015-10-28 23:27:25 -0400
    E, [2015-10-28T23:27:25.975233 #2928] ERROR -- : Refile::App: Error -> SSL connection has been closed unexpectedly

    E, [2015-10-28T23:27:25.987871 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-postgres-1.1.3/lib/refile/postgres/backend.rb:87:in `exec_params'
    E, [2015-10-28T23:27:25.988127 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-postgres-1.1.3/lib/refile/postgres/backend.rb:87:in `exists?'
    E, [2015-10-28T23:27:25.988271 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-0.5.5/lib/refile/backend_macros.rb:11:in `block (2 levels) in verify_id'
    E, [2015-10-28T23:27:25.989350 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-0.5.5/lib/refile/file.rb:53:in `exists?'
    E, [2015-10-28T23:27:25.989449 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-0.5.5/lib/refile/app.rb:113:in `file'
    E, [2015-10-28T23:27:25.989544 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-0.5.5/lib/refile/app.rb:52:in `block in <class:App>'
    E, [2015-10-28T23:27:25.989669 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
    E, [2015-10-28T23:27:25.989749 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
    E, [2015-10-28T23:27:25.989819 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
    E, [2015-10-28T23:27:25.989888 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
    E, [2015-10-28T23:27:25.989995 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
    E, [2015-10-28T23:27:25.990088 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
    E, [2015-10-28T23:27:25.990183 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
    E, [2015-10-28T23:27:25.990256 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
    E, [2015-10-28T23:27:25.990327 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
    E, [2015-10-28T23:27:25.990439 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
    E, [2015-10-28T23:27:25.990530 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
    E, [2015-10-28T23:27:25.990623 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
    E, [2015-10-28T23:27:25.990721 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
    E, [2015-10-28T23:27:25.990864 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    E, [2015-10-28T23:27:25.990958 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    E, [2015-10-28T23:27:25.991047 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    E, [2015-10-28T23:27:25.991136 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
    E, [2015-10-28T23:27:25.991223 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
    E, [2015-10-28T23:27:25.991334 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    E, [2015-10-28T23:27:25.991413 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    E, [2015-10-28T23:27:25.991482 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    E, [2015-10-28T23:27:25.991568 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
    E, [2015-10-28T23:27:25.991647 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
    E, [2015-10-28T23:27:25.991739 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/refile-0.5.5/lib/refile/custom_logger.rb:14:in `call'
    E, [2015-10-28T23:27:25.991828 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    E, [2015-10-28T23:27:25.991902 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    E, [2015-10-28T23:27:25.991982 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    E, [2015-10-28T23:27:25.992082 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    E, [2015-10-28T23:27:25.992183 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    E, [2015-10-28T23:27:25.992278 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    E, [2015-10-28T23:27:25.994326 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    E, [2015-10-28T23:27:25.994492 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    E, [2015-10-28T23:27:25.994594 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
    E, [2015-10-28T23:27:25.994909 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
    E, [2015-10-28T23:27:25.994998 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:51:in `serve'
    E, [2015-10-28T23:27:25.995071 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
    E, [2015-10-28T23:27:25.995140 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
    E, [2015-10-28T23:27:25.995228 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
    E, [2015-10-28T23:27:25.995323 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
    E, [2015-10-28T23:27:25.995411 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
    E, [2015-10-28T23:27:25.995504 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
    E, [2015-10-28T23:27:25.995612 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
    E, [2015-10-28T23:27:25.995736 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
    E, [2015-10-28T23:27:25.995816 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
    E, [2015-10-28T23:27:25.995886 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
    E, [2015-10-28T23:27:25.995984 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
    E, [2015-10-28T23:27:25.996080 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
    E, [2015-10-28T23:27:25.996155 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
    E, [2015-10-28T23:27:25.996224 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
    E, [2015-10-28T23:27:25.997980 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
    E, [2015-10-28T23:27:25.998132 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
    E, [2015-10-28T23:27:25.998210 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
    E, [2015-10-28T23:27:25.998299 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    E, [2015-10-28T23:27:25.998374 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
    E, [2015-10-28T23:27:25.998460 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
    E, [2015-10-28T23:27:25.998552 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
    E, [2015-10-28T23:27:25.998627 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
    E, [2015-10-28T23:27:25.998714 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
    E, [2015-10-28T23:27:25.998806 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
    E, [2015-10-28T23:27:25.998897 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
    E, [2015-10-28T23:27:25.998988 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
    E, [2015-10-28T23:27:25.999085 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    E, [2015-10-28T23:27:25.999160 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
    E, [2015-10-28T23:27:25.999258 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
    E, [2015-10-28T23:27:25.999386 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
    E, [2015-10-28T23:27:25.999495 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    E, [2015-10-28T23:27:25.999575 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    E, [2015-10-28T23:27:25.999726 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
    E, [2015-10-28T23:27:25.999807 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
    E, [2015-10-28T23:27:25.999895 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    E, [2015-10-28T23:27:25.999991 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
    E, [2015-10-28T23:27:26.000083 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
    E, [2015-10-28T23:27:26.000197 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
    E, [2015-10-28T23:27:26.000274 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
    E, [2015-10-28T23:27:26.000775 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
    E, [2015-10-28T23:27:26.003276 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
    E, [2015-10-28T23:27:26.003425 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
    E, [2015-10-28T23:27:26.003510 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
    E, [2015-10-28T23:27:26.003603 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
    E, [2015-10-28T23:27:26.003936 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    E, [2015-10-28T23:27:26.004023 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
    E, [2015-10-28T23:27:26.004112 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
    E, [2015-10-28T23:27:26.004204 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
    E, [2015-10-28T23:27:26.004294 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
    E, [2015-10-28T23:27:26.004421 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
    E, [2015-10-28T23:27:26.004528 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
    E, [2015-10-28T23:27:26.004651 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
    E, [2015-10-28T23:27:26.004764 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
    E, [2015-10-28T23:27:26.004880 #2928] ERROR -- : Refile::App: /home/deploy/apps/defensores/shared/bundle/ruby/2.2.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'


Do you know how I can fix this? or maybe how to go back to `FileSystem` backend and then fix the path.

**Comment by jnicklas** [comment]
Capistrano has a feature called shared directories, if you google for Capistrano and file uploads you should be able to find something. As for the postgres backend, it looks like you have some SSL issue, this could be due to a problem with the certs you have installed on the machine. I can't really help you with that, and I doubt it's related to Refile.
