### ISSUE TITLE
Upgrade from 0.5.x to 0.6.x

### ISSUE THREAD

**Issue by wafiq** [refile/refile#388]
Is there any release notes for the 0.5.x to 0.6.x?

I tried to upgrade the gem, but it appears that all the old images that were generated from previous version are broken. In the readme, the newer version will have a token generated to each files.

    GET /attachments/:token/:backend_name/:id/:filename

So how do I regenerate all files with the token digest? Or I just have to configure `Refile.secret_key` and it will automatically regenerate?

**Comment by jnicklas** [comment]
See: https://github.com/refile/refile/blob/master/History.md

**Comment by jnicklas** [comment]
Also, you shouldn't have to regenerate anything, unless you've cached the URLs to the files somewhere, which is something you shouldn't do. You might see a spike in traffic due to CDN misses as you upgrade though.

**Comment by mrsweaters** [comment]
@jnicklas I'm serving assets over an api in a microservices-style architecture. In my case caching the url is a must, as I don't have access to the helper methods in the other applications. Is there a way to selectively sign these requests so that it is backwards compatible?

**Comment by mrsweaters** [comment]
@jnicklas If I use the same secret key in the other apps and implement this method:
https://github.com/refile/refile/blob/master/lib/refile.rb#L451

I should be able to determine the correct hash of the file. Do you think this is possible? I'm concerned that `OpenSSL::Digest.new("sha1")` may return different values on different servers.

**Comment by mrsweaters** [comment]
@jnicklas I feel as though this tokenization should still be optional. I'm opening this issue back up because I don't see any easy way to migrate to 0.6.x.
