### ISSUE TITLE
Cache files between form submits without the input

### ISSUE THREAD

**Issue by sobrinho** [refile/refile#391]
When you submit a file and a validation error is presented, if you don't call `attachment_field` the file is lost.

I believe it is the hidden field generated by this method which keeps the cache between submits but I don't want to show the input again to the user if the file is already there, see the image.

<img width="1135" alt="screen shot 2015-11-03 at 14 42 35" src="https://cloud.githubusercontent.com/assets/26460/10914341/265b92e4-8239-11e5-93ba-020982986485.png">

What I've done is this:

``` erb
<tr class="nested-fields">
  <td>
    <%= f.input :id, as: :hidden %>

    <% if f.object.file %>
      <div style="display: none">
        <%= f.attachment_field :file %>
      </div>

      <%= link_to f.object.file_filename, attachment_url(f.object, :file) %>
    <% else %>
      <%= f.attachment_field :file %>
    <% end %>
  </td>

  <td class="text-right">
    <%= link_to_remove_association "Remover", f, class: 'btn btn-sm btn-danger' %>
  </td>
</tr>
```

Would be nice to have some kind of helper like `f.attachment_cache :file` to be able to keep the cache without rendering the file input itself.

Makes sense?

**Comment by jnicklas** [comment]
I think this would be sensible. Basically we should add a public API for the hidden field.

**Comment by sobrinho** [comment]
Great, I will try a patch at the end of the day.
