### ISSUE TITLE
refile s3 attachment_url with special characters 403 forbidden

### ISSUE THREAD

**Issue by duncangarde** [refile/refile#393]
Refile and attachment_url is working perfectly in my project for filenames without special characters, but when encoded characters are introduced the attachment_url link gives 403 forbidden error. 

<b>link that works:</b>
.../attachments/9f26ce39cd5df338a11c03c6d1e560feae4d3b3e/store/151c39067d215aaeda4cdad3e5341fc76c1580a011e8ef70ca7fb8a4d2a5/Events+Flix+bs+conflicted+copy+2014-07-15.xlsx

<b>link that doesn't work:</b>
..../attachments/53e36a73afff91581f02d482485de5584aff3ab0/store/469e013ec7e6fe5facf0df554f2b6c4c1a0939ce8d10ed6e90412c0a54f6/Events+<b>%28</b>Flix+b<b>%27s</b>+conflicted+copy+2014-07-15<b>%29</b>.xlsx

if I take out the encoded characters then it works again. Any Clues?

**Comment by imgarylai** [comment]
I have meet a similar problem. I want to apply retinjs to my project. However, when I set filename as `image@2x.png`, I get `image%402x.png`.

**Comment by Eric-Guo** [comment]
Confirm if filename contain `(` it will be 403 from refile also.

**Comment by coreymartella** [comment]
Definitely related to the digest token validation, here's some logging I put into my local install with a file that has an `&` in its name

```log
time=2016-02-17T10:38:36.578354-05:00 severity=INFO    pid=44307 Started GET "/attachments/7380ef57869f5400d4e6a49f8cc7e106971493e5/store/61b22e616af3901ffaa9134ec2bbd05da9d1d461ea36077d13480b64caa5/2073+a+&+b.pdf" for 127.0.0.1 at 2016-02-17 10:38:36 -0500
time=2016-02-17T10:38:36.715835-05:00 severity=DEBUG   pid=44307 request.script_name: /attachments params[:token]: 7380ef57869f5400d4e6a49f8cc7e106971493e5
time=2016-02-17T10:38:36.716095-05:00 severity=DEBUG   pid=44307 request_path: /attachments/7380ef57869f5400d4e6a49f8cc7e106971493e5/store/61b22e616af3901ffaa9134ec2bbd05da9d1d461ea36077d13480b64caa5/2073+a+&+b.pdf base_path: /store/61b22e616af3901ffaa9134ec2bbd05da9d1d461ea36077d13480b64caa5/2073+a+&+b.pdf
time=2016-02-17T10:38:36.716345-05:00 severity=DEBUG   pid=44307 valid_token? path: /store/61b22e616af3901ffaa9134ec2bbd05da9d1d461ea36077d13480b64caa5/2073+a+&+b.pdf url_token: 7380ef57869f5400d4e6a49f8cc7e106971493e5 refile_token: a928fcf5ec20f6bdee4b7f4543e0e409fca904dc
time=2016-02-17T10:38:36.716553-05:00 severity=DEBUG   pid=44307 valid_token? expected_digest: 6a51a27f69373e36770fca62a9cfb93d4ea450b4 actual_digest: f799b566c3843ab44b3a30f7057fb9576ea2053b match: false
time=2016-02-17T10:38:36.719666-05:00 severity=INFO    pid=44307 Refile::App: [2016-02-17 10:38:36 -0500] GET "/7380ef57869f5400d4e6a49f8cc7e106971493e5/store/61b22e616af3901ffaa9134ec2bbd05da9d1d461ea36077d13480b64caa5/2073+a+&+b.pdf" 403 4.8ms
```

My suspicion is that the ordering of escaping + tokenizing in `file_url` needs to generate the token BEFORE the escaping, hope to look into this if I find some free time

https://github.com/refile/refile/blob/cbdd2a6dd718d62f18e22657cc169f520db6a424/lib/refile.rb#L315-L320

in the meantime a simple workaround is to provide your own url safe filenames to your attachment_url calls:

```ruby
#if you're using the metadata columns:
attachment_url(model, :attachment, filename: model.attachment_filename.parameterize)
#if you're using the metadata storage
attachment_url(model, :attachment, filename: model.attachment_attacher.basename.parameterize)
```

**Comment by Eric-Guo** [comment]
@coreymartella Thanks, it works, but notice it may better to using try for `parameterize`

```ruby
attachment_url(model, :attachment, filename: model.attachment_filename.try(:parameterize))
```

**Comment by RealSilo** [comment]
Guys, I'm using direct upload to S3. Once the image gets uploaded I'd like to display a preview in the form. I'm using js but get the same 403 forbidden error like you. Could you tell me how to do the workaround in the case of js? (I've checked my bucket/cache and bucket/store and files get uploaded properly)

`$(document).on("upload:success", ".product-refile-form", function(e) {
    if (!$(this).find("input.uploading").length) {
      $(this).find("input[type=submit]").removeAttr("disabled");
      $('#product-progresspercent').hide();
      var new_image_input = $('.btn-product-image input:first-child').val();
      var product_data = JSON.parse(new_image_input.replace(/'/g, '"'));
      var product_image_id =  product_data.id;
      var product_image_name = product_data.filename;
      var product_image_token = $('.btn-product-image input:first-child').data('reference');
      $("#new-image").html($("<img />").attr({src: "/attachments/" + product_image_token + "/cache/fill/80/80/" + product_image_id + "/" + product_image_name }));
      //$(".removecheck").show();
    };
});`

**Comment by Eric-Guo** [comment]
@RealSilo google `rails parameterize js equavalent` and [first](http://stackoverflow.com/questions/24849667/jquery-parameterize-string-like-parameterize-method-in-rails) and [second](https://gist.github.com/pjambet/3710461) solution not working?

**Comment by RealSilo** [comment]
@Eric-Guo, thanks for the answer! I'm gonna checkout today! (Since my question I've checked some other answers and the current version of refile doesn't have image preview. A guy recommended me to check this js solution instead: http://jsbin.com/uboqu3/1/edit?html,js,output)

**Comment by 90caiosantos** [comment]
@Eric-Guo hey man, where did i put this code? 

attachment_url(model, :attachment, filename: model.attachment_filename.try(:parameterize))

i'm newbie trying to do something great, can you help with that?

**Comment by Eric-Guo** [comment]
@90caiosantos just in your code, sorry not very clear, the model is just your ActiveRecord::Base/ApplicationRecord inherited model class instance. attachment is just the fields, attachment_filename is [meta field](https://github.com/refile/refile#additional-metadata)

**Comment by sobrinho** [comment]
I'm able to upload, download and show inline by using special characters like `@` and `)` by using Refile master.

Closing.
