### ISSUE TITLE
Silence logging in development.

### ISSUE THREAD

**Issue by mmplisskin** [refile/refile#395]
As a user that has images on s3 and does not retrieve them in dev it would be nice to be able to turn off error logging. I have tried the following in development.rb, not sure if this is the right approach... 

Refile.logger = false
Refile::App.logging = false 
Refile::CustomLogger = false

**Comment by jnicklas** [comment]
You definitely do not need to set `Refile::CustomLogger` to false. I think setting `Refile.logger = Logger.new(nil)` should do just fine.

**Comment by mmplisskin** [comment]
Thank you soo much! worked like this...

```
config.after_initialize do
  Refile.logger = Logger.new(nil)
end
```
