### ISSUE TITLE
Could not find refile-0.6.2 in any of the sources

### ISSUE THREAD

**Issue by lecabel** [refile/refile#397]
Hi, I followed the instruction but have the following error : Could not find refile-0.6.2 in any of the sources
I tried again with gem install rake --version='10.4.2' and later with bundle --deployment.
This last unfortunately leads to different error Could not find rake-10.4.2 in any of the sources
Any suggestion?
thanks Fabio

**Comment by abitdodgy** [comment]
Try removing Refile from your Gemfile (don't forget to run bundle). Then uninstall Refile and all its dependencies by running `gem uninstall refile` from the terminal. Remove other gems that depend on it. Finally, add it to your Gemfile and run bundle again.

**Comment by lecabel** [comment]
I think it was related to ruby version also. Now I have ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]. Anyhow now it works!
thanks
