### ISSUE TITLE
[Question] Any way to generate urls from javascript files?

### ISSUE THREAD

**Issue by ariffmunshi** [refile/refile#399]
Is there a way to generate urls for the direct uploaded files in cache via javascript? I just updated from 0.5 any my custom urls are now returning 403s. Seems like with the new signed system, a token is needed. Was using this before to load a thumbnail preview on "upload:success" before the image upload is saved. Thanks!

**Comment by jnicklas** [comment]
No, this is currently not possible. You will have to do a round-trip to the server to sign the urls. I've also run into this problem in an application, and it would be very nice if uploading the file would automatically return a signed URL.

**Comment by ariffmunshi** [comment]
Hmm.. alright will think about it or another way to solve this. But anyway, great job on the gem so far @jnicklas !

**Comment by jnicklas** [comment]
The way to solve this is to round trip to the server to generate the URL. I think this is somewhat unavoidable with the current architecture.

**Comment by RealSilo** [comment]
@jnicklas could you pls elaborate how you do this round trip to the server or provide a code sample?
