### ISSUE TITLE
refile and mailer

### ISSUE THREAD

**Issue by lecabel** [refile/refile#400]
I am using refile to upload documents. I have also to transmit documents as attachment in email.
How to add to mail as attachments? below it is not working
# attach files
      @revisions.each do |revision|
          mail.attachments[revision.file_filename] = revision.file
        end
thanks for any help
Fabio

**Comment by jnicklas** [comment]
I think you'd be better off asking this question on StackOverflow, I can't provide you with an answer without looking it up.

**Comment by jimknight** [comment]
I'm using postgres as my backend but you can see how to do it here by calling the backend manually

<pre>
  def send_email(email,current_user)
    @user = current_user
    @email = email
    if @email.copy_to.present?
      @copy_to = @email.copy_to + ",#{@email.project.email}"
    else
      @copy_to = @email.project.email
    end
    if @email.email_attachments.any?
      connection = lambda { |&blk| ActiveRecord::Base.connection_pool.with_connection { |con| blk.call(con.raw_connection) } }
      backend = Refile::Postgres::Backend.new(connection)
      @email.email_attachments.each do |ea|
        attachments[ea.file_filename] = backend.get(ea.file_id).read
      end
    end
    mail(from: @user.email, cc:@copy_to, to: @email.sent_to, subject: @email.subject)
  end
</pre>

**Comment by lecabel** [comment]
thanks jimknight!
same solution I have found.

unless @revisions.nil?
  @revisions.each do |revision|
      rev = revision.file.backend.get(revision.file.id).read
      mail.attachments["#{revision.file_filename}"] = rev
    end
 end
