### ISSUE TITLE
attachment_field is not populating with values after failed form validation

### ISSUE THREAD

**Issue by ctro** [refile/refile#408]
Hi.

I have an attachment_field, it looks like this:
`<%= f.attachment_field :assets_pictures, multiple: true, direct: true, presigned: true %>`
It generates hidden inputs as expected, and uploads to s3 as expected. However, when my form is submitted with intentional errors I lose the values previously selected for :assets_pictures. 

The same happens without :multiple, :direct, and :presigned options.

Ruby 2.2.4
Rails 4.2.5

Is this known to be working or not?  I'm not too sure where to start digging in.

Thanks!
-Clint

**Comment by abitdodgy** [comment]
@ctro are you whitelisting the parameters in the controller? That's what this sounds like.

**Comment by ctro** [comment]
@abitdodgy Thanks for looking.
I do have params whitelisted in the controller.  I notice there are 2 inputs: one hidden and one NOT hidden, named the same.  In my case the HTML inputs are named: `report[assets_pictures][]`.

In the controller I have
```
def report_params
    params.require(:report).permit({:assets_pictures => []})
end
```

So, I think the params _are_ whitelisted... Any other ideas? :)

**Comment by ctro** [comment]
Well, I think this issue was just an assumption on my part.  I got the impression that refile was going to re-set the value of my file upload fields, but this is forbidden for security reasons.  I see my previous values in `params` though, so I can work with that.  Thanks!
