### ISSUE TITLE
physical location of picture

### ISSUE THREAD

**Issue by stackaccount** [refile/refile#409]
I have installedrefile_example_app and it works fine. However, I am confused where it saves the picture, I mean physical location. 
http://127.0.0.1:3000/attachments/bb4589f4f8450b4b00086948a197c39f27d05596/store/fill/200/200/3ceda4ab78878a9fc5a8a691a555c2636724f530d94f7715e42d867e131b/5jjOL._SY220_.jpg

I could not find any folder name "attachments" in my PC. I m sooo confused!

**Comment by scarfacedeb** [comment]
@stackaccount Look at `Refile.store` directory.

**Comment by jnicklas** [comment]
It might help to read the README again. Refile does not work like other file storage solutions, the storage of the files is quite different.
