### ISSUE TITLE
Rails 5.0.0.beta1 compatibility

### ISSUE THREAD

**Issue by boblin** [refile/refile#410]
Hello,

I would like to use `refile` together with rails 5.0.0.beta1. After `bundle install` I get this error:
```
    rails (< 5.1, >= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
      railties (= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
        actionpack (= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
          rack (~> 2.x)

    refile was resolved to 0.6.2, which depends on
      sinatra (~> 1.4.5) was resolved to 1.4.5, which depends on
        rack (~> 1.4)
```

Is there any way how to use rails 5.0.0.beta1 with refile?

**Comment by twalpole** [comment]
Not currently -- there's some work to be done for rails 5 compatibility

**Comment by twalpole** [comment]
@bobdin  - take a look at PR ##411 to see how to get it running with rails 5

**Comment by atomn** [comment]
any news on merging #411?

**Comment by jnicklas** [comment]
#411 is merged :)
