### ISSUE TITLE
Asset Sync gem override refile s3 credentials

### ISSUE THREAD

**Issue by luxxi** [refile/refile#413]
Asset Sync gem override refile s3 credentials on frontend where i want to display image. The link to image isn't correct (bucket is set by asset_sync). 
On backend works fine, it uploads image to s3 and i could get it via console.

**Comment by choonkeat** [comment]
Please reconsider. Don't use asset_sync anymore https://devcenter.heroku.com/articles/please-do-not-use-asset-sync

**Comment by luxxi** [comment]
Thanks
