### ISSUE TITLE
Refile changelog?

### ISSUE THREAD

**Issue by SamLau95** [refile/refile#419]
First off, I'm a big fan of this gem. Thanks for working on it!

I have an app using refile `v0.5.5`. I notice that the [`README` for `v0.6.2`][readme] says to use `Refile.cdn_host`, whereas on `v0.5.5` `Refile.host` is used. Are other API changes like this documented somewhere? I've checked for a `CHANGELOG.md` file as well as in the Github releases.

[readme]: https://github.com/refile/refile/blob/cbdd2a6dd718d62f18e22657cc169f520db6a424/README.md#3-rack-application

**Comment by jnicklas** [comment]
https://github.com/refile/refile/blob/master/History.md
