### ISSUE TITLE
Use refile with polymorphic relation

### ISSUE THREAD

**Issue by mpakus** [refile/refile#420]
I'm not sure is it a bug or not, but it seems like `refile` can't handle polymorphic relations.

as example, I have 2 models:

```
class Picture < ActiveRecord::Base
  attachment :file, type: :image

  belongs_to :pictured, polymorphic: true
```
and
```
class Cleaning < ActiveRecord::Base
  has_many :pictures, as: :pictured
  accepts_attachments_for :pictures, append: true, attachment: :file
```
so now when I send request with `"cleaning"=>{"pictures_files"=>["[{\"id\":\"192538c7bbcb0d983c97e2d1bae2cc6c0cdbeaaf8f60fae56399ca54e0bf\",\"filename\":\"38.jpg\",\"content_type\":\"image/jpeg\",\"size\":299980}]"]}` 
I get error `No relation cleaning on Picture`

but of course, everything works when I replace `belongs_to :pictured, polymorphic: true` to `belongs_to :cleaning` but it's not what I want :)

Thanks for any your help and suggestions.

**Comment by jnicklas** [comment]
Why did you close this issue? Did you resolve the problem?

**Comment by mpakus** [comment]
yes, probably the problem was with counter_culture and after_save callback
