### ISSUE TITLE
Upload PDF, DOC & VIDEO using Refile

### ISSUE THREAD

**Issue by samsoft00** [refile/refile#424]
Great gem with Doc, please how can i upload PDF, DOC & VIDEO using Refile. 
Encounter this error while trying to upload Image to Amazon s3 on Win 8

```
Seahorse::Client::NetworkingError in RegistrationsController#update
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Thanks

**Comment by sobrinho** [comment]
This is an error related to SSL, not sure if it's related to Refile.

Closing due to the lack of activity, thanks!
