### ISSUE TITLE
There was an error while trying to load the gem 'refile/simple_form'. (Bundler::GemRequireError)

### ISSUE THREAD

**Issue by chrise86** [refile/refile#425]
For some reason (started happening after I removed Dragonfly from the Gemfile) I am getting the error:

```
There was an error while trying to load the gem 'refile/simple_form'. (Bundler::GemRequireError)
```

when booting the Rails server.

Gemfile:

```
gem 'rails', '4.2.5'
gem 'refile', require: ['refile/rails', 'refile/simple_form']
```

I've tried using from master with the same result. Obviously removing the require 'refile/simple_form' fixes the error on boot, but then I won't be able to use the simple_form helpers.

**Comment by mmplisskin** [comment]
Have you tried removing the require from the gemfile and using an initializer?

config/initializers/refile.rb

`require 'refile/simple_form'`

**Comment by jaredmoody** [comment]
I had this issue with Rails 5 and realized bundler had set my refile version to `0.3.0` to try and resolve a rack conflict with sinatra, and simple_form support was added in `0.6.0`. The solution proposed in #447 resolved this for me:

```
gem 'refile', github: 'refile/refile', require: ['refile/rails', 'refile/simple_form']
gem 'sinatra', github: 'sinatra/sinatra'
```

**Comment by chrise86** [comment]
I'm pretty sure this has been fixed since I opened it, so closing 👍
