### ISSUE TITLE
Images Won't Load When Page is Loaded From Turbolinks On First Page Load

### ISSUE THREAD

**Issue by ygamretuta** [refile/refile#426]
I may only be missing a page:load event for refile but I can't see it anywhere in the documentation. I host my images on s3. I click on a turbolink link and it does not load the images. refreshing the page loads the images.

What could I be missing? 

**UPDATE:**
Seems to only happen on first visit. Images are showing up after the subsequent visits to the page.

**Comment by sobrinho** [comment]
Closing due to the lack of activity.
