### ISSUE TITLE
Process the image before uploading in S3

### ISSUE THREAD

**Issue by anhnk** [refile/refile#435]
Please let me know if this feature already exists. I raise it here because I couldn't find it anywhere in the documentation.

I am looking for a way to process the images before uploading them to S3. For example, with the current setup I am having in my app, when a user uploads a big image to S3, that image will stay with the original quality/resolution. There are 2 pages in my app that show the image in 2 different sizes (200px x 200px and 80px x 80px). So whenever the page is opened, it takes a lot of time to load the image because it has to be processed (in this case resized) to a smaller size and this is done every time the page is opened.

Therefore it would be lovely to be able to process the image before the upload process. Specifically, resize the image to 200px x 200px and 80px x 80px and upload those 2 images to S3 and store the URLs in the database so I can use the URL for the image with the size I need.

Let me know if this can already be done in a different approach. Or if this feature is too much to ask because refile is meant to be a simple gem rather than a swiss army knife.

**Comment by 90caiosantos** [comment]
i'm trying to use jquery-file-upload but with no sucess, i'm trying to put my projet live but its impossible for users upload  2 or 3 MB photos with 3G Network =/

**Comment by aaroncass** [comment]
@anhnk this is by design. The idea is, you store the original file, and then serve it through the rack application, but with a HTTP cache so you only see the delay on the first page load.  From the readme:

> Important: Unlike other file upload solutions, Refile always streams your files through your application. It cannot generate URLs to your files. This means that you should always put a CDN or other HTTP cache in front of your application. Serving files through your app takes a lot of resources and you want it to happen rarely.

**Comment by anhnk** [comment]
Thanks for answering my question, @aaroncass !
