### ISSUE TITLE
conflict with rails 5 ActionCable

### ISSUE THREAD

**Issue by ifokeev** [refile/refile#437]
I got this: 

```
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta2/lib/active_record/dynamic_matchers.rb:21:in `method_missing': undefined method `accepts_attachments_for' for Product (call 'Product.connection' to establish a connection):Class (NoMethodError)
Did you mean?  accepts_nested_attributes_for
```

Then I googled this: 
http://stackoverflow.com/questions/32125234/extending-activerecordbase

Because of 
https://github.com/refile/refile/blob/800f4d0db4e3e1ab7e307a14b991ec641d8f503c/lib/refile/attachment/active_record.rb#L124

Solution is: 
remove `Rails.application.eager_load!` from `config.ru`
or you can add
`require 'refile/attachment/active_record'` in your models

It works!
I think you should know.

Also:
http://stackoverflow.com/questions/2328984/rails-extending-activerecordbase/2330533#2330533

**Comment by sobrinho** [comment]
I would prefer to see this line changed to or similar to:

```ruby
ActiveSupport.on_load(:active_record) do
  ActiveRecord::Base.extend(Refile::ActiveRecord::Attachment)
end
```

**Comment by sobrinho** [comment]
My mistake, this is already fixed on master: https://github.com/refile/refile/blob/2f9bce5e763dd71fa1b4532f235eb6af4da99488/lib/refile/rails.rb#L16-L18
