### ISSUE TITLE
Uploads filling user's /tmp directory

### ISSUE THREAD

**Issue by klappradla** [refile/refile#438]
First of all: thanks for this awesome library! Loving it!

I'm recently running into the problem that uploads fill up the user's `/tmp` directory with temporary files like:
```
[ec2-user@ip-172-31-27-101 tmp]$ ls
open-uri20160217-15375-1kxs5xi.gif  open-uri20160217-15375-2h40xm.gif   open-uri20160217-15375-uvrjzy.gif
open-uri20160217-15375-1s4vg4k.png  open-uri20160217-15375-gbynsa.jpeg
open-uri20160217-15375-1sziy9v.gif  open-uri20160217-15375-s875f6.gif
```
This quickly grows until *"No space left on device"*.

I'm using direct uploads to S3 with the following versions:
```
refile (0.6.2)
refile-mini_magick (0.2.0)
refile-s3 (0.2.0)
```
Could someone maybe give me a hint where these files come from / when they are created?

**Comment by blazeeboy** [comment]
@klappradla what was the problem root cause as I think I have the same problem

**Comment by klappradla** [comment]
Hey @blazeeboy I could not reproduce the problem anywhere else than on EC2 and having CloudFront in front of my app - and even there it happened kind of randomly. I ended up just adding a job to periodically clean up these files if they pile up.

**Comment by blazeeboy** [comment]
@klappradla yes same thing here, also made same solution, thank you
