### ISSUE TITLE
Add revise permission to attachment_path

### ISSUE THREAD

**Issue by otavioschwanck** [refile/refile#439]
I need to add authenticate_user! to route "/attachments/*"

I tried in application_controler with before_action and before_filter without success.

i created a function that get's request.env["PATH_INFO'] and verify if it start_with? '/attachments' .  If it, use's authenticate_user!.  I Did not succeed.  

How can i do this ?

**Comment by sobrinho** [comment]
Refile uses a Sinatra application and automount itself, the Rails stack itself is not used for it.

If you are using Devise, you can try disabling the automount and mount the route by using a constraint check, like this:

```ruby
# config/initializers/refile.rb
Refile.configure do |config|
  config.automount = false
end
```

And mount manually in your routes file:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    mount Refile::App.new, at: "attachments", as: :refile_app
  end
end
```

Like I said, `Refile::App` is a Sinatra application, so you can't use let's say Rails controllers for it.

But you can have constraints checks on your routes, like the Devise macro or something like this:

```ruby
authenticate :user, -> (user) { user.admin? } do
  mount Refile::App.new, at: "attachments", as: :refile_app
end
```
