### ISSUE TITLE
FileDouble not in a tagged version

### ISSUE THREAD

**Issue by jonesmac** [refile/refile#443]
I couldn't figure out why my tests could never access the Refile::FileDouble module referenced in the read me. Then I realized that the latest tagged release doesn't actually have it - https://github.com/refile/refile/tree/v0.6.2/lib/refile

Its clearly in [master](https://github.com/refile/refile/tree/master/lib/refile) but I wanted to know why it isn't present in the latest tagged release?  This is confusing since the readme that references FileDouble and says to add refile to your gem file as `gem "refile", require: "refile/rails" which pulls 0.6.2`.  But this will not actually give you the File Double module since its only in master.

Can we add a note in the readme file stating the master branch should be pulled if you want to use the FileDouble module for testing?

**Comment by olhor** [comment]
Thanks for sharing. Started to work after updating Gemfile with:
`gem "refile", require: "refile/rails", :git => 'https://github.com/refile/refile.git', :branch => 'master'`

**Comment by sdellis** [comment]
Any idea when this will be fixed in the tagged release?

**Comment by sobrinho** [comment]
We will be releasing a new version soon, keep using master until then. Thanks!
