### ISSUE TITLE
File upload to User model with ajax request in JSON / HTML5 FormData

### ISSUE THREAD

**Issue by igorpreston** [refile/refile#449]
Hello, 

I have defined attachment on ActiveRecord model and I am using React.js on front-end, so that file uploads should occur with ajax request.

How should I approach uploading a file in this case? I can send data both in JSON format:

```
{
  file: '...'
}
```

Or using HTML5 FormData API:

```
let formData = new FormData();
formData.append('file', file, file.name);
```

Please advise on best possible way to upload file to model with refile attachment using ajax request. What fields should I send in my JSON object or in FormData object to the Rails? (Note: I can't use your refile.js library.)

Thanks!

**Comment by sobrinho** [comment]
You can use the HTML5 FormData API.
