### ISSUE TITLE
reading filename with multiple file uploads

### ISSUE THREAD

**Issue by acandael** [refile/refile#450]
Hi, at the moment I'm trying to implement multiple document uploads. The model 'Tournament' has_many 'Documents'.

In the Show view I'm reading out the uploaded documents like this:

```
<% @tournament.documents.each do |doc| %>
  <%= link_to @tournament.document_filename, attachment_url(doc, :file) %>
<% end %>
```

But what I'm getting back is the document_id instead of the filename:

```
/attachments/c380563b5cdd7589524dd7eb67e2136de67f1d59/store/feca3a6972f8193b44ee520b22c4166b76145cbcf5020b6c675ec56da968/file /attachments/50cd5c3c8bd05fbb1550243cf1795041b5dd55ba/store/2b3f8822f26e8359c0b03f7356644870855c599bcbc31bf26dd7c77e73f5/file
```

Does someone know how to read out the filenames when working with multiple uploads?

Thanks for your help,

Anthony

**Comment by sobrinho** [comment]
You have to create a column named `file_filename` in your document model.

Alternatively, you can specify it manually by using `attachment_url(document, :file, filename: 'something')`.
