### ISSUE TITLE
0.6.2 is missing Refile::FileDouble

### ISSUE THREAD

**Issue by danielmackey** [refile/refile#451]
When attempting to use `Refile::FileDouble` with v0.6.2:

```
`require': cannot load such file -- refile/file_double (LoadError)
```

It appears that its in `master` but v0.6.2 was cut prior to its inclusion. 

If anyone else runs into this, update your Gemfile to pull from Github until the next version is released.

```
gem 'refile', require: 'refile/rails', github: 'refile/refile'
```

**Comment by thiagoramos23** [comment]
Do you know when it will be on a tagged version?

**Comment by chrishough** [comment]
Thank you for posting

**Comment by heeton** [comment]
When is the new version going to be cut?

**Comment by rodrigopinto** [comment]
@sobrinho I am facing the same problem mentioned here. I know It is a minor thing if compared to other issues, but I was wondering if it is possible to bump and release a new version of the gem to close this issue and to have new features like #518 available to use.

Thanks in advance.
