### ISSUE TITLE
undefined method object for nil class

### ISSUE THREAD

**Issue by sobrinho** [refile/refile#454]
Not sure what is happening, the exception message is weird.

```
  from active_record/attribute_assignment.rb:54:in `public_send'
  from refile/attachment/active_record.rb:27:in `block in attachment'
  from refile/attachment.rb:65:in `block (2 levels) in attachment'
  from refile/attacher.rb:77:in `set'
  from refile/attacher.rb:97:in `cache!'
  from refile/backend_macros.rb:31:in `block (2 levels) in verify_uploadable'
  from refile/s3.rb:66:in `upload'
  from refile/backend_macros.rb:11:in `block (2 levels) in verify_id'
  from refile/s3.rb:154:in `object'
```

Any idea?

The credentials are set and the bucket exists on s3, there is something else to configure?

Using the file storage it works, only when using s3 that the exception happens (production).

**Comment by sas1ni69** [comment]
@sobrinho any luck? I've run into the exact same thing. Rails 4.2.6, Ruby 2.3.0.

**Comment by sobrinho** [comment]
I've figured out that was a typo in my case.

I used `ENV["BUCKET_NAME"]` on the application but configured `S3_BUCKET_NAME` on the server.

In other words, the bucket name was nil but the error message wasn't clear.

**Comment by sas1ni69** [comment]
I used Settings.s3_bucket_name instead of Settings.s3.bucket_name. What are the odds. Thanks though.

**Comment by sobrinho** [comment]
I will make a pull request with a better error message soon, I will keep the issue open to remind me :)
