### ISSUE TITLE
Copy image from one model to another

### ISSUE THREAD

**Issue by grosser** [refile/refile#455]
x.image_id = y.image_id works fine until I delete x or y ... 
assigning x.remove_image_url = y.image_url results in `Image has an invalid file format` ...
any suggestions how to do this nicely (ideally with an s3 copy command instead of re-upload) ?

@jnicklas

**Comment by janko-m** [comment]
Something like this should work:

```rb
image = Refile.store.upload(record1.image) # S3 COPY, since `record1.image` is a Refile::File from S3
record2.update(image_id: image.id)
```

**Comment by grosser** [comment]
thx that worked! :D
