### ISSUE TITLE
Adding an User-Agent to Refile's image download request

### ISSUE THREAD

**Issue by shmay** [refile/refile#460]
Sometimes Refile's request to download a remote image is being blocked, due to the image host's attempts to block bots (we're doing a lot of scraping).  My workaround locally has been to add a user_agent to RestClient's download request here: https://github.com/refile/refile/blob/master/lib/refile/attacher.rb#L108.

Ultimately what I'm requesting: a way to add a User-Agent to Refile's request to download an attachment.  

I suppose it could also be helpful to have a general `options` hash that we could pass into RestClient's DL request as well.

In the meantime, maybe I should monkey patch the relevant method in RestClient?

Thank you for creating Refile and any help with this issue.

**Comment by shmay** [comment]
Ok, I was able to solve the problem by monkey patching RestClient like so:

```
module RestClient
  class Request
    def default_headers
      {:accept => '*/*; q=0.5, application/xml', :accept_encoding => 'gzip, deflate', :user_agent =>  "#{my_user_agent}"}
    end
  end
end
```

I'll leave it open for now in case anyone has any thoughts, but otherwise feel free to close it.  Thank you.

**Comment by sobrinho** [comment]
Closing due to the lack of activity but I would be glad to merge a PR setting an user-agent like "Refile x.y.z" or even a configuration for that.
