### ISSUE TITLE
show image on prawn pdf

### ISSUE THREAD

**Issue by vonchristian** [refile/refile#461]
I'm trying to show uploaded image to a pdf using gem 'prawn'.
image "#{@member.profile_photo}", :at => [40, 150] 
but it produces 
# Refile::File:0x007f0df61bcf78 not found

**Comment by abitdodgy** [comment]
You need to call `attachment_url(@member, :profile_photo)`, or `Rfile.attachment_url ...` if the helper isn't available.

**Comment by vonchristian** [comment]
I've tried Refile.attachment_url(@member, :profile_photo) but it returns 
attachments/9a8582928a03c363866984372cdbbb6cfa62bab7/store/2565edb8468e7ed7b356ac60ecc456f098d415888396625551a197de7234/profile_photo not found

**Comment by klarahirao** [comment]
It should look like this: 
```ruby
image @member.profile_photo, :at => [40, 150] 
```

you don't need interpolation here.

**Comment by danieldraper** [comment]
@vonchristian I have used Prawn and Refile, I'm using the following code:

```ruby
image open(@member.profile_photo.download), at: [0, cursor], fit: [80, 80]
```
