### ISSUE TITLE
Links to uploaded assets lost after every deployment with Capistrano 3 on Linux VPS

### ISSUE THREAD

**Issue by rmilushev** [refile/refile#463]
What is the correct configuration for Capistrano to keep uploaded assets after deployment process?

**Comment by wkurosawa** [comment]
Are you using FileSystem backend? If so, you should be using a config on Capistrano to create shared folders between versions, I guess it's `linked_dirs` option. 

Uploading to a remote server like AWS S3 should be working without any effort.

**Comment by rmilushev** [comment]
@wkurosawa I have tried both - file system and fog/rackspace. The problem is that when I include `attachments` to `linked_dirs` , uploaded assets vanish after deploy. I suppose that Capistrano restarts Sinatra app and it is all gone.

When I use fog, I can see uploads in the storage. It seems after deploy they are referenced with different names. That's why I get 404 after each deploy.

Can you post an example of `config.rb` with `linked_dirs` ?

Thank you for your time, @wkurosawa

**Comment by wkurosawa** [comment]
:-) 
Capistrano configuration will depends on how your refile backend is set. 
If is 
```ruby
Refile.cache = Refile::Backend::FileSystem.new("tmp/cache")
Refile.store = Refile::Backend::FileSystem.new("tmp/cache")
```
Then I guess your `deploy.rb` should be
```ruby
set :linked_dirs, fetch(:linked_dirs, []).push('tmp/cache', 'tmp/store')
```

**Comment by rmilushev** [comment]
@wkurosawa Absolutely! I've just tested it and I can confirm that it is the solution. Thank you again.

**Comment by wkurosawa** [comment]
@rmilushev you're welcome! 
Can you close the issue, since it's not really related to refile and also solved :-)

**Comment by rmilushev** [comment]
You are right, it is not Refile related. But I hope it would be helpful anyway. :)
