### ISSUE TITLE
Download image from the same host

### ISSUE THREAD

**Issue by tanraya** [refile/refile#464]
Hello guys!

I'm trying to download image from the same host as my app and nothing happens, but when I download image from remote host, it works.

Does anyone have issues with that?

**Comment by janko-m** [comment]
If by "nothing happens" you mean that it hangs indefinitely, it could be that in development you're using a single-threaded web server (e.g. WEBrick), so when one request is being processed and wants to do an HTTP request a URL of your app, it can't because it has to wait for the current request to finish first, but that request won't finish because it's waiting for that HTTP request, so it infinitely hangs.

**Comment by janko-m** [comment]
If that's the case, the solution is to use Puma or Unicorn (Thin should probably also work, although I'm not sure), which support multiple requests at the same time.

**Comment by tanraya** [comment]
In production environment at remote server (with Unicorn) I run following code in the console:

```ruby
p = Publication.first
p.remote_photo_url = 'http://mywebsite.com/uploads/image.png'
p.save!
```

And... Photo is not been downloaded. But when I specify image from Google Photos for example, it works as expected:

```ruby
p = Publication.first
p.remote_photo_url = 'http://news.bbcimg.co.uk/media/images/73820000/jpg/_73820506_mikerawlingsbbc.jpg'
p.save!
```

Both images are exists.
Any thoughts on that?

**Comment by janko-m** [comment]
What does "Photo is not downloaded mean"? What exactly happens? Does the request raise an error? Does it not complete? Is the request successful but the file is empty? Or nothing gets attached to the record?

Can you successfully open that URL in the browser? If not, Refile should add a validation error to the model.

**Comment by tanraya** [comment]
It means file is not appears on disk. And no exceptions! o_O

**Comment by sobrinho** [comment]
Closing due to the lack of activity.

If you are still having this issue, feel free to reopen sending the URL that's not working to be able to debug.
