### ISSUE TITLE
link_to attachment_url is a direct download by default.

### ISSUE THREAD

**Issue by EminenceHC** [refile/refile#467]
I want this link to open the file in the browser, but it downloads the file instead.

`<%= link_to " Certification", Refile.attachment_url(f.object, :file_1) %>`

If this is intentional behavior, how would I get the link to open in the browser instead?

**Comment by wendelscardua** [comment]
@EminenceHC I'm doing this, and it works file:
```ruby
link_to thing.title,
        attachment_url(thing, :file),
        title: thing.title,
        target: '_blank'
```
Do you have `file_1_content_type` and `file_1_filename` metadata on your model as well? If the browser doesn't know if your file can be opened, it'll always download instead of opening.

**Comment by EminenceHC** [comment]
I am not sure what metadata I should have. Here is all that is in my model:

attachment :file_1
validates_presence_of :file_1

and my DB column: file_1_id

thing ==  a form object. Not sure if that would make any difference. If it helps, this file is being stored on a nested model, which is why I am using the form object instead of an instance variable.

**Comment by sobrinho** [comment]
This is only true when you don't have the `{attachment}_content_type` column because in this case, the content type will be `application/octet-stream` and this forces the browser to download the file.

Maybe we can improve the documentation about that in the future, PRs are welcome.
