### ISSUE TITLE
attachment_url does not provide correct document or document extension

### ISSUE THREAD

**Issue by chevinbrown** [refile/refile#471]
I'm trying to use refile for documents (.pdf, .xlsx, etc.). When using `link_to` and `attachment_url(@document, :power_point)`, I get a weird url that looks like `localhost:3000/documentz/234...3432/document`...

Is this correct? Do I need to change something in my setup?

**Comment by mmplisskin** [comment]
It may be possible that you are getting the incorrect url because :power_point is not a format.  As per the source [here](https://github.com/refile/refile/blob/master/lib/refile.rb#L374) 

I am not completely sure about this just a thought.

**Comment by mmplisskin** [comment]
As per the source [here](https://github.com/refile/refile/blob/master/lib/refile.rb#L374) you could try adding the extension. Maybe store the document extension and when using attachment_url helper specify format: "ppt"

**Comment by chevinbrown** [comment]
I have added the format and my attachment_url helper outputs a really weird string for the url, which is 404'd.

**Comment by mmplisskin** [comment]
Without seeing snippets it is not possible to tell what is going on.. Are you sure the file is there?

**Comment by chevinbrown** [comment]
@mmplisskin, if I visit my ubuntu file host, I can see in my `rails_root/tmp/uploads/store` that files are created there.
They're excel files and I've used the tutorial provided to add the file format, or I've tried other methods by googling. Currently, my attachment url looks like: `attachment_url(kb, :document, kb.try(:document_content_type)` and generates a url like: `root_url/attachments/ea6634469abb076d447a7479dbb4ee02d1a60f56/store/application/vnd.ms-excel/a2b60ed8b2d7f0afde72e768f8dc5eb511b6cb17f68241d6491fd3cf2a58/Acronymns1.xls`, but when I click, I get a nginx 404.

**Comment by chevinbrown** [comment]
This is what I had to end up implementing:

```
  def file_extension
    require 'rack/mime'
    Rack::Mime::MIME_TYPES.invert[document_content_type].split('.').last
  end
```

**Comment by sobrinho** [comment]
I think this was a typo because the helper signature is like this:

```ruby
attachment_image_tag(@user, :avatar, format: :svg)
```

If you want the format to be automatic, you need to create an `avatar_content_type` column as a string and do not need to do anything else.

We are going to improve this documentation later.
