### ISSUE TITLE
Redirect to resource not working when using direct: true

### ISSUE THREAD

**Issue by drale2k** [refile/refile#473]
When i use `direct: true`, an xhr request as expected is sent in the background but when i submit the form after that, i get an error when i try to redirect to the resource. 

```ruby
  def create
    @upload = Upload.new(upload_params)
    if @upload.save
      redirect_to @upload
    else
      render :index
    end
  end

  def upload_params
    params.require(:upload).permit(:file)
  end
```

Error
`No route matches {:action=>"show", :controller=>"uploads", :id=>nil} missing required keys: [:id]`

Problem is that with `direct: true`, no ID is passed in the params anymore so it does not know where to redirect to. 

Am i using direct uploads incorrectly? It works fine without direct uploads though.

**Comment by drale2k** [comment]
Bump. Anyone an idea on this one?

**Comment by mmplisskin** [comment]
Tested with version 6.2 and could not recreate.

**Comment by jnicklas** [comment]
This is probably not related to Refile, it seems unlikely that it would affect the create action in such a way.
