### ISSUE TITLE
How to cache images after Refile process?

### ISSUE THREAD

**Issue by manfe** [refile/refile#476]
I am adding fragment caching (http://guides.rubyonrails.org/caching_with_rails.html#fragment-caching) to my homepage. And the images that are processed by refile coming from S3 bucket do not cache. Each request is a new process to load the images, and it's consuming more than 20 seconds to load entire home page (since there is like 20 images on it).

I didn't find anywhere any documentation to work with refile and caching.

Can anyone help me and perform caching with refile?

BTW: I am using, rails 4.2 and Image upload to Amazon S3.

**Comment by aglushkov** [comment]
Configure `Refile.cdn_host` https://github.com/refile/refile#3-rack-application

**Comment by manfe** [comment]
Thanks for replying. After more research and some tries I make it work.
