### ISSUE TITLE
Customize HTTP Response Headers

### ISSUE THREAD

**Issue by hughfm** [refile/refile#477]
Does anyone have a suggestion on how I might customize the HTTP headers that the Refile sinatra app responds with? I am integrating with pdf.js and there are a couple of necessary CORS headers I need to set. 

Most importantly, I need to set: Access-Control-Allow-Headers  'Range'. 

Any thoughts greatly appreciated, thanks for all the work on Refile.

**Comment by janko-m** [comment]
I think you should be able to use the [rack-cors](https://github.com/cyu/rack-cors) middelware, and if you want just scope it Refile's endpoint.

**Comment by hughfm** [comment]
Thanks @janko-m, you were absolutely right, although it took me a bit of fiddling to get right. I found [this article](http://blog.carbonfive.com/2012/02/27/supporting-cross-domain-ajax-in-rails-using-jsonp-and-cors/) particularly helpful if anyone else is wrestling with [rack-cors](https://github.com/cyu/rack-cors).
