### ISSUE TITLE
dropzone.

### ISSUE THREAD

**Issue by holden** [refile/refile#484]
Hi,

I'm trying to find enough information to get refile working with [Dropzone](http://www.dropzonejs.com/) for an `Asset` model which takes multiple files (images/pdfs, etc).  I'm pretty sure I could get it to work the normal way by providing it just the basic form / post request url for the controller, but then I wouldn't get any of the benefits of using refile.

eg `<%= form.attachment_field :media, direct: true, presigned: true %>`

My question is how would I go about doing the same thing thru Dropzone and Refile JS or how can I upload directly to the S3 refile cache directory and submit the correct information thru the form?

A lot of what the Refile does happens somewhat magically, which is great, but it makes this harder to figure out than say Carrierwave did.

Any pointers (or cautionary tales) would be appreciated!

Thanks,

**Comment by nofxx** [comment]
Hello @holden, problably not the answer you're looking, but a tale:
It was pretty boring to integrate dropzone with carrierwave (our current setup).
We ended up using: http://fineuploader.com  . Would be nice to integarte with refile...heh

**Comment by pablocrivella** [comment]
Hi @holden did you manage a way to make the integration? Any advices?

**Comment by holden** [comment]
We did.  We haven't yet managed to get it working with direct uploads to S3 (and presigned) but it works fine when uploading thru the application with dropzone.

**Comment by sobrinho** [comment]
Closing due to the lack of activity, feel free to reopen if this is still an issue.

Remember that the wiki is enabled now, feel free to collaborate there saying how you did these 3rd integrations.

**Comment by lsarni** [comment]
@holden how did you manage to open to the cache when using Dropzone?
