### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by manfe** [refile/refile#485]
Guys, I have to create a issue for this, because I couldn't find anything about it.

Well I am using Rails 4 and Ruby 2.2.4 and I am uploading a SVG file to a S3 bucket.

I can upload the file and display correclty the SVG file while it's on `cache` folder, but when it's moved to `store` folder and lose the extension. If I try to display the image using the `attachment_url(<resource>, :logo, filename: :svg)` it loses the XML content for SVG file.

How can I use SVG files with Refile?

**Comment by sobrinho** [comment]
It's working on the master with latest rails released, just make sure that you use `format` instead of `filename` as you showed.
