### ISSUE TITLE
Using Refile multiple upload in Rails engine

### ISSUE THREAD

**Issue by kinsomicrote** [refile/refile#487]
I came across this error `undefined method`file_id_will_change!' for #<Qeturah::Image id: nil, created_at: nil, updated_at: nil> Did you mean? id_will_change!` when I submitted the form.

Am I supposed to generate a column called `file` in `qeturah_images` table?

**Comment by supermomonga** [comment]
Same problem happened here.

## models

```
class NotificationIcon < ActiveRecord::Base
  belongs_to :magazine
  attachment :file
end
```

```
class Magazine < ActiveRecord::Base
  has_many :notification_icons, dependent: :destroy
  accepts_attachments_for :notification_icons, attachment: :file, append: true
end
```

## permit setting (magazines_controller.rb)

```
params.require(:magazine).permit(:name, notification_icons_files: [])
```

## form html (.slim file)

```
= simple_form_for(@magazine) do |f|
  = f.input :name
  = f.input :notification_icons_files, multiple: true, as: :attachment, direct: true, presigned: true
  = f.button :submit, class: 'btn-primary btn-block'
```

here is the magazine_params value.

```
{"name"=>"Test",
 "notification_icons_files"=>
  ["[{\"id\":\"349058319fba28f1157a855524da5b3beeb9ca8a174e4ea79f83be19a755\",\"filename\":\"computer_email.png\",\"content_type\":\"image/png\",\"size\":275420}]"]}
```

## error message

```
undefined method `file_id_will_change!' for #<NotificationIcon:0x007f943b694840>
Did you mean?  file_will_change!
               file_change
               file_changed?
               id_will_change!
```

**Comment by philiplindblom** [comment]
Same problem here.

**Comment by juddey** [comment]
Not in a rails engine, but I did find that if I only included some of the [optional fields](https://github.com/refile/refile#additional-metadata) (in my case I omitted the _filename_) then I got the same error.

**Comment by philiplindblom** [comment]
I came up with the idea of using multiple tables in the database for each image. so image one is :image_1, :image_2, :image_3. Works good in case you need to upload more than 1, but not hundreds of images.

**Comment by JapArt** [comment]
Having the same issue here with an image model with polymorphic associations.

**Comment by sobrinho** [comment]
This is error seems to be related to missing the `file_id` on the notification icon table (or your similar table) or maybe just restart the rails server (I've seen the schema reflection failing couple times before a server restart).

Since I'm having success by using this same code with Refile's master, I'm closing this.

Feel free to reopen if you are still experiencing this issue.
