### ISSUE TITLE
Issues rendering uploaded images in Rails engine.

### ISSUE THREAD

**Issue by kinsomicrote** [refile/refile#488]
I was able to successfully fix the uploading of the images, but I am running into issues with the rendering of the images.
Here is what I have in my `show.html.erb`:

```
<p><%= attachment_image_tag(@product, :images_files_data, :fill, 300, 300) %></p>
```

This is the error I get:

```
undefined method `images_files_data_attacher' for #<Qeturah::Product:0x007f22a8d6d900>
Did you mean?  images_files_data
```

Any help on this?

**Comment by sobrinho** [comment]
This error is a bit obscure but this means that you are using it in the wrong way.

If you have a product that has many files, you probably want something like:

```erb
<% @product.images.each do |image| %>
  <p><%= attament_image_tag(image, :file, :fill, 300, 300) %></p>
<% end %>
```
