### ISSUE TITLE
Support for Vector Based Images

### ISSUE THREAD

**Issue by taylorbrooks** [refile/refile#491]
I'm able to upload vectors images (.ai, .eps, .svg) fine.

But when I use the display code:

``` ruby
<%= attachment_image_tag(@order, :artwork) %>
```

The middleware returns a `200`, but I get a broken image.

Anyone else face similar challenges displaying SVGs?

**Comment by manfe** [comment]
I had the same issue, couldn't find a way to print the image with the same format.

**Comment by sobrinho** [comment]
If your attachment only accepts svg, you can force the type on helper:

```ruby
attachment_image_tag(@user, :avatar, format: :svg)
```

If you accept more than one, or just want it to be automatic, you need to create a `avatar_content_type` column as a string.

We are going to improve this documentation later.
