### ISSUE TITLE
What happened to the wiki?

### ISSUE THREAD

**Issue by goodviber** [refile/refile#492]
I think there used to be a wiki associated with this gem, unfortunately the previous link to it on SO no longer functions, and it is not easy to get info re the various image processing methods available , etc...

**Comment by sobrinho** [comment]
Not sure what was there before but I just enabled it again.

Feel free to collaborate there, thanks! <3

**Comment by abitdodgy** [comment]
Just for the record, @goodviber @sobrinho, this repo never had a wiki. It was discussed, and I even offered to do one, but the original author, @jnicklas, doesn't like wikis and thinks they tend to fall in disrepair, hence why one wasn't created.

**Comment by sobrinho** [comment]
I see.

Let wait to see what will happen to the wiki in the next months and if do not get a positive result from the community, we disable it again.

Thanks! <3

**Comment by goodviber** [comment]
Even more importantly, whats happening with the rails 5 issue?

On Tue, Oct 31, 2017 at 12:43 PM, Gabriel Sobrinho <notifications@github.com

**Comment by sobrinho** [comment]
I think it's working on master, I'm going to close more issues before releasing a new version.

Can you try the master?
