### ISSUE TITLE
Refile::App: Error -> ImageMagick/GraphicsMagick is not installed

### ISSUE THREAD

**Issue by nfunwigabga** [refile/refile#496]
I have Refile working in development and I upload images to s3 bucket just fine. But when I deploy it to production, the images still upload but they do not get retrieved. I looked at the logs and I have the error:

`App 494 stdout: Refile::App: Error -> ImageMagick/GraphicsMagick is not installed`

I have both imagemagick and graphicsmagick installed on my server (Ubuntu 16), and I am using Capistrano and Nginx. Images upload with no issues and I can see them in the bucket, but I cannot retrieve them. Anyone facing this recently?

**Comment by willnet** [comment]
I haven't faced this error. 
But I think that you don't put imagemagick and graphicsmagick to your server's PATH.
Did you check it?

**Comment by sobrinho** [comment]
As commented, the ImageMagick isn't in your PATH.

Feel free to reopen or create a new issue if you still have this issue, thanks! <3
