### ISSUE TITLE
integration with active admin gem for backend

### ISSUE THREAD

**Issue by kerensei** [refile/refile#498]
I want to make an image upload on the admin panel with refile uploader.
Active admin depends on formtastic form builder, so I added "refile-input" gem which integrates refile with formtastic, and built a form for my Cover.rb model:

**Gemfile:**

```
gem 'activeadmin', github: 'activeadmin'
gem "refile-input", require: ["inputs/refile_input"]
#image uploads
gem "refile", require: "refile/rails", github: 'refile/refile'
gem "refile-mini_magick"
gem "refile-s3"
```

**admin/cover.rb**

```
ActiveAdmin.register Cover do

  permit_params :caption, :role, :image, :shop_id, :tag_ids => [],
  items_attributes: [:id, :title, :price, :currency, :url, :image, :remote_image_url, :_destroy]

  form multipart: true do |f|
    f.inputs do
      input :shop
      input :image, as: :refile
      input :caption       
      input :promotion
      input :expiration
    end      
end
```

I submitted an image and got this error:

```
IOError in Admin::CoversController#create
closed stream

lambda do |*args, &block|
    target = self.__getobj__
    target.__send__(mid, *args, &block)
  end
end
```

Any thoughts?
Also, would appreciate input on how to display images on active admin index page.
Thanks! 
Keren

**Comment by Jamevid** [comment]
Does it work for you outside Active Admin? 

The methods for uploading and displaying are the same outside / inside Active admin.

**Comment by sobrinho** [comment]
Closing due to the lack of activity.
