### ISSUE TITLE
attachment_image_tag prints wrong cloudfront URL

### ISSUE THREAD

**Issue by imfaisalkh** [refile/refile#500]
I'm using refile gem for file uploading and I'm uploading files directly to my amazon s3 public bucket. The files are being uploaded just fine to following URL:

`https://s3.amazonaws.com/{bucket-name}/store/6309035935359dca1ef549170e7facac9ab3553ad53946cea0bcb8335475`

I'm using amazon cloudfront to serve these assets from s3, so the cloudfront url, for the asset given above, is something like this:

`https://{distribution-name}.cloudfront.net/store/6309035935359dca1ef549170e7facac9ab3553ad53946cea0bcb8335475`

The both urls when accessed directly through browser works fine. To display this asset in my app view file I'm using refile gem following helper function:

`attachment_image_tag(@post, :profile_img, :fill, 350, 350)`

Now the issue is, this helper method prints a URL something like this:

`https://{distribution-name}.cloudfront.net/attachments/5845d0a97dc77a57b5b05742a1eb26d629d7cdaa/store/fill/350/350/6309035935359dca1ef549170e7facac9ab3553ad53946cea0bcb8335475/file`

As this URL is different from above cloudfront URL, it is not displaying the image. How do I force `attachment_image_tag` function to print the correct cloudfront URL?

Here is my `refile.rb` file:

```
# config/initializers/refile.rb
require "refile/s3"

aws = {
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  region: "us-east-1",
  bucket: ENV['export S3_BUCKET'],
}

Refile.cache = Refile::S3.new(prefix: "cache", **aws)
Refile.store = Refile::S3.new(prefix: "store", **aws)
Refile.cdn_host = "https://{distribution-name}.cloudfront.net"
```

**Comment by hughfm** [comment]
It sounds like you may have set up your Cloudfront distribution with your S3 bucket as its origin? Refile, however, does not generate URLs directly to files on S3 (see README section 3. Rack Application). You'll therefore want to set your Cloudfront distribution's origin to be the URL of your _application_. That way, files will be streamed from your application on the first request, and cached by Cloudfront for future requests.

**Comment by imfaisalkh** [comment]
Thanks. The docs are a bit confusing for newbies.

Yes, I've set cloudfront distribution origin with my S3 bucket. I've setup another cloudfront distribution with my app's URL but it is not working either.

**Comment by hughfm** [comment]
I'd suggest having a read of this article, which is linked to in the readme - http://www.happybearsoftware.com/use-cloudfront-and-the-rails-asset-pipeline-to-speed-up-your-app.html

Has a good explanation of CDNs, and how to set up Cloudfront.
