### ISSUE TITLE
Upload endpoint for refile gem

### ISSUE THREAD

**Issue by imfaisalkh** [refile/refile#501]
I'm using refile gem to upload multiple files to my S3 bucket through cloudfront CDN and it is woking just fine with standard file attachment field. But now I want to enhance front view experience by implementing drag and drop file JS library on front-end. For this I've chosen http://fineuploader.com/ and I've taken initial steps to integrate it with my view file.

However, now this plugin require us to specify the URL where it should send uploads and server requests to. This endpoint can be an absolute path or a relative path. More information could be found here: http://docs.fineuploader.com/quickstart/02-setting_options.html

But I'm not sure what endpoint this should be, considering I'm using Refile gem on server side for uploading.

PS: "Shrine" gem provides upload endpoint, which makes it easier to integrate with other services. More information can be found here: https://github.com/janko-m/shrine#direct-uploads

**Comment by sobrinho** [comment]
You can use `/:backend` to upload directly to refile: https://github.com/refile/refile/blob/3dc5f524c831484a24fa4398194bee2a58a3bd1c/lib/refile/app.rb#L69-L77

Not sure if it will integrate with fine uploader easily but that would be the start point.

Closing <3
