### ISSUE TITLE
Images not working on Microsoft Edge

### ISSUE THREAD

**Issue by maxcodes** [refile/refile#502]
None of the images served by Refile are working on Microsoft Edge. They are coming across as application/octet.

**Comment by yannvery** [comment]
This can be fixed if you add metadata informations into you database as described on [github page](https://github.com/refile/refile#additional-metadata).

I've checked this on a simple refile example app with refile 0.6.2 and MS Edge 25.10586.0.0 / EdgeHTML 13.10586.

I don't know if it must considered as a refile issue or edge issue.

**Comment by maxcodes** [comment]
Thanks! I must have missed this. Let me try that out and see if it works. As to whether it's a refile issue or edge....not sure. Edge is the only one where it's happening, but on the other hand it's not like all images are broken on Edge, so I guess a little bit of both?

cc/ @seque1990

**Comment by ChanChar** [comment]
@maxcodes Running into the same issue but may be due to edge's inability to distinguish `image/jpg` which isn't a valid mime type from the valid `image/jpeg`

**Comment by maxcodes** [comment]
Interesting. Where is the relevant code? @ChanChar Is it something we can fix in Refile?

**Comment by ChanChar** [comment]
@maxcodes May just be an edge issue, still investigating it on my end but the only broken images on our end are from uploading 'image/jpg'. A suggested, but untested in production, workaround was to check for `image/jpg` before uploading/downloading and labeling it as `image/jpeg` since they're the same format.

**Comment by yannvery** [comment]
@maxcodes I suspect Refile ( or Sinatra / Rack ) to only use the extension of a filename to determine the file content-type.
I've done a test with extensions `.jpeg` and `.jpg`  both have been served as `image/jpeg`.

**Comment by abitdodgy** [comment]
@maxcodes we had the same issue in edge until we added the meta columns, and then it's worked just fine.

**Comment by sobrinho** [comment]
Closing due to the lack of activity.

I believe this is an Edge issue but I don't have access to it.

Feel free to reopen or create a new issue if you find it again.
