### ISSUE TITLE
Some images seems broken while uploading from remote URL

### ISSUE THREAD

**Issue by cintrzyk** [refile/refile#507]
**What did you do?**
configure sample app https://github.com/refile/refile_example_app
goto `rails console` then try to upload image from remote source:

``` ruby
Post.create(remote_image_url: "http://static2.businessinsider.com/image/57c0bcd2b996eb7a018b4d21-1190-625/what-its-like-to-win-a-bidding-war-for-apples-one-of-a-kind-unicorn-computer.jpg", title: 'Post-test', body: 'test-body')
```

then show the image with original size:

``` ruby
  <%= attachment_image_tag(@post, :image) %>
```

**What did you expect to happen?**
Expected to see image.

**What happened instead?**
Image doesn't load.
![image](https://cloud.githubusercontent.com/assets/494720/18050077/910e8be2-6dec-11e6-88fc-6db5cb5fbb82.png)

**Comment by sobrinho** [comment]
Can not replicate, feel free to reopen if you are still seeing this.
