### ISSUE TITLE
Crop image while uploading Image using Refile 

### ISSUE THREAD

**Issue by chetan-wwindia** [refile/refile#509]
I have tried many different stuff but not able to find success. I need to implement Cropping option while I upload image using refile gem 
My basic implementation is working fine. 
   Option I m currently working on 
      - using Jcropper I have cropped the image on the front end but not able to insert it as image object to the form.
  current input field looks like this 
           `= bf.attachment_field :hero_image, direct: true, presigned: true`
I had googled options for cropping with refile but couldn't find any.

**Comment by jeffAwesome** [comment]
Did you ever find out a solution for this?

**Comment by sobrinho** [comment]
There is no official way but I see a few options:

1. Submit the cropped image to your application (as file or base64) and then save it
2. Use a cropper plugin that supports direct upload to S3, in a temp bucket, and then submit the remote URL by using `remote_{attachment}_url`
3. Use a cropper plugin that submits the arguments of the crop, submit the image direct to s3 and crop it in the background

I think it depends on the crop plugin that you are using, none of the options are the ideal of course, but would do the job.

Feel free to suggest anything different if you see a better option, thanks! <3
