### ISSUE TITLE
Error when trying to use simple_form with "multiple: true"

### ISSUE THREAD

**Issue by nest4less-dev** [refile/refile#511]
I get the following error when using simple_form for a multiple image (i.e.) upload field.

```
= f.input :uploads_files, as: :attachment, multiple: true, direct: true, presigned: true

undefined method `klass' for nil:NilClass
```

**Comment by sobrinho** [comment]
Couldn't reproduce with Refile master and latest simple form.

Probably a mistake like using a wrong variable on simple_form_for.

Closing due to the lack of activity.
