### ISSUE TITLE
Remote image download in background

### ISSUE THREAD

**Issue by JoshuaNovak919** [refile/refile#514]
I have the remote url being filled out after a direct upload to S3, but I want to have refile do the image work in the background. Anyone know a good way to handle this?

**Comment by bufordtaylor** [comment]
I recommend having a background processor like sidekiq download the file and process after refile has uploaded it to s3.

1. Refile uploads to s3
2. Successful saves kicks off sidekiq job
3. sidekiq pulls down the file from s3 (`Refile.attachment_url(object, :some_image)`) and performs work on the image and then saves it as an absolute URL to s3. 
4. You can safely delete your refile store now

This also gives you the advantage of not processing your images on every GET request (regardless of CDN)

**Comment by abitdodgy** [comment]
@bufordtaylor how do you get the direct S3 URL?

**Comment by sobrinho** [comment]
@abitdodgy `Refile.attachment_url(object, :some_image)` would do the job if your backend is configured correctly.

If you are going to save the record and then later migrate it to the model, you can create a string attribute on your model for that and process in the background to upload like this:

```ruby
model.remote_avatar_url = model.temp_remote_avatar_url
model.save
```

_Assuming that `temp_remote_avatar_url` is your column for that.
