### ISSUE TITLE
Upload Progress details not working in heroku app

### ISSUE THREAD

**Issue by samueljanes** [refile/refile#516]
I'm trying to make a rails app with refile that has user images.

For these images I want a progress bar that displays how much and image has uploaded, and then when the upload is complete

Here is my code

```ruby
/** users/show.html.erb **/
        <% if @user == current_user %>
            <%= link_to "Edit Account", edit_user_registration_path %>
            <%= render 'image' %>
        <% end %>

/** image partial **/   

<div class="row">
    <% @user.images.each do |image| %>
        <div class="col-1-2 images">
            <div class="picture-card" style="background-image: url('<%= attachment_url(image, :picture) %>')"></div>
            <%= link_to "Delete Image", url_for([@user, image]), :method  => :delete %>
        </div>
    <% end %>
    <div class="col-full form">
        <%= render "image_fields" %>
    </div>
</div>

/** image_fields partial **/

    <%= form_for [@user, Image.new] do |f| %>
        <%= f.label :picture, class: "image-label" do %>
            <div class="picture-card new">
                Add an image
            </div>
        <% end %>
        <%= f.attachment_field :picture, direct: true, class: "image-form hidden" %>
        <div class="progress-bar hidden">
            <div class="progress-bar active" style="width: 0%">
                <span></span>
            </div>
        </div>
    <% end %>
    <script>
        $(document).on("upload:progress", "form", function(e) {
            $(".progress-bar").removeClass("hidden");
            var detail  = e.originalEvent.detail,
                percentComplete = detail.loaded / detail.total * 100;
            console.log(percentComplete);
            $(".progress-bar.active").width(""+ percentComplete +"%").find("span").text(""+ percentComplete +"%");
        });
        $(document).on("upload:complete", "form", function(e) {
            $(".progress-bar.active").addClass("complete").find("span").fadeOut(150, function(){
                $(this).text("Upload Complete").fadeIn(150)
            });

            setTimeout( function(){
              /** stuff here **/
            }, 750);

        });
    </script>
```

The issue is that detail.loaded and detail.total are working locally, but are displayed as NaN in production on heroku, rendering the progress bar useless

**Comment by wkurosawa** [comment]
What do you mean by "are not numbers"? It's string? Would a `parseInt()` work?

**Comment by samueljanes** [comment]
@wkurosawa I should have specified that better. Detail is part of the refile customEvent for ProgressEvent. It works fine locally, but displays as NaN instead of a number that jquery can use to style a progress bar

**Comment by wkurosawa** [comment]
I see, but I have been using a `parseInt` and it's working like a charm. 

```
 var progress = parseInt(data.loaded / data.total * 100, 10);
```

We have created a gem with Refile to encapsulate our file upload front end and been using Heroku, as you can see on this demo: 
https://filemagic-demo.herokuapp.com/

Also, code is at: https://github.com/flama/filemagic

**Comment by samueljanes** [comment]
@wkurosawa Thanks, but it didn't work. Its fine locally but in heroku it still shows that percentComplete is "NaN"

**Comment by mmplisskin** [comment]
Have you tried using presigned uploads? Im assuming you must have some sort of storage solution since you are using heroku.
https://github.com/refile/refile#presigned-uploads

**Comment by sobrinho** [comment]
Closing due to the lack of activity.
