### ISSUE TITLE
Migrate (back) from Sinatra to a Rack application ?

### ISSUE THREAD

**Issue by EtienneDepaulis** [refile/refile#520]
Hello guys,

when updating to Rails 5, one of the major pain was updating Sinatra and apparently we still need to point our Gemfiles to the github repo if we want to use it.

In our case two major gems depends on Sinatra: Refile and Sidekiq.

Sidekiq team decided this summer to remove Sinatra dependency (see https://github.com/mperham/sidekiq/pull/3075 and https://blog.codeship.com/replacing-sinatra-with-rack-in-sidekiq/

This leaves us with only Refile which depends on Sinatra.

We are great fans of Refile philosophy for many reasons and we would like to help on this topic but we noticed that version `0.4.0` [migrated](https://github.com/refile/refile/blob/d7a42dcd7cf631ba94b01231f535bda061f6af92/History.md#040) this gem from a Rack app to a Sinatra app and that migrating back to a Rack app would also suppress Sinatra's [hooks](https://github.com/refile/refile/blob/d7a42dcd7cf631ba94b01231f535bda061f6af92/README.md#authentication).

Before submitting a PR on this topic, I wanted to have the opinion on the subject :)

Is removing Sinatra dependency and switching back to a Rack app on the table or not ?
cc @jnicklas

**Comment by EtienneDepaulis** [comment]
Good to know @miyucy 

I'm guessing this gem is not actively maintained anymore. It's sad for such an awesome gem but I can truly understand it's a time consuming activity.
Thanks for all the work that was done so far @jnicklas :)

**Comment by sobrinho** [comment]
Hey, this is really interesting and I would like to see a pull request doing that against master, I would be glad to merge.

Closing <3 <3 <3
