### ISSUE TITLE
Multi-byte filename download error

### ISSUE THREAD

**Issue by shenhf** [refile/refile#521]
When google online office document editor opened  links generated by attachment_url(doc, :file), filename display as following:
%E4%BF%A1%E6%81%AF%E5%A4%84%E7%AC%AC%E5%8D%81%E5%9B%9B%E5%91%A8%E5%B7%A5%E4%BD%9C%E6%B1%87%E6%8A%A5.doc

  I know it's send_file parameter's problem.
  Is there any way to correct it ?

thanks.

 edit: 
 Finally define a custom action in documents controller:

def download
    send_file @document.file.download,
      :type => @document.file_content_type,
      :disposition => 'inline',
      :filename => @document.file_filename
  end

it works, not refile way!

**Comment by sobrinho** [comment]
Fixed on master.

**Comment by sobrinho** [comment]
a53308a12f0ba8bc8e473e3513749afc311f9ff3
