### ISSUE TITLE
undefined method `accepts_attachments_for'

### ISSUE THREAD

**Issue by Jirka1111** [refile/refile#524]
Hi,
I tried restart server etc., but the error is still there.

Project model:
accepts_attachments_for :images, attachment: :file

Image model:
attachment :file
belongs_to :imageable, polymorphic: true

I use:

Using refile 0.6.2 from https://github.com/refile/refile.git (at master@d7a42dc)

Does anyone have an idea why the method doesn't work?

Thank you in advance.

**Comment by mmplisskin** [comment]
Have you specified the parent relationship in the project model? 

```has_many :images, as: :imageable```

**Comment by Jirka1111** [comment]
Thank you for a quick answer :-)

The problem was solved by uninstall gem and installing again.

**Comment by wkurosawa** [comment]
@Jirka1111 looks like it's everything ok, right? Can you close the issue?
