### ISSUE TITLE
Replacing SHA1 hashes by SHA256 ?

### ISSUE THREAD

**Issue by yellowiscool** [refile/refile#525]
Hei,

I see that [refile is using SHA1 in its current version.](https://github.com/refile/refile/blob/90cbf2ac808b37dd5ce87104171499db07d6e522/lib/refile.rb#L451-L465)

[It seems that SHA1 is not safe anymore](https://shattered.io). Should refile use SHA256 instead ?

**Comment by walterdavis** [comment]
I'm pretty sure that these SHAs are used not for any sort of security, but to provide a unique key for the uploaded files. SHAs have the benefit that they are unique (when based on different inputs) and of a known string length. They also seem to be internally unique, such that if you only look at the first 8 characters of each, you have a significant chance of still remaining unique within the larger set of keys. At least this is how it works in Git. If my supposition is correct, then using a computationally less stressful method to generate them makes sense from a performance standpoint.

Walter
