### ISSUE TITLE
0 byte file

### ISSUE THREAD

**Issue by ericlormul** [refile/refile#530]
Hello,

I use Ajax to upload a image file:
```

function save_cropped_image(){
  crop.croppie('result', { type: 'blob', format: 'jpeg', quality: 0.5 }).then(function(result){
    var file = new File([result], 'myAvatar.jpg', { type: 'image/jpeg' });

    var data = new FormData;
    data.append('image[image]', file);
    data.append('commit', 'avatar');

    $.ajax({
      data: data,
      type: 'POST',
      url: '/images',
      cache: false,
      contentType: false,
      processData: false,
      success: function(response) {
        $('#myAvatar').attr('src', response.url);
        $('#image_crop').modal('close');
      }
    });

  });
}
```
refile successfully store the file in filesystem with correct file name, type... but the file size is 0 byte.
Looks like the has been successfully sent to sever (at least part of file), I can access the ActionDispatch::Http::UploadedFile object, but its size method returns nil.

Thanks in advance!

**Comment by valterbarros** [comment]
I'm have the same issue

**Comment by sobrinho** [comment]
Can anyone provide a test case or a sample application showing the issue?

**Comment by valterbarros** [comment]
@sobrinho I did use `file.try(:rewind)` on file, method from `ActionDispatch::Http::UploadedFile < Object`

Ref: http://api.rubyonrails.org/classes/ActionDispatch/Http/UploadedFile.html#method-i-rewind

**Comment by sobrinho** [comment]
@valterbarros are you using the crop too? Where did you put the rewind?

**Comment by valterbarros** [comment]
Before to send to model to create new record. I'm using rails 4.2.1 and ruby 2.2.5

> PS: This function prepare the params to send to model

```
def prepare_params params, file
  file.try(:rewind)
  { 
     file: file, 
     usuario_id: params[:usuario_id], 
     documentable_id: params[:documentable_id],
     documentable_type: ConstructionSiteProgressEvaluation::ContractProgressEvaluation::Contract.name,
     scope: :create_many 
  }
end
```

**Comment by sobrinho** [comment]
Are you using AJAX to send this request?

**Comment by valterbarros** [comment]
Yep

**Comment by sobrinho** [comment]
Can you try to **not** use AJAX to see if the problem persists?

**Comment by valterbarros** [comment]
I'll try and back here to talk about.

**Comment by sobrinho** [comment]
@valterbarros any news on that?

**Comment by valterbarros** [comment]
@sobrinho sorry buddy, I have been out of time

**Comment by sobrinho** [comment]
Okay, here are my findings:

1. This works on Chrome (latest release) but not on Safari (latest release) [I haven't tested with other browsers]
2. The problem is not with crop library or AJAX itself, the problem is the File API
3. On Chrome, using Rails 5.1 and Refile's master, I didn't have to rewind the file

So, the issue is about the browsers and not Refile itself.

We are probably going to support base64 uploads in the future, but until then, you are limited to use Chrome, sorry!
