### ISSUE TITLE
Gemfile rest-client dependency issue

### ISSUE THREAD

**Issue by tomituominen** [refile/refile#531]
Could the rest-client gem requirement be made a bit more lax? i.e. allow also rest-client 2.x ? 
Or is there a reason that only minor version updates are allowed?

**Comment by tomituominen** [comment]
According to the rest-client documentation:
"Users are encouraged to upgrade to rest-client 2.0, which cleans up a number of API warts and wrinkles, making rest-client generally more useful. Usage is largely compatible, so many applications will be able to upgrade with no changes."

**Comment by LeandroSNunes** [comment]
I'm going through the same problem.

https://github.com/rest-client/rest-client/pull/573

**Comment by sobrinho** [comment]
Fixed in #547, thanks for reporting! ❤️
