### ISSUE TITLE
when i upload PNG image using refile,minimagick it just goes blank.

### ISSUE THREAD

**Issue by negabaro** [refile/refile#532]
when i upload PNG image using refile,minimagick it just goes blank.
features of png image  which goes blank is bellow

```
black-and-white image
PNG image
```

sample image
wget -O test.png https://cloud.githubusercontent.com/assets/7065149/24034983/e12bb0a4-0b36-11e7-910f-d62fcc00330e.png

at first, I had doubted this problem is related to imagemagick or libpng version.
but i could not this problem even it change any version.(https://github.com/ImageMagick/ImageMagick/issues/412)

my question is 2

1. 
is there anybody who are having the same problem?

2.
could you get me a hint  how to do troubleshooting for resolve this problem?

**Comment by wkurosawa** [comment]
@negabaro Does this problem only occurs with Black and White images?
Have you tried to test Refile / Imagemagick running at a server, other than your computer?

**Comment by sobrinho** [comment]
Closing due to the lack of activity, feel free to reopen if you find this again.
