### ISSUE TITLE
Docs for integration with Dropzone or similar?

### ISSUE THREAD

**Issue by conwayanderson** [refile/refile#534]
Are there any docs or tutorials for integrating refile with Dropzone or similar? The existing resources I've found haven't been enough to figure this out. It'd be extremely helpful if the docs pointed to specific tutorials that cover this type of integration.

**Comment by sobrinho** [comment]
I just enabled the wiki for this kind of collaboration, feel free to document that there if you found the way to go.

Thanks! <3
