### ISSUE TITLE
Status of Refile?

### ISSUE THREAD

**Issue by holden** [refile/refile#535]
Hi,

We use Refile on a couple of projects and love it, no major problems but I've noticed it hasn't had an update in 11 months.  It also has a bunch of open issues and 22 open PRs, which might not mean anything except none of them has been accepted since last June (where has the love gone?).  

* Is this gem still being actively maintained? \*sniff\*  
* Or is it just that good / stable / awesome?

**Comment by holden** [comment]
Out of pure jealousy, I also cannot help but notice that [Pundit](https://github.com/elabs/pundit) enjoys frequent updates!

**Comment by abitdodgy** [comment]
@jnicklas it would be great to get some indication of your plans for Refile. We built an app around Refile (thanks for making it possible), but we have to decide whether to migrate or keep using it.

**Comment by conwayanderson** [comment]
+1

**Comment by sobrinho** [comment]
Hey, I'm working in the maintenance of refile but my opensource time isn't that much.

We have a lot of issues open and I'm trying to work against them, we have a lot of projects using refile and everything is pretty stable (except for the incompatibility with Rails 5.1 these days).

If anyone wants to help, feel free to grab random issues and confirm that they are still real or not and if they are, try to open a pull request against the master, I will be glad to review it.

Thanks! <3 <3 <3
