### ISSUE TITLE
How to get the S3 URL for saves files...

### ISSUE THREAD

**Issue by abitdodgy** [refile/refile#536]
Our app is crashing on large files (when they're streamed through Refile). Has anyone figured out a solution or a definitive way to get S3 URLs and bypass Refile on file downloads? That might solve the problem initially.

**Comment by mmplisskin** [comment]
You could consider using a cdn or scaling the deployment.  Another option is to make the s3 bucket public, get the temporary refile image url and reupload it with the s3 sdk. 
Something like this will get you a temporary image link.

```URI.parse(Refile.attachment_url(image, :file, format: :jpg)).tap{ |uri| uri.scheme = 'http' if uri.scheme.blank? }.to_s```
