### ISSUE TITLE
undefined method `partition' for ActionDispatch...

### ISSUE THREAD

**Issue by chevinbrown** [refile/refile#540]
Trying to do polymorphic uploads, getting this error consistently.
Follows this schema:

https://gorails.com/forum/how-to-i-use-refile-as-upload-in-a-polymorphic-way-i-have-managed-to-use-it-that-way-but-i-am-struggling-on-destroy-image-after-uploading

I assume this is a AWS failure, but I don't have that gem installed or aws configured yet.

Please help!

```
undefined method `partition' for #<ActionDispatch::Http::UploadedFile:0x007fb484ae67b8>
```

**Comment by sobrinho** [comment]
Unable to reproduce.

This is probably because you sent one file instead of an array to the backend, likely to missing `multiple: true` on the view.

**Comment by sobrinho** [comment]
To clarify, `partition` is an array method, used here:  https://github.com/refile/refile/blob/d7a42dcd7cf631ba94b01231f535bda061f6af92/lib/refile/attachment/active_record.rb#L98

**Comment by chevinbrown** [comment]
Sounds good. I think it was user error. Thanks for the followup.
