### ISSUE TITLE
Uploading pdf through remote_file_url

### ISSUE THREAD

**Issue by crhonox** [refile/refile#541]
i have an issue with this, i'm uploading some pdf through an active job, 
`h = {`
`        remote_file_url: cert_url,`
`        contractor_id: contractor.id,`
`        file_filename: cert_url.split("/")[8],`
`        file_content_type: "application/pdf"`
`     }`
`      Certification.create(h)`

i'm passing the file through a url and everything is fine, the problem is when i try to view the pdf, 
[https://imgur.com/jTpDIhx](url)
i'ts like the pdf is corrupted or something

**Comment by sobrinho** [comment]
1. This happens to any kind of file or just for PDF files?
2. Have you tried other PDF files?
3. Can you check the md5 or crc32 of the file before uploading and after downloading?

**Comment by sobrinho** [comment]
Closing due to the lack of activity.
