### ISSUE TITLE
attachment_url is incorrect after upgrade to 0.6.2

### ISSUE THREAD

**Issue by lsarni** [refile/refile#545]
I was using 0.5.3 but I wanted to add a CDN (which I haven't done yet) so I upgraded to 0.6.2.

Now `attachment_url` is generating this:
 `attachments/a66b14e11bd870170e75/store/fill/144/144/a0a1d934fff14bc684693d6f57469fa080dc5a90cd7e1a6fa9a9c/profile_image` 
when the actual image is at:
`attachments/store/fill/144/144/a0a1d934fff14bc684693d6f57469fa080dc5a90cd7e1a6fa9a9c/profile_image`

This is my `refile.rb` now:
```
require "refile/s3"
aws = {
  access_key_id: "AKA",
  secret_access_key: "B4P5u",
  bucket: "mybucket",
  region: 'us-east-1'
}
Refile.cache = Refile::S3.new(prefix: "cache", **aws)
Refile.store = Refile::S3.new(prefix: "store", **aws)
Refile.cache = Refile::S3.new(max_size: 100.megabytes, **aws)
```

And before:
```
require "refile/backend/s3"
aws = {
  access_key_id: "AKA",
  secret_access_key: "B4P5u",
  bucket: "mybucket"
}
Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)
Refile.cache = Refile::Backend::S3.new(max_size: 100.megabytes, **aws)
```

**Comment by sobrinho** [comment]
I do not recall if something has changed from 0.5.3, the URL is different but is it broken now? What's the error message?

**Comment by sobrinho** [comment]
Closing due to the lack of activity.
