### ISSUE TITLE
Updating associated records using nested fields removes existing attachments

### ISSUE THREAD

**Issue by flats** [refile/refile#548]
Given the following two models in a Rails 5.1 application using latest Refile master:
```
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  attachment :avatar
end

class User < ApplicationRecord
  has_one :profile
  accepts_nested_attributes_for :profile
  attachment :background
end
```
I'm able to attach an `avatar` to a `Profile` using nested fields when calling `@user.update user_params` in an `update` controller method. However, after that, updating the user record removes that `avatar` attachment from the `Profile`, even when `remove_avatar` is `false`. This is obviously unexpected behavior - unless I'm misunderstanding Refile, the attachment should be retained unless the `remove_avatar` parameter is explicitly set to `true`.

This seems to be isolated to using nested fields to update an association - it is not an issue when updating attachments on the parent model (in this case, the `background` attachment) or when calling `#update` on `@user.profile` directly.

This has worked properly in the past and appears to be the result of changes in Rails 5 or 5.1. Any guidance would be greatly appreciated. Thanks in advance for your time and your work on this wonderful library!

**Comment by sobrinho** [comment]
I'm unable to reproduce this with Refile's master and Rails 5.1.

Feel free to reopen if you are still seeing this or provide more information to help us debug this further.
