### ISSUE TITLE
full url of images

### ISSUE THREAD

**Issue by lbstephane** [refile/refile#552]
Hi,

I'm using Refile for attachements in my app, but also to upload images in a Trix editor to produce HTML code. This HTML is sent to a mobile application to display the content. So, my problem is, HTML code got only the path on the server and not the full url of my image.

Is there a way to do it ? Backend config or in js maybe ? Is it the same thing using s3 ? I really need to get full path.

I did this on my js file : 
```

document.addEventListener 'trix-attachment-add', (event) ->
    attachment = event.attachment
    if attachment.file
      return sendFile(attachment)
    return
```

```
sendFile = (attachment) ->
    file = attachment.file
    form = new FormData
    form.append 'Content-Type', file.type
    form.append 'image[image]', file
    xhr = new XMLHttpRequest
    xhr.open 'POST', '/images', true

    xhr.upload.onprogress = (event) ->
      progress = undefined
      progress = event.loaded / event.total * 100
      attachment.setUploadProgress progress

    xhr.onload = ->
      response = JSON.parse(@responseText)
      attachment.setAttributes
        url: response.url
        image_id: response.image_id
        href: response.url

    xhr.send form
```

**Comment by sobrinho** [comment]
You just need to return the full URL in your endpoint or configure Trix to save it as full URL (TinyMCE has this option, I don't know about Trix).
