### ISSUE TITLE
Limit image width or height only

### ISSUE THREAD

**Issue by molfar** [refile/refile#553]
How can I resize image to fit (fill) only one dimension: width or height?

`image_tag(attachment_url(product, :photo, :limit, 150, nil, fallback: 'packet-medium.png')`

I tried to pass nil - but it does not work.

**Comment by alexander-ruehle** [comment]
You can pass a ridiculously high number:
`image_tag(attachment_url(product, :photo, :limit, 150, 100000, fallback: 'packet-medium.png')`
This will match the width of 150 and will not create a Image with a height of 100000 pixel.

But I agree with you, an input of nil would fit better.

**Comment by sobrinho** [comment]
PRs are welcome for this feature 👍
