### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by rainerborene** [refile/refile#560]
The latest version of `refile` was published on 29 Oct 2015 on RubyGems. Is there any reason for not releasing a new version there? By the way, I'm planning to migrate from `sinatra` to a pure `rack` application. Would you accept that pull request? @sobrinho

**Comment by sobrinho** [comment]
@rainerborene I would absolutely accept that, as long the code remains simple and keeps the same behavior.

About the release, I'm going to contact @jnicklas to coordinate that.
