### ISSUE TITLE
Release a new gem

### ISSUE THREAD

**Issue by thomasfedb** [refile/refile#563]
Version `0.6.2` was released October 2015, and quite a lot as changed since then. Could a new version of the gem be released?

**Comment by sobrinho** [comment]
@thomasfedb will be soon, we are working on a lot of issues in the last weeks before releasing.

Use master until then.

**Comment by thomasfedb** [comment]
Thanks @sobrinho, was very pleased to see the recent commits and I'll be very happy to see a new release soon.

**Comment by runephilosof** [comment]
Any hope for a new release?

**Comment by sobrinho** [comment]
Refile is EOL'ed at this point. I will archive the repository.

Recommended to migrate to other solutions like the native one on Rails.
