### ISSUE TITLE
Changing the RandomHasher to urlsafe_base64

### ISSUE THREAD

**Issue by jolim** [refile/refile#567]
There may be a reason for shorter URLs for images. In particular, spamassassin cares how long a path is for a URL.

To shorten URLs slightly, it seems sensible to use base64 for the IDs instead of hex. The combinatorics allow for the ID to be 20 bytes long instead of 30, which means 28 character long IDs instead of 61.

I'm curious whether there is a strong rationale for hex. Is there a compatibility issue with different backends?

We are able to change the RandomHasher in the init, which is great; however, the `valid_id` method uses `/\A[a-z0-9]+\z/i`, which excludes a couple nonalpha characters.

So, ideally we would be able to replace the valid_id regex expression with a user-defined constant or some such, perhaps also kept as a method inside RandomHasher.

If that appeals, I'm happy to make a PR.

**Comment by sobrinho** [comment]
This is the safest way to store files.

I wouldn't recommend using anything besides alpha chars for file names, despite a lot of file systems allowing some special chars.

Remember that you can always create your own application's backend for generating different hashes, you only have to comply with the alpha chars requirement.

Cheers.
