### ISSUE TITLE
Upload fail when form has remote: true

### ISSUE THREAD

**Issue by lazaronixon** [refile/refile#66]
As not is possible submit multipart form with ajax request upload file this way will fail, I did a workaround via javascript to remove multipart atribute. but i think will be better prevent it on this line
https://github.com/elabs/refile/blob/61b38fc4f7ef7412ca716cf414a0e79268ed5aab/lib/refile/rails.rb#L7
something like

```
self.multipart = true unless self.options[:html][:remote]
```

**Comment by masonhale** [comment]
I agree this is a Rails UJS issue. But there is an event one can catch to work around it. I posted an example handler in #58
